### ISSUE TITLE
Enum cannot be serialized as string in CosmosDb

### ISSUE THREAD

**Issue by TechWatching** [Azure/azure-cosmos-dotnet-v3#1063]
I have an object that I wan't to save as a document in a CosmosDb container. This object contains some Enum properties. I did not find a way to serialize these properties as string in CosmosDb. They are serialized as their int value. I looked at CosmosSerializerOptions but I did not see a way to configure that.

Moreover, on my object the id of my document is also an ennum property so when I try to create the document I have this error: 
```
Microsoft.Azure.Cosmos.CosmosException: 'Response status code does not indicate success: 400 Substatus: 0 Reason: (Message: {"Errors":["The input name '0' is invalid. Ensure to provide a unique non-empty string less than '1024' characters."]}
```

Am I missing something or is handling enum not implemented yet in the sdk ? Is there any workaround known ? Maybe using NewtonSoft serializer as the serializer ?

**Comment by j82w** [comment]
The SDK is using newtonsoft as the [default serializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs). The CosmosSerializationOptions are setting that we found most users were setting and added to reduce friction. There hasn't been any other request for enums to string. You can specify a custom serializer on the [CosmosClientOptions](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/94d517b69245fd75185d8e364c721cb3fe42da74/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L364). This will allow you to do any custom setting for the serializer.

**Comment by TechWatching** [comment]
If the default serializer is newtonsoft shouldn't the attribute `[JsonConverter(typeof(StringEnumConverter))]`allow me to do what I want witout having to change settings ?
When you say that I can specify a custom serializer on the CosmosClientOptions you mean I have to dupplicate the `CosmosJsonDotNetSerializer` and only change my settings, that's right ? Just for a setting on enum, it's seems weird.

**Comment by j82w** [comment]
I did some testing and putting `[JsonConverter(typeof(StringEnumConverter))]` on the enum class or the property correctly serialized it to a string instead of a number.

**Comment by TechWatching** [comment]
🤔, I have to check my code. I have been trying without success to do that. Maybe I misplaced the attribute. I check and let you know.

**Comment by j82w** [comment]
Here is a PR #1065 of what I did.

**Comment by TechWatching** [comment]
Strange, I checked my code and everything seems fine. I have similar code than your PR and can't make it work... I always end up with a number in my document. I will check your PR more thoroughly to check for differences with what I have done. Thanks for the PR anyway.

**Comment by TechWatching** [comment]
I took your code and executed it in a new console app querying a real cosmos db and I got the same error that I had :
`Response status code does not indicate success: 400 Substatus: 0 Reason: (Message: {"Errors":["The input name '3' is invalid. Ensure to provide a unique non-empty string less than '1024' characters."]} `

**Comment by j82w** [comment]
By any chance do you have `using system.text.json` in your project? Is it a .net core 3.0 app? My only thought is that the `[JsonConverter(typeof(StringEnumConverter))]` is from the wrong package and that's why it's getting ignored.

**Comment by j82w** [comment]
Here is a simple console app that I tested and verified it worked.
[v3EnumTest.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/3902882/v3EnumTest.zip)

**Comment by TechWatching** [comment]
I succeeded to make it work. Thank you so much for your help @j82w !
What is weird is that I did the same thing that I was doing before but from another laptop. I wonder what was causing the issue ... but nevermind it works now, I will check my work laptop tomorrow.
I close the issue but I think it would make sense to add a setting for enum in the `CosmosSerializerOptions` in a future version of the sdk. Thanks again 👍.

**Comment by TechWatching** [comment]
By the way, you were right @j82w, on my console app where I tested, the JsonConverter attribute was the one from system.text.json and the StringEnumConverter from NewtonSoft. That was probably the same issue in my project. Quite easy to get lost 😃, I was lucky you were there to guide me in the right direction, thanks.

**Comment by udit0802** [comment]
I am also facing the issue with azure cosmos 3 with .Net6 core where System.text.json is the serializer library recommened.
Is there a way to make that work?

**Comment by wrkntwrkn** [comment]
Also, not sure if this is the right place or related to above, but enums are not working with Hierarchical Partition Keys partitions.

`<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.30.1-preview" />`

![image](https://user-images.githubusercontent.com/94405711/195327953-892a8f08-564b-48e1-99b9-80a656e2f690.png)

**Comment by chrisdreams13** [comment]
Is there a solution for this? why is closed? I continue having issues with **System.Text.Json.Serialization** as it's the recommendation since net core 3.1 and we are on days for net7 releases.

this works:
```
[Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
public Status Status { get; set; }
```
but this doesn't work and should:
```
[System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
public Status Status { get; set; }
```

using 
Microsoft.Azure.Cosmos 3.31.0
net 6.0.402

**Comment by dkapadia-jb** [comment]
> Is there a solution for this? why is closed? I continue having issues with **System.Text.Json.Serialization** as it's the recommendation since net core 3.1 and we are on days for net7 releases.
> 
> this works:
> 
> ```
> [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
> public Status Status { get; set; }
> ```
> 
> but this doesn't work and should:
> 
> ```
> [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
> public Status Status { get; set; }
> ```
> 
> using Microsoft.Azure.Cosmos 3.31.0 net 6.0.402

Same case with us at the moment. NewtonSoft.Json works but not System.Test.Json

**Comment by kodbulten** [comment]
> Is there a solution for this? why is closed? I continue having issues with **System.Text.Json.Serialization** as it's the recommendation since net core 3.1 and we are on days for net7 releases.
> 
> this works:
> 
> ```
> [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
> public Status Status { get; set; }
> ```
> 
> but this doesn't work and should:
> 
> ```
> [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
> public Status Status { get; set; }
> ```
> 
> using Microsoft.Azure.Cosmos 3.31.0 net 6.0.402

Same here. Only reason we use Newtonsoft in a current project was to get this working, so felt a bit unnecessary. Would be great if this could work with System.Text.Json as well.

**Comment by bartelink** [comment]
There's STJ wiring almost complete. And everyone wants it (the last mile is currently paused due to a short term higher priority override that is affecting a number of ongoing work items) - start here https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4540

**Comment by mbaird628** [comment]
Microsoft.Azure.Functions.Worker.Extensions.CosmosDB 4.10.0 and NewtonSoft.Json 13.0.3 throws and exception when using [JsonConverter(typeof(StringEnumConverter))]> 

If NewtonSoft.Json is the library that is being used why does the exception reference System.Text.Json.

Function 'CosmosDBTrigger', Invocation id '177fb752-08ba-4cd9-ad2c-1facecd8cbe7': An exception was thrown by the invocation.
[2024-08-13T20:24:40.870Z] Result: Function 'CosmosDBTrigger', Invocation id '177fb752-08ba-4cd9-ad2c-1facecd8cbe7': An exception was thrown by the invocation.
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'CosmosDBTrigger': Cannot convert input parameter 'sensors' to type 'System.Collections.Generic.IReadOnlyList`1[[Cumulus.IoT.Device.SAFE.VirtualDevices.Models.LoonSensor, Cumulus.IoT.Device.SAFE.VirtualDevices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON value could not be converted to Cumulus.IoT.SAFE.Beacons.Enums.SensorType. Path: $[0].sensorType | LineNumber: 0 | BytePositionInLine: 191.
[2024-08-13T20:24:40.871Z]    at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
[2024-08-13T20:24:40.871Z]    at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
[2024-08-13T20:24:40.872Z]    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
[2024-08-13T20:24:40.872Z]    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
[2024-08-13T20:24:40.873Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
[2024-08-13T20:24:40.874Z]    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
[2024-08-13T20:24:40.874Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
[2024-08-13T20:24:40.875Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
[2024-08-13T20:24:40.877Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
[2024-08-13T20:24:40.877Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
[2024-08-13T20:24:40.878Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
[2024-08-13T20:24:40.878Z]    at Microsoft.Azure.Functions.Worker.Converters.JsonPocoConverter.GetConversionResultFromDeserialization(Byte[] bytes, Type type) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\JsonPocoConverter.cs:line 66
[2024-08-13T20:24:40.879Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 94
[2024-08-13T20:24:40.880Z]    at Cumulus.IoT.Device.SAFE.VirtualDevices.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\bairdma\source\repos\Cumulus.IoT.Device.SAFE.VirtualDevices\Cumulus.IoT.Device.SAFE.VirtualDevices\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 32
[2024-08-13T20:24:40.880Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-08-13T20:24:40.881Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 38
[2024-08-13T20:24:40.881Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 94
[2024-08-13T20:24:40.882Z]    at Cumulus.IoT.Device.SAFE.VirtualDevices.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\bairdma\source\repos\Cumulus.IoT.Device.SAFE.VirtualDevices\Cumulus.IoT.Device.SAFE.VirtualDevices\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 32
[2024-08-13T20:24:40.883Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-08-13T20:24:40.883Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 38
[2024-08-13T20:24:40.887Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89.
[2024-08-13T20:24:40.908Z] Executed 'Functions.CosmosDBTrigger' (Failed, Id=177fb752-08ba-4cd9-ad2c-1facecd8cbe7, Duration=140ms)
[2024-08-13T20:24:40.909Z] System.Private.CoreLib: Exception while executing function: Functions.CosmosDBTrigger. System.Private.CoreLib: Result: Failure
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'CosmosDBTrigger': Cannot convert input parameter 'sensors' to type 'System.Collections.Generic.IReadOnlyList`1[[Cumulus.IoT.Device.SAFE.VirtualDevices.Models.LoonSensor, Cumulus.IoT.Device.SAFE.VirtualDevices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON value could not be converted to Cumulus.IoT.SAFE.Beacons.Enums.SensorType. Path: $[0].sensorType | LineNumber: 0 | BytePositionInLine: 191.
[2024-08-13T20:24:40.911Z]    at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
[2024-08-13T20:24:40.911Z]    at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
[2024-08-13T20:24:40.912Z]    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
[2024-08-13T20:24:40.913Z]    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
[2024-08-13T20:24:40.913Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
[2024-08-13T20:24:40.914Z]    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
[2024-08-13T20:24:40.914Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
[2024-08-13T20:24:40.915Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
[2024-08-13T20:24:40.916Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
[2024-08-13T20:24:40.917Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
[2024-08-13T20:24:40.917Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
[2024-08-13T20:24:40.918Z]    at Microsoft.Azure.Functions.Worker.Converters.JsonPocoConverter.GetConversionResultFromDeserialization(Byte[] bytes, Type type) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\JsonPocoConverter.cs:line 66
[2024-08-13T20:24:40.918Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 94
[2024-08-13T20:24:40.918Z]    at Cumulus.IoT.Device.SAFE.VirtualDevices.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\bairdma\source\repos\Cumulus.IoT.Device.SAFE.VirtualDevices\Cumulus.IoT.Device.SAFE.VirtualDevices\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 32
[2024-08-13T20:24:40.919Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-08-13T20:24:40.919Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 38
[2024-08-13T20:24:40.920Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
[2024-08-13T20:24:40.920Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 94
[2024-08-13T20:24:40.921Z]    at Cumulus.IoT.Device.SAFE.VirtualDevices.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\bairdma\source\repos\Cumulus.IoT.Device.SAFE.VirtualDevices\Cumulus.IoT.Device.SAFE.VirtualDevices\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 32
[2024-08-13T20:24:40.922Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-08-13T20:24:40.922Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 38
[2024-08-13T20:24:40.923Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
[2024-08-13T20:24:40.923Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.
