### ISSUE TITLE
NullReferenceExceptions during serialization on Reads/Queries under load

### ISSUE THREAD

**Issue by nathansoz** [Azure/azure-cosmos-dotnet-v3#1079]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
After switching from v2 to v3 of the SDK, we observed sporadic NREs deep in Cosmos/Newtonsoft.Json call stacks. These exceptions did not occur in v2 and we didn't change anything about our data model that would have caused serialization issues. Additionally, subsequent and prior reads/queries to the same document (without modifications in between) would succeed.

The issue did not happen in our development environments and only manifested under load (perhaps 50+ RPS to our service and 100-150 RPS to cosmos, but that's just a SWAG).

Stack of a sample failing request is below:

```
   at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.Azure.Cosmos.CosmosJsonDotNetSerializer.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosSqlQuerySpecJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.Azure.Cosmos.CosmosJsonDotNetSerializer.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.ExecuteItemQueryAsync[RequestOptionType](Uri resourceUri, ResourceType resourceType, OperationType operationType, RequestOptionType requestOptions, SqlQuerySpec sqlQuerySpec, String continuationToken, PartitionKeyRangeIdentity partitionKeyRange, Boolean isContinuationExpected, Int32 pageSize, SchedulingStopwatch schedulingStopwatch, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.BufferMoreDocumentsAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.BufferMoreIfEmptyAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.TryMoveNextPageAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.MoveNextAsyncImplementationAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.MoveNextAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.TryMoveNextAsyncImplementationAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.ExecuteWithSplitProofingAsync(Func`2 function, Boolean functionNeedsBeReexecuted, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.MoveNextAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.CosmosCrossPartitionQueryExecutionContext.MoveNextHelperAsync(ItemProducerTree itemProducerTree, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosParallelItemQueryExecutionContext.InternalDrainAsync(Int32 maxElements, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosCrossPartitionQueryExecutionContext.DrainAsync(Int32 maxElements, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.ExecuteNextAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.ExecuteNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.ReadNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.ReadNextAsync(CancellationToken cancellationToken)
<SNIPPED FOR PRIVACY>
   at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.Azure.Cosmos.CosmosJsonDotNetSerializer.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosSqlQuerySpecJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.Azure.Cosmos.CosmosJsonDotNetSerializer.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.ExecuteItemQueryAsync[RequestOptionType](Uri resourceUri, ResourceType resourceType, OperationType operationType, RequestOptionType requestOptions, SqlQuerySpec sqlQuerySpec, String continuationToken, PartitionKeyRangeIdentity partitionKeyRange, Boolean isContinuationExpected, Int32 pageSize, SchedulingStopwatch schedulingStopwatch, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.BufferMoreDocumentsAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.BufferMoreIfEmptyAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.TryMoveNextPageAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.MoveNextAsyncImplementationAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.MoveNextAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.TryMoveNextAsyncImplementationAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.ExecuteWithSplitProofingAsync(Func`2 function, Boolean functionNeedsBeReexecuted, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.MoveNextAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.CosmosCrossPartitionQueryExecutionContext.MoveNextHelperAsync(ItemProducerTree itemProducerTree, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosParallelItemQueryExecutionContext.InternalDrainAsync(Int32 maxElements, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosCrossPartitionQueryExecutionContext.DrainAsync(Int32 maxElements, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.ExecuteNextAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.ExecuteNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.ReadNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.ReadNextAsync(CancellationToken cancellationToken)
<SNIPPED FOR PRIVACY>
```

We construct our client like this.
```
                    CosmosClientBuilder builder = new CosmosClientBuilder(GetConnectionString(geo));
 
                    builder = string.Equals(_options.ConnectionMode, "direct", StringComparison.OrdinalIgnoreCase) ?
                        builder.WithConnectionModeDirect() :
                        builder.WithConnectionModeGateway();
 
                    builder
                        .WithConsistencyLevel(ConsistencyLevel.Session)
                        .WithThrottlingRetryOptions(TimeSpan.FromSeconds(30), maxRetryAttemptsOnThrottledRequests: 10)
                        .WithSerializerOptions(new CosmosSerializationOptions { PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase, Indented = false, IgnoreNullValues = false });
 
                    if (_options.PreferredLocations.TryGetValue(affinity, out string[] locations) &&
                        locations.Length > 0)
                    {
                        // TODO: I don't think we can set a list anymore
                        builder.WithApplicationRegion(locations.First());
                    }
 
                    CosmosClient client = builder.Build();

```

**To Reproduce**
We were finding that any query/read under heavy load in ASP.net core was liable to cause the issue. The issue is not deterministic, so a query/read may succeed many times and then fail. At this point we are unsure if x86/x64 plays any role (this was mentioned in other issues).

**Expected behavior**
No NullReferenceExceptions :)

**Actual behavior**
NullReferenceExceptions 

**Environment summary**
SDK Version: 3.5.0
OS Version (e.g. Windows, Linux, MacOSX): Windows, ASP.net Core (Azure App Service)

**Comment by nathansoz** [comment]
FWIW we also found that creating a custom serializer that does not share a JsonSerializer instance unblocked us. This is the code we used:

```
    public class CustomCosmosSerializer : CosmosSerializer
    {
        public override T FromStream<T>(Stream stream)
        {
            if (typeof(Stream).IsAssignableFrom(typeof(T)))
            {
                return (T)(object)stream;
            }

            using (stream)
            {
                using (StreamReader streamReader = new StreamReader(stream))
                {
                    using (JsonTextReader jsonTextReader = new JsonTextReader(streamReader))
                    {
                        if (JsonConvert.DefaultSettings == null)
                        {
                            return JsonSerializer.Create().Deserialize<T>(jsonTextReader);
                        }
                        else
                        {
                            return JsonSerializer.Create(JsonConvert.DefaultSettings()).Deserialize<T>(jsonTextReader);
                        }
                    }
                }
            }
        }

        public override Stream ToStream<T>(T input)
        {
            MemoryStream streamPayload = new MemoryStream();
            using (StreamWriter streamWriter = new StreamWriter(streamPayload, Encoding.Default, bufferSize: 1024, leaveOpen: true))
            {
                using (JsonWriter writer = new JsonTextWriter(streamWriter))
                {
                    writer.Formatting = Formatting.None;

                    if (JsonConvert.DefaultSettings == null)
                    {
                        JsonSerializer.Create().Serialize(writer, input);
                    }
                    else
                    {
                        JsonSerializer.Create(JsonConvert.DefaultSettings()).Serialize(writer, input);
                    }

                    writer.Flush();
                    streamWriter.Flush();
                }
            }

            streamPayload.Position = 0;
            return streamPayload;
        }
    }

**Comment by ealsur** [comment]
Do your data models use JsonConverter? Did the Newtonsoft.Json dependency change versions as part of the migration process?

**Comment by asgoe** [comment]
Hi @kirankumarkolli/@j82w ,

We can into this issue recently in our production environment (see error stack below).  The Sql Query Engine on-call engineer  (@khdang) advised to re-open this issue, since the call stack is similar. Can someone take a look and advice? This impacted our customers so we have to rollback the V3 SDK code. This is blocking rolling out the V3 code. 

SDK version: 3.25.0 version of Microsoft.Azure.Cosmos

Here's the ICM that was created for this: [Incident 308754558](https://portal.microsofticm.com/imp/v3/incidents/details/308754558/home) : Null stream causing ArgumentNullException while running a Sql query

Error Stack:
`System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at Microsoft.Intune.CloudStorage.Common.Serializer.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosSqlQuerySpecJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.Azure.Cosmos.CosmosJsonDotNetSerializer.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.<ExecuteItemQueryAsync>d__10.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.NetworkAttachedDocumentContainer.<MonadicQueryAsync>d__16.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CrossPartition.OrderBy.OrderByQueryPartitionRangePageAsyncEnumerator.InnerEnumerator.<GetNextPageAsync>d__15.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.PartitionRangePageAsyncEnumerator`2.<MoveNextAsync>d__16.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.BufferedPartitionRangePageAsyncEnumerator`2.<PrefetchAsync>d__5.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.ParallelPrefetch.<>c__DisplayClass0_1.<<PrefetchInParallelAsync>b__0>d.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.ParallelPrefetch.<PrefetchInParallelAsync>d__0.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.ParallelPrefetch.<PrefetchInParallelAsync>d__0.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CrossPartition.OrderBy.OrderByCrossPartitionQueryPipelineStage.<MoveNextAsync_InitializeAsync>d__23.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.SkipEmptyPageQueryPipelineStage.<MoveNextAsync>d__13.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.LazyQueryPipelineStage.<MoveNextAsync>d__8.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.NameCacheStaleRetryQueryPipelineStage.<MoveNextAsync>d__10.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CatchAllQueryPipelineStage.<MoveNextAsync>d__1.MoveNext()
   at Microsoft.Azure.Cosmos.Query.QueryIterator.<ReadNextAsync>d__14.MoveNext()
   at Microsoft.Azure.Cosmos.ClientContextCore.<RunWithDiagnosticsHelperAsync>d__39`1.MoveNext()
   at Microsoft.Azure.Cosmos.ClientContextCore.<OperationHelperWithRootTraceAsync>d__30`1.MoveNext()
   at Microsoft.Intune.CloudStorage.Common.CosmosDbFeedIterator.<>c__DisplayClass19_0.<<ReadNextAsync>b__0>d.MoveNext()
   at Microsoft.Intune.CloudStorage.Common.ReconnectExecutor.<ExecuteAsync>d__2.MoveNext()
   at Microsoft.Intune.CloudStorage.Common.CosmosDbClient.<>c__DisplayClass49_0.<<ExecuteAsync>b__0>d.MoveNext()
   at Microsoft.Intune.CloudStorage.Common.Retry.ObservableThrottlingRetryExecutor.<OnExecutingAsync>d__3`1.MoveNext()
   at Microsoft.Intune.CloudStorage.Common.CosmosDbClient.<ExecuteAsync>d__49.MoveNext()`

**Comment by j82w** [comment]
@asgoe as the ICM incident explained this is an issue with the custom serializer "Microsoft.Intune.CloudStorage.Common.Serializer.ToStream[T](T input)" which you can see in the call stack. The custom serializer needs to be able to handle null values instead of throwing a null ref argument.
