### ISSUE TITLE
Recieving BadImageFormatException: Bad IL format when loading plugin

### ISSUE THREAD

**Issue by ConnorShore** [Azure/azure-cosmos-dotnet-v3#1113]
**Describe the bug**
We are currently developing a microservice architecture, and each service will have a database storage plugin so we can support different databases.  We are using .NET core 3.1.  

In other services, we have plugins for Azure Table Storage with the Microsoft.Azure.Cosmos.Table nuget with no issues during plugin loading.  However, with this new service, we are making a plugin to use CosmosDB for document type storage.  When we load the plugin we get a "BadImageFormatException: Bad IL format" from "System.Runtime.Loader.AssemblyLoadContext.LoadFromPath" which is fed the path of the plugin dll.  

I've read that the issue could come from an architecture mismatch, however i tried targeting the plugin and plugin-receiver both at x86, x64 and AnyCPU and still get the same issue.  Everything is setup identical to the other services that use the Azure Tables plugins and the only difference is the CosmosDB nuget package.  When I remove the Microsoft.Azure.Cosmos package then I can load the plugin without the exception (the plugin currently has no functionality, just a reference to that cosmos package) so we know the issue stems from this package.

Also we are using the latest version of this package at time of this post (v3.5.1)

**To Reproduce**
We have a somewhat big system already in place and can't provide code right now.  But the plugin system is based around the Microsoft Extensibility Framework for plugins.  So essentially creating a IPlugin type, and then implementing that plugin and having a reference to this nuget package in the plugin should probably cause the issue when trying to load the plugin using MEF.

**Expected behavior**
No errors when loading the plugin

**Actual behavior**
Receiving Bad IL format exception when loading the plugin

**Environment summary**
SDK Version: .NET Core 3.1
Windows 10 x64
Visual Studio 2019 Version 4.8.03752

**Comment by ealsur** [comment]
Is your plugin referencing Microsoft.Azure.Cosmos.Table  AND Microsoft.Azure.Cosmos at the same time? Or are they different plugins?

Can you post the entire Exception with Stack Trace?

**Comment by ConnorShore** [comment]
This plugin is only referencing Microsoft.Azure.Cosmos. Here is the stack trace:

System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PluginManager.PluginProvider.Compose()
   at PluginManager.PluginProvider..ctor(String pluginDllPath)
   at BatchManager.Startup.<ConfigureServices>b__4_4(IServiceProvider provider) in D:\WindwardNEXT\BatchManager\BatchManager\Startup.cs:line 51
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by ealsur** [comment]
Seems to be coming from DI, how are you registering the instances in the DI container? Is there any project references or is it just one single project?

**Comment by ealsur** [comment]
Is the plugin project using the same architecture as the project loading it? Are both x64 or both x86?

**Comment by ConnorShore** [comment]
Yes each of the projects are the same.  I tried setting each to x64, x86 and AnyCPU to see if a specific config would work with the package but had no luck.  Here is where we register the instances:

`
        private void Compose()
        {
            var assemblies = new List<Assembly>() { typeof(IPlugin).GetTypeInfo().Assembly };

            var files = Directory.GetFiles(_pluginDirectoryPath, "*.dll", SearchOption.TopDirectoryOnly).Select(AssemblyLoadContext.Default.LoadFromAssemblyPath).ToList();

            foreach (Assembly a in files)
            {
                foreach (Type type in a.GetTypes())
                {
                    if (typeof(IPlugin).IsAssignableFrom(type))
                    {
                        assemblies.Add(a);
                    }
                }
            }

            List<Assembly> pluginAssemblies = new List<Assembly>();
            foreach (Assembly a in files)
            {
                foreach (Type type in a.GetTypes())
                {
                    if (typeof(IPlugin).IsAssignableFrom(type))
                    {
                        assemblies.Add(a);
                    }
                }
            }

            assemblies.AddRange(pluginAssemblies);

            var configuration = new ContainerConfiguration()
                .WithAssemblies(assemblies);

            using (var container = configuration.CreateContainer())
            {
                Services = container.GetExports<IPlugin>();
            }
        }
`

The plugin being loaded is 3 project.  One is for the DBQuery interface, one is for the DBCommand interface (both of these are class libraries that produce a dll).  There is one more project in that solution that is a Utilities project that contains data contracts used by each project as well as some common functions.  This project is referenced via project reference in both DBQuery and DBCommand projects.

This is the same project and reference format that has been used in 2 of our other service plugins (each of which use Azure Tables opposed to CosmosDB) with no issues.

**Comment by ealsur** [comment]
From the code and stack trace, it looks like the exception is being thrown on `Compose` when `LoadFromAssemblyPath` is called through Linq Select. You are loading ALL dlls in the folder and one of them appears to have a Bad Image (not built for the current architecture).

One thing you could do is, instead of using Linq Select, do a for loop on the files and load them one by one, add a try/catch block during that call to `LoadFromAssemblyPath` for each file. On the catch, log (or put a breakpoint if you are debugging) which file is the one that is causing the issue. That will show if it's one of the SDK dlls or something else.

**Comment by ConnorShore** [comment]
Ok excellent! Thanks for getting back quick! I'll give that a shot and try to isolate that specific dll.  I'll reply back with my findings.

**Comment by ConnorShore** [comment]
Ok so I went ahead and did what you said and in the catch statement, I had it print out the exception message as well as which file caused the exception and here was the console output from that:

EXCEPTION:
Bad IL format.
File: D:\WindwardNEXT\BatchManager\publish\Plugins\AzureCosmosDB\Cosmos.CRTCompat.dll


EXCEPTION:
Bad IL format.
File: D:\WindwardNEXT\BatchManager\publish\Plugins\AzureCosmosDB\Microsoft.Azure.Cosmos.ServiceInterop.dll

**Comment by ealsur** [comment]
@ausfeldt Do you have any clues here? The `ServiceInterop.dll` is a native DLL, but I am not sure about `Cosmos.CRTCompat.dll`.

I don't believe these need to be loaded, the SDK does a PInvoke on the `ServiceInterop.dll` in case it's needed.

**Comment by ConnorShore** [comment]
If it helps at all, here are the commands used to produce the dll's that are referenced:
![image](https://user-images.githubusercontent.com/12499542/71270520-08f55980-230f-11ea-9d22-87d8a07b864c.png)

**Comment by ealsur** [comment]
Is there any way you can filter out those 2 DLLs, and see if the plugin works?

I know one of them does not need to be loaded, but I am not familiar with the other one.

**Comment by ConnorShore** [comment]
If i remove both those DLLs then everything works fine.  The only CosmosDB functionality I had was creating a client, database and container.  When those DLLs were removed the client, database and container were created successfully.

**Comment by ealsur** [comment]
I know the ServiceInterop DLL is PInvoked, so there is no need to load it. For the second one `Cosmos.CRTCompat.dll` I am not familiar with.

**Comment by ConnorShore** [comment]
Its an ok workaround for now but as we get deeper into development and begin to automate more, we can't be going in and deleting specific dlls everytime we build.  Right now I'll add a target to the build script that will just remove those specific dlls, but as we get to production, this isn't something I want to be doing.  Do you believe there will be a fix for this going forward?

**Comment by ealsur** [comment]
Why would you delete the dlls? Leaving `Cosmos.CTRCompat.dll` aside, the `ServiceInterop.dll` should be physically present, just not loaded through `LoadFromAssemblyPath`. Your output folder will contain them, but they are not required to be loaded as they do not expose any of the types used on runtime.

**Comment by ausfeldt** [comment]
> @ausfeldt Do you have any clues here? The ServiceInterop.dll is a native DLL, but I am not sure about Cosmos.CRTCompat.dll.
> I don't believe these need to be loaded, the SDK does a PInvoke on the ServiceInterop.dll in case it's needed.

Correct, Cosmos.CRTCompat.dll is needed to be along side ServiceInterop.dll but is not PInvoked. Only ServiceInterop is PInvoked. That dll is need to deal with double precision differences.

**Comment by ealsur** [comment]
Thanks @ausfeldt ! So it's enough for both to be present in the folder, correct?

**Comment by ealsur** [comment]
@ConnorShore One way to dynamically apply the filter on the Plugin is to extend IPlugin to have a `bool ShouldLoad (string dllName)` that would always return true on all plugins but on Cosmos DB would return false for these 2 DLLs. You can call this method as part of the Compose process? That way, you don't need to delete any DLLs and each Plugin defines its own exclusion list if needed.

**Comment by ConnorShore** [comment]
Ok ya that sounds good! Thanks for the help!

**Comment by ausfeldt** [comment]
> Thanks @ausfeldt ! So it's enough for both to be present in the folder, correct?

Both ServiceInterop.ll, Cosmos.CRTCompact.dll and the SDK's DLL all need to beside each other.

**Comment by ealsur** [comment]
Closing as a course of action has been defined. Please reopen if you run into any other issues.
