### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by anchowda** [Azure/azure-cosmos-dotnet-v3#1157]
**Describe the bug**
I am getting index was outside the bounds of the array error when try to use predicate in GetItemLinqQueryable method.  Working fine if i remove predicate. Any clue how to identify what's wrong in below method and how to resolve this issue? or any known issue?

**To Reproduce**
```
var queryable = this.container.GetItemLinqQueryable<T>(requestOptions: this.feedOptions, continuationToken: nextPageId).Where(t => t.IsError == true);//.OrderByDescending(d => d.Timestamp);
               //QueryDefinition queryDefinition = queryable.ToQueryDefinition();
                //FeedIterator<T> feedIterator = this.container.GetItemQueryIterator<T>(queryDefinition: queryDefinition, continuationToken: nextPageId, requestOptions: this.feedOptions);
                FeedIterator<T> feedIterator = queryable.ToFeedIterator();

                while (feedIterator.HasMoreResults)
                {
                    FeedResponse<T> currentResultSet = await feedIterator.ReadNextAsync();
                    foreach (T document in currentResultSet)
                    {
                        resultCollection.Items.Add(document);
                    }

                    resultCollection.NextPageId = currentResultSet.ContinuationToken;
                }
```

**Expected behavior**
When i get QueryDefinition for the same queryable object, The query is working fine in IDE. It  should iterate documents with ReadNextAsync method as well.

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
Az Function ~3
Cosmos DB SDK 3+

**Comment by j82w** [comment]
@anchowda  are you using the latest 3.5.1 SDK?

@bchong95 any suggestions?

**Comment by anchowda** [comment]
@j82w , Thanks for your quick response.

Yes, I am using 3.5.1 SDK. Here is the exception message.

```
Response status code does not indicate success: 500 Substatus: 0 Reason: (System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.Create(ReadOnlyMemory`1 buffer, JsonStringDictionary jsonStringDictionary, Boolean skipValidation)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.CreateFromBuffer(ReadOnlyMemory`1 buffer)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.TryParse(String serializedCosmosElement, CosmosElement& cosmosElement)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.TryParse[TCosmosElement](String serializedCosmosElement, TCosmosElement& cosmosElement)
   at Microsoft.Azure.Cosmos.Query.Core.ContinuationTokens.PipelineContinuationToken.TryParse(String rawContinuationToken, PipelineContinuationToken& pipelineContinuationToken)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CosmosQueryExecutionContextFactory.TryCreateCoreContextAsync(CosmosQueryContext cosmosQueryContext, InputParameters inputParameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.AsyncLazy`1.GetValueAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.LazyCosmosQueryExecutionContext.ExecuteNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CosmosQueryExecutionContextWithNameCacheStaleRetry.ExecuteNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CatchAllCosmosQueryExecutionContext.ExecuteNextAsync(CancellationToken cancellationToken)).

**StackTrace:**
   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.CreateQueryFeedResponseHelper[T](ResponseMessage cosmosResponseMessage, Boolean usePropertySerializer)
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.CreateQueryFeedResponse[T](ResponseMessage cosmosResponseMessage)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.<ReadNextAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Mms.Apps.Datav3.Repository`1.<FindBy>d__12.MoveNext() in C:\Users\anchowda\source\repos\MMS\MMS.Apps\MMS.Apps.Datav3\Repository.cs:line 213
```

**Comment by bchong95** [comment]
Please provide the continuation token for that query

**Comment by anchowda** [comment]
Thanks @bchong95 . This issue is now resolved. I was passing empty string for continuation token in initial request. After setting null instead of empty string for continuation token, worked.

**Comment by bchong95** [comment]
I will fix the code, so that you get a better error message. You should ideally get 400 / Bad Request with malformed continuation token error message. Thanks

**Comment by Artemiy-Zarubin** [comment]
Unfortunately, this is an actual problem. http code 500.

```
{
    "error": {
        "code": "unknown",
        "message": "Unhandled exception: Index was outside the bounds of the array.",
        "details": "Unhandled exception: Index was outside the bounds of the array."
    }
}
```
