### ISSUE TITLE
[vNext] Paginated query throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by Mortana89** [Azure/azure-cosmos-dotnet-v3#1272]
Using preview SDK v4, we have the following code:

```
var queryIterator = container.GetItemQueryIterator<TResponse>(queryDefinition, continuationToken, new QueryRequestOptions() { MaxItemCount = (string.IsNullOrEmpty(continuationToken) ? 300 : 100) });
                string newContinuationToken = null;

                await foreach (var page in queryIterator.AsPages())
                {
                    response.AddRange(page.Values);
                    newContinuationToken = page.ContinuationToken;
                }
```

When executing with a query that should go cross-partition (we have a STARTSWITH(c.PartitionKeyField, PartitionKeyValue) clause in our query), we get the following error:
Index was outside the bounds of the array.
`  at System.ThrowHelper.ThrowIndexOutOfRangeException()
   at System.ReadOnlySpan`1.get_Item(Int32 index)
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.Create(ReadOnlyMemory`1 buffer, JsonStringDictionary jsonStringDictionary, Boolean skipValidation)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.CreateFromBuffer(ReadOnlyMemory`1 buffer)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.TryParse(String serializedCosmosElement, CosmosElement& cosmosElement)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.TryParse[TCosmosElement](String serializedCosmosElement, TCosmosElement& cosmosElement)
   at Microsoft.Azure.Cosmos.Query.Core.ContinuationTokens.PipelineContinuationToken.TryParse(String rawContinuationToken, PipelineContinuationToken& pipelineContinuationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.<TryCreateItemQueryExecutionContextAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.<ExecuteNextAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Azure.Cosmos.Query.QueryIterator.<ReadNextAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Azure.Cosmos.PageIteratorCore`1.<GetPageAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Azure.Cosmos.PageResponseEnumerator.FuncAsyncPageable`1.<AsPages>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Azure.Cosmos.PageResponseEnumerator.FuncAsyncPageable`1.<AsPages>d__2.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()`

Are we taking an incorrect approach in doing paginated queries perhaps? It's pretty new so we're searching for the best approach!

**Comment by Mortana89** [comment]
Just testing, it seems as if when the continuation token is an empty string, this exception occurs.
I've added a string.Empty check in our base class, making sure that, when the continuation token is just an empty string, the continuation token is changed to NULL. This seems like something to check in the SDK though?

**Comment by ealsur** [comment]
What is the scenario where you need the Continuation Token if you are iterating over all the results anyway?

If you are consuming all results might as well just do:

```
await foreach (TResponse item in queryIterator)
                {
                    response.Add(item);
                }
```

**Comment by Mortana89** [comment]
If we're specifying maxitemcount, I guess we could still have multiple pages returned from the server?
Basically we have two scenario's, API calls for listpages, where the first API call returns 300 items and a continuation token, and the second call (and more) use prev continuation token and fetch more (we don't use Page 1,2,3... Stuff but have virtual list). Then in our backend we have the processes calling the same pagination logic, either with a flag to skip pagination completely, or with continuation tokens.

I might be misunderstanding the .AsPages stuff though! 😃

**Comment by Mortana89** [comment]
Hi @ealsur 

I noticed I'm taking the wrong approach here, I expected that the following code would enumerate over the results until the maxitemcount was reached;
```
await foreach (var page in queryIterator.AsPages())
                {
                    response.AddRange(page.Values);
                    newContinuationToken = page.ContinuationToken;
                }
```

but instead this fetches all records that match the query. 
How can I make sure I honor the maxitemcount, and get a continuationtoken that I can pass to the caller to get the next page (as and when required)?

**Comment by ealsur** [comment]
MaxItemCount defines the maximum results in a given page, not the max in a query. For that you can use TOP to return only the first X results in a query.

**Comment by Mortana89** [comment]
> MaxItemCount defines the maximum results in a given page, not the max in a query. For that you can use TOP to return only the first X results in a query.

Yes, I understand. But what I meant is that I don't want to send all the query results at once to thé frontend, hence we send over the continuation token. So what would be the code for that? Do we still need the .AsPages?

**Comment by ealsur** [comment]
You can certainly use AsPages if you need to return the continuation token, in that case, the count for the amount of items you want to return to the caller is something you need to do. The problem there is if let's say you want to return 10 items and page 1 returned 7 and page 2 returned 5, you have 12 there. 

The continuation token is for after the second page, so you'd have to return 12 results + continuation.

**Comment by Mortana89** [comment]
Aha okey, and do I understand that the MaxItemCount has only effect on a single page?
So if I set 350 as maxitemcount, and a page only contains 100, it will do 4 calls and I will have 400 records? In the other way, if a page COULD return more than 400 items at once, it will honor the maxitemcount and only return 350, right?

I don't mind that the amount of records can be varying, the caller should not have a dependency on that, cause he should use the TOP clause if that's important, indeed!
