### ISSUE TITLE
Can't pass AppContainerCheck for UWP certification

### ISSUE THREAD

**Issue by AlfredBauer** [Azure/azure-cosmos-dotnet-v3#132]
**Describe the bug**
Firstly, after starting create a package for upload to store I see warnings in VS.
[Warnings in VS](https://imgur.com/77xolmc)
Then I can't pass the certification whis this error:
[AppContainerCheck Error](https://imgur.com/lb7b1Ib)

**Expected behavior**
Passed certification in MS Store.

**Actual behavior**
Error for AppContainerCheck test.

**Environment summary**
Microsoft.Azure.Cosmos: 3.0.0.9
SDK Version: 17763
OS Version: Windows 10 17763.437

I was start program (Release) on my PC and immediately catch an exception on creating CosmosClient:
[Exception](https://imgur.com/s7avBAv)
**StackTrace:**
   at __Interop.ntdll.RtlGetVersion(RTL_OSVERSIONINFOEX& lpVersionInformation)
   at Microsoft.Azure.Cosmos.Internal.NativeMethods.Windows.RtlGetVersion()
   at Microsoft.Azure.Cosmos.Internal.PlatformApis.GetOSVersion()
   at Microsoft.Azure.Cosmos.CustomTypeExtensions.GenerateBaseUserAgentString()
   at Microsoft.Azure.Cosmos.Internal.UserAgentContainer..cctor()
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext* pContext) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\ClassConstructorRunner.cs:line 92

P.S. In Debug all works fine

**Comment by dpaulino** [comment]
Any updates regarding this?

**Comment by j82w** [comment]
@dpaulino as a workaround can you try removing the `ServiceInterop.dll` from the application? The service interop dll parses query locally to avoid additional latency of going to Cosmos DB to get the information. There is logic in the SDK if the `ServiceInterop.dll` fallback to the gateway model.

**Comment by j82w** [comment]
Closing this since there is no updates. The ideal model would have a service that is processing the Cosmos DB requests and the application connects to that service.
