### ISSUE TITLE
Queries using CONTAINS and STARTSWITH throw an error when using the ignore case parameter

### ISSUE THREAD

**Issue by george-ayris** [Azure/azure-cosmos-dotnet-v3#1615]
**Describe the bug**
When trying to use the boolean parameter to ignore case in a CONTAINS or STARTSWITH clause (as documented [here](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-contains) and [here](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-startswith)) in a query, e.g. `SELECT * FROM c WHERE CONTAINS(c.platformId, '1', true)`, the SDK throws the following error:
```
Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"errors":[{"severity":"Error","location":{"start":35,"end":68},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."}]}
```
However, the same query works when running in the Cosmos Data Explorer (explorer version: 377ee75414c1840d12174ff8674a6a3635de92a6).

**To Reproduce**
```
var query = new QueryDefinition("SELECT * FROM c WHERE CONTAINS(c.platformId, '1', true)");
var options = new QueryRequestOptions
{
  MaxConcurrency = -1,
  MaxItemCount = 25
};
var queryIterator = db.GetItemQueryIterator<T>(query, null, options);
var response = await queryIterator.ReadNextAsync();
// await causes the exception to be thrown
```

**Expected behavior**
An exception not to be thrown and the clause to work.

**Actual behavior**
An exception is thrown (with stack trace below).

**Environment summary**
SDK Version: 3.9.1
OS Version: Windows 10, .NET Core 2.1

**Additional context**
Complete stack trace:
```
System.Private.CoreLib: Exception while executing function: HttpPostGetDocuments. Microsoft.Azure.Cosmos.Client: Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"errors":[{"severity":"Error","location":{"start":21,"end":21},"code":"SC1002","message":"Syntax error, unexpected end-of-file."}]} ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x800A0B00
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPartitionProvider.TryGetPartitionedQueryExecutionInfoInternal(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey)
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPartitionProvider.TryGetPartitionedQueryExecutionInfo(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.TryGetPartitionedQueryExecutionInfoAsync(SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.TryGetPartitionedQueryExecutionInfoAsync(SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPlanHandler.TryGetQueryInfoAsync(SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPlanHandler.TryGetQueryInfoAsync(SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPlanHandler.TryGetQueryPlanAsync(SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, QueryFeatures supportedQueryFeatures, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPlanHandler.TryGetQueryPlanAsync(SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, QueryFeatures supportedQueryFeatures, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPlanRetriever.GetQueryPlanWithServiceInteropAsync(CosmosQueryClient queryClient, SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPlanRetriever.GetQueryPlanWithServiceInteropAsync(CosmosQueryClient queryClient, SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CosmosQueryExecutionContextFactory.TryCreateCoreContextAsync(CosmosQueryContext cosmosQueryContext, InputParameters inputParameters, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CosmosQueryExecutionContextFactory.TryCreateCoreContextAsync(CosmosQueryContext cosmosQueryContext, InputParameters inputParameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CosmosQueryExecutionContextFactory.<>c__DisplayClass2_0.<Create>b__1(CancellationToken innerCancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.AsyncLazy`1.GetValueAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.Query.Core.AsyncLazy`1.GetValueAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.LazyCosmosQueryExecutionContext.ExecuteNextAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.LazyCosmosQueryExecutionContext.ExecuteNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CosmosQueryExecutionContextWithNameCacheStaleRetry.ExecuteNextAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CosmosQueryExecutionContextWithNameCacheStaleRetry.ExecuteNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CatchAllCosmosQueryExecutionContext.ExecuteNextAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CatchAllCosmosQueryExecutionContext.ExecuteNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.ReadNextAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.ReadNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.FeedIteratorInlineCore.ReadNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.ReadNextAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.ReadNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.FeedIteratorInlineCore`1.ReadNextAsync(CancellationToken cancellationToken)
   at ...calling code...```

**Comment by ealsur** [comment]
@bchong95 Do you know what could be the issue? Data Explorer is certainly going through Gateway to execute the query.

**Comment by bchong95** [comment]
Case insensitive contains requires the lastest SDK with newest service interop.

**Comment by george-ayris** [comment]
I'm using version 3.9.1, which I believe is the latest stable version of the SDK. Is there a new version available?

**Comment by george-ayris** [comment]
Yeah production. Running the SDK (and data explorer) queries against a cosmos instance in West Europe.

**Comment by j82w** [comment]
@george-ayris we've located the issue and it is already fixed in the repo. We are working on doing a release with the fix which should hopefully be out by the end of the week.

**Comment by george-ayris** [comment]
Thank you very much

**Comment by j82w** [comment]
Related PR #1628

**Comment by j82w** [comment]
@george-ayris [3.10.0](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.10.0) is officially released with the fix.

**Comment by kweebtronic** [comment]
Linq to SQL not implemented for this yet?
Just upgraded to latest, and it misinterprets the parameters

### 3.9.1
Expression
`(x => x.FromName.ToLower().Contains(nameLower))`

SQL
`CONTAINS(LOWER(root["fromName"]), "searchString")`

### 3.10.1
Expression
`(x => x.FromName.Contains(name, StringComparison.OrdinalIgnoreCase))`

SQL
`AND CONTAINS("searchString", 3)`

**Comment by j82w** [comment]
@kweebtronic can you create a new issue asking for linq support?

**Comment by hora7ce** [comment]
Hm.. the problem seems to still be present within the SDK 3.16

`Error: Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"errors":[{"severity":"Error","location":{"start":456,"end":494},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":498,"end":540},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":560,"end":601},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":605,"end":646},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":666,"end":704},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":708,"end":746},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":766,"end":801},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":805,"end":842},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."}]}
 ---> System.Runtime.InteropServices.COMException (0x800A0B00): 0x800A0B00`

**Comment by j82w** [comment]
@hora7ce please create a new github issue.
