### ISSUE TITLE
SDK hangs when server is unreachable

### ISSUE THREAD

**Issue by skurik** [Azure/azure-cosmos-dotnet-v3#1635]
**Describe the bug**
I am using v3.9.1 and testing this against a local emulator.

I wanted to test how our code behaves in face of network partitions. Therefore, I reproduced a situation where the client is successfully initialized but before executing a transactional batch, the server is shut down. The result is that `ExecuteAsync` hangs.

**To Reproduce**
```
async Task Main()
{
    var connectionString = "AccountEndpoint=https://localhost:8081/;AccountKey=<account key>";
    
    var clientBuilder = new CosmosClientBuilder(connectionString);
    var clientWithSerialization = clientBuilder.WithSerializerOptions(new CosmosSerializationOptions
    {
        PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
    });
    var containerProperties = new ContainerProperties
    {
        Id = "testcontainer",
        PartitionKeyPath = $"/partitionKey"
    };
    
    var client = clientWithSerialization.Build();
    var database = (await client.CreateDatabaseIfNotExistsAsync("test")).Database;
    var container = (await database.CreateContainerIfNotExistsAsync(containerProperties)).Container;
        
    var item = new Item
    {
        PartitionKey = "abc"
    };

    var batch = container.CreateTransactionalBatch(new PartitionKey(item.PartitionKey));
    batch.CreateItem(item);

    // Put a breakpoint here and before continuing, shut the server down
    var response = await batch.ExecuteAsync();
}
```

**Expected behavior**
* `ExecuteAsync` returns `TransactionalBatchResponse` where an error response status is indicated
* or an exception is thrown

**Actual behavior**
`ExecuteAsync` never finishes.

**Environment summary**
SDK Version: 3.9.1
OS Version: Windows

**Comment by j82w** [comment]
@skurik does this happen for a normal create or only batch? Trying to figure out if it is specific to batch.

@anujtoshniwal and @abhijitpai can you take a look?

**Comment by skurik** [comment]
@j82w I now tried, it also hangs at `CreateItemAsync`.

**Comment by j82w** [comment]
1. How long did you let it hang? It should time out after roughly a minute with an exception that contains more information.
2. Can you try resetting the emulator and make sure you are using the latest version of the emulator?

**Comment by skurik** [comment]
1. I let it run for about 6 minutes. I am running it in LINQPad if that helps.
2. I now downloaded and installed the latest version of the emulator, still the same behavior.

**Comment by j82w** [comment]
Can you try switch to gateway mode? I know this scenario works with dot net console application so it seems to be something specific with LINQPad.

```c#
var clientBuilder = new CosmosClientBuilder(connectionString).WithConnectionModeGateway();
    var clientWithSerialization = clientBuilder.WithSerializerOptions(new CosmosSerializationOptions
    {
        PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
    });
```

**Comment by ealsur** [comment]
Could this be something on LINQPad? Does this repro in a console application?

**Comment by skurik** [comment]
Using gateway mode did not help.

It reproduces in a 4.7.2 console application: https://github.com/skurik/cosmos-hang

**Comment by j82w** [comment]
Thanks @skurik for the repro. I'm able to reproduce the issue. If you look at the VS console output you will see the SDK is continuously retrying. More investigation is needed to figure out this many retries are a bug or by design.

**Comment by j82w** [comment]
Here is the exception after it finally times out.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8081
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.DocumentClient.HttpRequestMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.GatewayStoreClient.<>c__DisplayClass14_0.<<InvokeClientAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetryAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetryAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.GatewayStoreClient.<InvokeClientAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.GatewayStoreClient.<InvokeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.<ProcessMessageAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.<ProcessMessageAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.RequestHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.<ExecuteHttpRequestAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.<ExecuteHttpRequestAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.RequestHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.RequestHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.<SendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.<SendAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.BatchExecutor.<ExecuteServerRequestAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.BatchExecutor.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CosmosHang.Program.<Main>d__0.MoveNext() in C:\Users\jawilley\Downloads\cosmos-hang-master\cosmos-hang-master\CosmosHang\Program.cs:line 41

**Comment by ealsur** [comment]
Ok, the investigation yielded the following:

We have 2 retry policies that are happening, one is the ClientRetryPolicy and the other is the WebExceptionRetryPolicy.

The scenario you are generating @skurik does not happen with a real account, so the behavior is not well defined. In your case, shutting down the emulator mid run does not equal to a Cosmos DB account endpoint going down for 2 reasons:

* Your machine (localhost) is not down, you are just rejecting the port. This does not happen on a real Cosmos DB account, because if the endpoint/region is down, basically the endpoint is not reachable. In this case, the SDK does a retry on any of the other regions.
* Emulator does not have any other regions, so all our fall back logic does not apply.

Given the fact that this scenario can only be reproduced using the Emulator, on a particular set of steps, and does not mirror a real case scenario, working on it might not add any impactful result. I do agree that it would be great to get the failure faster, and that's why I added #1648 to track it, but this won't really repro on a real scenario.

**Comment by skurik** [comment]
Thank you for the explanation @ealsur, makes sense.
