### ISSUE TITLE
ArgumentNullException thrown in CosmosExceptionFactory

### ISSUE THREAD

**Issue by sivethe** [Azure/azure-cosmos-dotnet-v3#1741]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
EventName="FormattedMessageEvent" FormattedMessage="Exception in CosmosDB Request pipeline for account {0} and API {1}: {2}" Argument0="snc-cc-demonightlysmartops-dev" Argument1="CassandraService" Argument2="System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Microsoft.Azure.Cosmos.CosmosMessageHeadersInternal.Add(String headerName, String value)
   at Microsoft.Azure.Cosmos.Resource.CosmosExceptions.CosmosExceptionFactory.Create(DocumentClientException dce, CosmosDiagnosticsContext diagnosticsContext)
   at Microsoft.Azure.Cosmos.Extensions.ToCosmosResponseMessage(DocumentClientException documentClientException, RequestMessage requestMessage)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.ExecuteHttpRequestAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`3 callShouldRetryException, CosmosDiagnosticsContext diagnosticsContext, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Friends.DelayEstimateRequestHandler.SendWithDelayEstimateScopeAsync(RequestMessage requestMessage, DelayEstimateScope delayEstimateScope, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(Uri resourceUri, ResourceType resourceType, OperationType operationType, RequestOptions requestOptions, ContainerInternal cosmosContainerCore, Nullable`1 partitionKey, Stream streamPayload, Action`1 requestEnricher, CosmosDiagnosticsContext diagnosticsContext, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ContainerCore.ProcessItemStreamAsync(Nullable`1 partitionKey, String itemId, Stream streamPayload, OperationType operationType, ItemRequestOptions requestOptions, CosmosDiagnosticsContext diagnosticsContext, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ContainerCore.UpsertItemStreamAsync(Stream streamPayload, PartitionKey partitionKey, ItemRequestOptions requestOptions, CancellationToken cancellationToken)

**To Reproduce**
Happened in CosmosDB Internal service

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version: OSS Release Repo snap
OS Version (e.g. Windows, Linux, MacOSX): ComputeGW

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
This seems to be a bug with the service. The SDK code is currently written to fail if the header value is null. If this is an expected scenario the logic can be updated, but this will break older SDKs.

**Comment by sivethe** [comment]
Can you provide more details on where in the service this issue could be.  There is no component of the service in the call stack?

> This seems to be a bug with the service. The SDK code is currently written to fail if the header value is null. If this is an expected scenario the logic can be updated, but this will break older SDKs.

**Comment by j82w** [comment]
I don't have any idea where in the service it could be creating this value. Based on the call stack it happened when there was a DocumentClientException. I will send out a PR to add more context to the exception message so we will know which header has a null value.

**Comment by j82w** [comment]
@sivethe do we have any idea what the original document client exception was?

**Comment by sivethe** [comment]
I cannot be sure. It is hard to get the logs without the SDK activityId.  I see multiple errors in the same timewindow on the same node.  My suspect is the original exception was NotFound

**Comment by j82w** [comment]
@sivethe I created the PR to add the additional context to figure which header is causing the issue and to include the original DCE.
