### ISSUE TITLE
ArgumentNullException when start change feed processor

### ISSUE THREAD

**Issue by MishaUliutin** [Azure/azure-cosmos-dotnet-v3#1883]
We have multimaster DB and use change feed from 6 regions to subscribe on latest update. Sometimes start change feed processor fails with ArgumentNullException 

```
ArgumentNullException("Value cannot be null.
Parameter name: stream") Source: 'mscorlib'
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at Microsoft.Azure.Cosmos.CosmosJsonDotNetSerializer.FromStream[T](Stream stream)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.FromStream[T](Stream stream)
   at Microsoft.Azure.Cosmos.ChangeFeed.Utils.CosmosContainerExtensions.<TryCreateItemAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ChangeFeed.LeaseManagement.DocumentServiceLeaseStoreCosmos.<AcquireInitializationLockAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Cosmos.ChangeFeed.Bootstrapping.BootstrapperCore.<InitializeAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedManagement.PartitionManagerCore.<StartAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ChangeFeed.ChangeFeedProcessorCore`1.<StartAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Skype.PstnHub.PstnSelectorService.CosmosDb.PrefixRepository.<StartChangeFeedProcessorAsync>d__7.MoveNext() in D:\a_work\36\s\src\Microsoft.Skype.PstnHub.PstnSelectorService\CosmosDb\PrefixRepository.cs:line 131
   ....
```

I assume it is caused because lease container hits RUs limits and issues disappears after couple retries.  

SDK Version: 3.12.0
OS Version Windows, .net framework 4.8

**Comment by j82w** [comment]
This seems like a bug [here ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/2108b088e0caea206563eca8a2f035984bf84c04/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs#L49) where it only checks for a 409 conflict. If some other failure like 429 it will try to always deserialize the payload even though there isn't one. Most likely this is hiding the real the problem which is that call is failing for some reason.

**Comment by ealsur** [comment]
@MishaUliutin This operation is on the leases container, if a 429 is on the leases container it means the volume of operations happening in it is unusually high. 

Are you sharing the leases container across many Change Feed Processor deployments (deployment = configuration of monitored collection + lease collection + processorName)? Are you stopping and starting Change Feed Processors constantly?

**Comment by MishaUliutin** [comment]
> Are you sharing the leases container across many Change Feed Processor deployments (deployment = configuration of monitored collection + lease collection + processorName)?

yes

> Are you stopping and starting Change Feed Processors constantly?

no

Issues was mitigated by increasing RUs, bug mostly about misleading exception in this case

**Comment by ealsur** [comment]
@MishaUliutin PR to properly bubble up the correct exception has been merged.
