### ISSUE TITLE
ArgumentNullException with StringComparison.InvariantCulture

### ISSUE THREAD

**Issue by ylabade** [Azure/azure-cosmos-dotnet-v3#1929]
**Describe the bug**
Using the [Equals](https://docs.microsoft.com/fr-fr/dotnet/api/system.string.equals?view=netcore-3.1#System_String_Equals_System_String_System_StringComparison_) method in a where clause with `StringComparison.InvariantCulture` an `ArgumentNullException` is throw :

```
System.ArgumentNullException: Value cannot be null. (Parameter 'arguments must not have null items.')
   at Microsoft.Azure.Cosmos.SqlObjects.SqlFunctionCallScalarExpression..ctor(SqlIdentifier name, Boolean isUdf, ImmutableArray`1 arguments)
   at Microsoft.Azure.Cosmos.SqlObjects.SqlFunctionCallScalarExpression.Create(SqlIdentifier name, Boolean isUdf, ImmutableArray`1 arguments)
   at Microsoft.Azure.Cosmos.SqlObjects.SqlFunctionCallScalarExpression.Create(String name, Boolean isUdf, ImmutableArray`1 arguments)
   at Microsoft.Azure.Cosmos.SqlObjects.SqlFunctionCallScalarExpression.Create(String name, Boolean isUdf, SqlScalarExpression[] arguments)
   at Microsoft.Azure.Cosmos.SqlObjects.SqlFunctionCallScalarExpression.CreateBuiltin(String name, SqlScalarExpression[] arguments)
   at Microsoft.Azure.Cosmos.Linq.StringBuiltinFunctions.StringEqualsVisitor.VisitImplicit(MethodCallExpression methodCallExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.BuiltinFunctionVisitor.Visit(MethodCallExpression methodCallExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.StringBuiltinFunctions.Visit(MethodCallExpression methodCallExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.BuiltinFunctionVisitor.VisitBuiltinFunctionCall(MethodCallExpression methodCallExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression expression, ReadOnlyCollection`1 parameters, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitScalarExpression(Expression expression, ReadOnlyCollection`1 parameters, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitScalarExpression(LambdaExpression lambda, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitWhere(ReadOnlyCollection`1 arguments, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitMethodCall(MethodCallExpression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.Translate(Expression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.TranslateQuery(Expression inputExpression, IDictionary`2 parameters, CosmosSerializationOptions serializationOptions)
   at Microsoft.Azure.Cosmos.Linq.SqlTranslator.TranslateQuery(Expression inputExpression, CosmosSerializationOptions serializationOptions, IDictionary`2 parameters)
   at Microsoft.Azure.Cosmos.Linq.DocumentQueryEvaluator.HandleMethodCallExpression(MethodCallExpression expression, IDictionary`2 parameters, CosmosSerializationOptions serializationOptions)
   at Microsoft.Azure.Cosmos.Linq.DocumentQueryEvaluator.Evaluate(Expression expression, CosmosSerializationOptions serializationOptions, IDictionary`2 parameters)
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery`1.CreateFeedIterator(Boolean isContinuationExcpected)
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery`1.ToFeedIterator()
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqExtensions.ToFeedIterator[T](IQueryable`1 query)
```

There is no exception with `StringComparison.InvariantCultureIgnoreCase`

**To reproduce**
```cs
var cosmosClient = new CosmosClient(connectionString);
var database = cosmosClient.GetDatabase("db1");
var container = database.GetContainer("container1");
var queryable = container.GetItemLinqQueryable<ToDoItem>();
var iterator = queryable.Where(x => x.Name.Equals(subjectId, StringComparison.InvariantCulture)).ToFeedIterator();
```

**Environment summary**
SDK Version: 3.14.0
OS Version: Windows 10 1909

**Comment by j82w** [comment]
@ylabade please try the latest [3.15.0 release](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.15.0)
