### ISSUE TITLE
CosmosClientBuilder.Build causing Method not found for GetUserAuthorizationToken

### ISSUE THREAD

**Issue by Scythen** [Azure/azure-cosmos-dotnet-v3#2038]
**Describe the bug**
Developing a V3 Azure Functions app with netcoreapp3.1 target.
Attempting to use Cosmos DB .NET V4 SDK but unable build client.
Calling Build on the CosmosClientBuilder results in MissingMethodException for IAuthorizationTokenProvider.GetUserAuthorizationToken

This does not happen with a console app, just in the Functions App.

**To Reproduce**
Create a functions app.
Add Cosmos V4 API
Add CosmosClient service.
Inject CosmosClient into a function.

```
using System;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Azure.Cosmos.Fluent;

namespace FunctionsApp
{
    static class IWebJobsBuilderExtension
    {
        public static IWebJobsBuilder AddCosmosClient(this IWebJobsBuilder builder)
        {
            if (builder == null)
                throw new ArgumentNullException(nameof(builder));

            var serviceProvider = builder.Services.BuildServiceProvider();

            var configuration = serviceProvider.GetService<IConfiguration>();

            builder.Services.AddSingleton(s =>
            {
                var connectionString = configuration["CosmosDBConnection"];
                if (string.IsNullOrEmpty(connectionString))
                {
                    throw new InvalidOperationException(
                        "Please specify a valid CosmosDBConnection in the appSettings.json file or your Azure Functions Settings.");
                }
                var builder = new CosmosClientBuilder(connectionString);
                return builder.Build();
            });
            return builder;
        }
    }
}
```

**Expected behavior**
builder.Build() returns a CosmosClient

**Actual behavior**
builder.Build() throws exception:
```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.String Microsoft.Azure.Documents.IAuthorizationTokenProvider.GetUserAuthorizationToken(System.String, System.String, System.String, Microsoft.Azure.Documents.Collections.INameValueCollection, Microsoft.Azure.Documents.AuthorizationTokenType, System.String ByRef)'.
  Source=Azure.Cosmos
  StackTrace:
   at Azure.Cosmos.CosmosClient..ctor(String accountEndpoint, String authKeyOrResourceToken, CosmosClientOptions clientOptions) in .\JetBrains\Shared\vAny\DecompilerCache\decompiler\B4CF19D5-8DD3-4D13-B2DD-EF2C203E8245\8c\9959ed31\CosmosClient.cs:line 72
   at Azure.Cosmos.Fluent.CosmosClientBuilder.Build() in .\JetBrains\Shared\vAny\DecompilerCache\decompiler\B4CF19D5-8DD3-4D13-B2DD-EF2C203E8245\51\157ca07a\CosmosClientBuilder.cs:line 42
```

**Environment summary**
SDK Version: v4
OS Version Windows 10

**Additional context**
Connection string example `AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==`

Package references:
```
    <PackageReference Include="Azure.Cosmos" Version="4.0.0-preview3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.8.0" />
    <PackageReference Include="YamlDotNet" Version="9.1.0" />
```

**Comment by Scythen** [comment]
This appears to be some sort of interaction with `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` im using for JWT issue [397](https://github.com/Azure/azure-functions-vs-build-sdk/issues/397).
I removed legacy cosmos references, deleted all output folders and then readded the reference. This seems to have solved the issue.

**Comment by j82w** [comment]
@Scythen it's recommended to use the v3 SDK currently. The v4 SDK is a early preview version, and is waiting on some new features from the Cosmos DB service. 

The issue itself sounds like the Direct dll was a newer version from the v3 SDK. That is why removing the v3 reference and cleaning the output folders fixed the issue.

**Comment by gjvdkamp** [comment]
I get the same error when trying to create a CosmosClient

```
       services
                .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)               
                .AddIdentityServerAuthentication(options => {
                    options.ApiName = "xlc.api";
                    options.Authority = Repo.Authority;
                });
          
            var ep = Configuration["cosmosdb:AccountEndpoint"];
            var key = Configuration["cosmosdb:AccountKey"];
            services.AddSingleton<CosmosClient>(new CosmosClient(ep, key)); // this line throws (also tried the entire connectionstring as one string)

```

throws: 
```
Unhandled exception. System.MissingMethodException: Method not found: 'System.String Microsoft.Azure.Documents.IAuthorizationTokenProvider.GetUserAuthorizationToken(System.String, System.String, System.String, Microsoft.Azure.Documents.Collections.INameValueCollection, Microsoft.Azure.Documents.AuthorizationTokenType, System.String ByRef)'.
   at Azure.Cosmos.CosmosClient..ctor(String accountEndpoint, String authKeyOrResourceToken, CosmosClientOptions clientOptions)
   at MyApp.API.Startup.ConfigureServices(IServiceCollection services) in C:\Users\me\source\repos\MyApp\MyApp.API\Startup.cs:line 89
```

I included the ldentityServer lines above as the error seems to have to do with jwt.

The package is in Preview 3 now, are we still not supposed to use it for greenfield stuff (going live in a month or so..)?
