### ISSUE TITLE
CosmosDiagnostics throws  IndexOutOfRangeException

### ISSUE THREAD

**Issue by LiDamon** [Azure/azure-cosmos-dotnet-v3#2075]
We want get count about all partition with special filter, but have an error
Message:System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Azure.Cosmos.CosmosDiagnosticsContextCore.<GetEnumerator>d__42.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.Azure.Cosmos.CosmosDiagnosticsContextCore.AddDiagnosticsInternal(CosmosDiagnosticsContext newContext)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.<ReadNextAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.<ReadNextAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Test.CosmosIndexDocService.<>c__DisplayClass34_0.<<GetCount>b__0>d.MoveNext() in C:\CosmosIndexDocService.cs:line 980
   --- End of inner exception stack trace ---
   at Test.CosmosIndexDocService.GetCount() in C:\CosmosIndexDocService.cs:line 993
   at CosmosService.SPIndexService.GetUserGranPermissionCount() in C:\SPIndexService.cs:line 2284
   at Test.GetSensitivityCount(String tenantId, String logonName, String dorid, DataModule module, SensitiveLevel sensitiveLevel, MemberType type) in C:\\AggUsersRelation.cs:line 409
   at GetUseGroupAccess(UsersRelationInfo user, MemberType type) in C:\Aggregate\AggUsersRelation.cs:line 285
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Azure.Cosmos.CosmosDiagnosticsContextCore.<GetEnumerator>d__42.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.Azure.Cosmos.CosmosDiagnosticsContextCore.AddDiagnosticsInternal(CosmosDiagnosticsContext newContext)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.<ReadNextAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.<ReadNextAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Test.CosmosIndexDocService.<>c__DisplayClass34_0.

**Environment summary**
SDK Version:3.15.0
OS Version  Windows 
.NET Version:4.7.2

**Comment by j82w** [comment]
@LiDamon any chance you can provide a simple console app that reproduce the issue? If not can you please provide the query, query request options, and any other custom settings you have configured for the SDK?

**Comment by LiDamon** [comment]
This is my code
`public int GetCount()
        {
            Stopwatch sw = new Stopwatch();
            sw.Start();
            try
            {
                var queryText = @"SELECT value count(1) FROM c where c.schema=10 and c.type=128 and c.module=2 
                    and c.inherittype=1 and c.dorid='42dd7df6-e706-44b1-ba4f-5f9a9bf6342d'";
                var query = new QueryDefinition(queryText);
                var options = new QueryRequestOptions
                {
                    MaxConcurrency = 100000,
                    MaxBufferedItemCount = 1,
                    MaxItemCount = 1
                };
                using (var queryIterator = container.GetItemQueryIterator<Int32>(query, null, options))
                {
                    while (queryIterator.HasMoreResults)
                    {
                        var queryTask = Task.Run(async () => await queryIterator.ReadNextAsync());
                        queryTask.Wait(TimeSpan.FromMinutes(10));
                        if (queryTask.Result.Count == 1)
                        {
                            return queryTask.Result.FirstOrDefault();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
               
            }
            return 0;
        }`
        
        This is index json 
        
![image](https://user-images.githubusercontent.com/3748285/102570007-75bd5280-4121-11eb-964c-3d81c58b6e7f.png)

        
        BTW , we  before used  3.12 don't found this issue. Upgrade to 3.15 found it. So we plan downgrade to 3.12

**Comment by LiDamon** [comment]
I add retry  logic, Won't show up exception the second time.

**Comment by j82w** [comment]
@LiDamon what is the reason for doing the Task.Run? Why not just use a cancellation token with a timeout?

**Comment by LiDamon** [comment]
The main reason is here:
https://stackoverflow.com/questions/14526377/why-does-this-async-action-hang
