### ISSUE TITLE
Availability: Adds cross-region retry mechanism on 500 issues

### ISSUE THREAD

**Issue by yar-shukan** [Azure/azure-cosmos-dotnet-v3#2211]
**Describe the bug**
When CosmosDB region is down (e.g. like with NOA region issue happened at 1:00 AM UTC February 2021 (Azure Cosmos DB - North America - Mitigated (Tracking ID CVTV-R80) ) it responds with 500 error code:

![image](https://user-images.githubusercontent.com/2014175/107756769-c0300980-6d35-11eb-8966-616171e927dd.png)

And it looks like it continues to make requests to region that constantly responds with 500 and doesn't fallback to another region.

There was a fix (see #1715) to address similar problem, **but it handles only 503, but not 500**.

**To Reproduce**
Make read or write requests to region when region is down and responds with 500 error codes.

**Expected behavior**
If `PreferredLocations > 1` and CosmosDB account has multiple read regions, SDK client stops sending requests to region that is responding with `500` and falls back to another region in `PreferredLocations` list. Already failed with `500` requests are retried to another PreferredLocation.

**Actual behavior**
SDK continues to send requests to same region that responds with 500.

**Environment summary**
SDK Version: latest for v2 and v3.
OS Version: observed on Windows.

**Additional context**
N/A

**Comment by yar-shukan** [comment]
Hi @ealsur, thank you for original #1715 improvement. But we do see that SDK is not resilient when 500 happens, and during last 3 weeks we observe the same pattern: CosmosDB backend starts to respond with 429 or 500 (this ticket case) when region is down.

- I'm wondering if there was any reason why you've added only 503 handling, but not any 5xx response code?
- Can you please confirm that your fix works only for 1 request? As client is singleton, if this 503 issue appears e.g. for long period of time, will SDK constantly try to attempt region that responds with 503 and make 1 retry, or it makes a retry and switches singleton to use another region from `PreferredLocation` list?

**Comment by ealsur** [comment]
SDK won't retry on 500. HTTP 500 implies an error on the backend, there is no semantics that tells the client that it is a retriable state.

503 is a temporary state and thus retried. So no, we won't retry blindly on 5XX.

Regarding the semantics, it is request level based. So 1 request failure and retry does not affect other requests. Because 503 is a temporary state, it does not affect all requests nor subsequent requests. Getting 503s for a long period of time hints at a service issue. The SDK is resilient to temporary failure state. To answer your question, if 1 request fails with a 503, retries on a second region and succeeds, a second request would still hit the original region, as there is no indication that it should fail (again, 503 is temporary state response).

If you are getting 503s for a long period of time, please first verity that it's not a client side connectivity issue: https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-service-unavailable

If you are getting HTTP 500 or 503s for a long period of time (and it's not a client side issue), please file a support ticket as this is not related to the client.

**Comment by yar-shukan** [comment]
@ealsur if you say _HTTP 500 implies an error on the backend_ I don't really understand why SDK shouldn't act on it and why SDK continues to make requests to region that constantly responds with 500? the problem with current retry design is that SDK not resilient at all all to backend issues when backend responds with 500 due to internal issue that makes region unavailable for requests for lot of minutes.

**I think it would be nice to reopen this ticket and improve SDK to react to 500s and do at least something with it**. I think what it should do is the following:
1. Fallback at least read operations to another available region (it should be safe to retry 500 reads as I don't see a big difference with 503 case)
2. Stop doing at least read requests to affected region that responds with 500 (consider it unavailable).

Otherwise I don't see a good way to maintain resiliency and HA when CosmosDB backend has issues with 500s. And also this thing when it responds with 500s for about 30 mins+ is the second time we observe in 3 weeks so for me it looks like current design is not resilient to 500 failures that showed to have pretty high probability of happening.

If you close this ticket and think that there's nothing to improve or do here, can you please propose how should we as a client act except filling a SR ticket during 500s outage? Filling SR ticket doesn't our service to stay resilient and HA while CosmosDB region is constantly erroring with 500s.

I think the fact that 500s are not handled right now is a gap and it must be considered. Please reopen the ticket or explain better motivation why you believe 500s shouldn't be retried and considered as an service outage. Thanks!

**Comment by ealsur** [comment]
@yar-shukan The problem is that you are assuming that a retry would fix the HTTP 500 situation, what if the issue is related to a problem that is spanning multiple regions? Why would it be safe to retry a read request with HTTP 500? There are no guarantees based on the server response. We can take actions when the scenario is clear that there is a path forward that will resolve the situation and there are several of these in our docs but an HTTP 500 has no clear indication of what is the issue and what to do, it just means that there was a critical/catastrophic error with that request, it does not even mean the next request will fail (for example, if there is a Write region fail-over, it is clear by the HTTP 403 substatus 3 that all Write requests will fail unless we switch to the new Write region on the client).

Given that HTTP 500 is totally unclear on what the scope of the failure is or what should we do, taking any action could be detrimental, we have no way of knowing that that action will actually fix the issue.

**Comment by yar-shukan** [comment]
@ealsur I understand your point that retries or automatic failover to another region on HTTP 500 can lead to the same 500 on another region. But there's also a chance that another region will be successful, we simply don't know.

For example, there's a code in ClientRetryPolicy [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/540070c96cc50bd9e655e6d0e7bb5cf10e4f8f2a/Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs#L69) and it does mark endpoint as unavailable globally in the case of `HttpRequestException` without analyzing the status code and does retry.

So what I don't understand from your point and the code is:

1. Why it makes retry on `HttpRequestException` exception type without analyzing status code, but HTTP 500 is not retriable? Per my understanding, `HttpRequestException` supposed to be a generic error of HTTP request, but maybe 500 deserializes to another exception type and it's just a gap in logic that should be covered?
2. Why `HttpRequestException` supposed to be OK to retry on another region and failover to another region, but not 500?

If you still believe that failover and retry of 500s shouldn't be handled by default, I think this has to be at least configurable to give a client a chance to decide what to do with this situation (as it's done e.g. for 429s) as continue sending requests to the region that responds for minutes or hours with 500 is not an optimal design decision.

**Comment by ealsur** [comment]
Reopening pending discussion and investigation of the root cause of those HTTP 500.

**Comment by yar-shukan** [comment]
@ealsur, I've rechecked the fact that you didn't observe 500s during that outage on the CosmosDB side and I do confirm that my initial observation was wrong: we use wrapper library and it this library logged `TaskCanceledException` with 500 status code and definitely it's not from CosmosDB backend. Sorry for misleading.

The stack trace that we did observe during the outage are the following:

```
exception type=System.Threading.Tasks.TaskCanceledExceptionTaskCanceledException(A task was canceled.)

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.Client.ClientExtensions.<GetAsync>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.Routing.GatewayAddressCache.<GetServerAddressesViaGatewayAsync>d__24.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.Routing.GatewayAddressCache.<GetAddressesForRangeId>d__22.MoveNext()
  at Microsoft.Azure.Documents.Query.DocumentProducer`1.<>c.<MoveNextPage>b__62_1(ExceptionDispatchInfo exceptionDispatchInfo)
  at Microsoft.Azure.Documents.Query.DocumentProducer`1.<MoveNextPage>d__62.MoveNext()
  at Microsoft.Skype.Identity.CosmosDb.Monitoring.MeteredDocumentQuery`1.<ExecuteNextAsync>d__13`1.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess( Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.AsyncCache`2.<GetAsync>d__8.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.Query.DocumentProducer`1.<MoveNextAsyncImplementation>d__59.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.AsyncCache`2.<GetAsync>d__8.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.<MoveNextAsyncImplementation>d__46.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.<ExecuteWithSplitProofing>d__49.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.<MoveNextAsync>d__38.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.Query.ParallelDocumentQueryExecutionContext.<DrainAsync>d__7.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Skype.Identity.CosmosDb.Monitoring.MeteredDocumentQuery`1.<ExecuteNextAsync>d__13`1.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.<ExecuteNextAsync>d__7.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<ExecuteNextPrivateAsync>d__36`1.MoveNext()
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.IC3.DirectoryCache.Library.RunTime.Cache.Providers.CosmosDB.ExperimentalWrappedDocumentClient.ExperimentalDocumentQuery`1.<ExecuteNextAsync>d__6`1.MoveNext() in D:\a_work\295\s\src\Library\RunTime\Cache\Providers\CosmosDB\ExperimentalWrappedDocumentClient.cs:line 326
 --- End of stack trace from previous location where exception was thrown
 ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Skype.Identity.CosmosDb.Monitoring.MeteredDocumentQuery`1.<ExecuteNextAsync>d__13`1.MoveNext()
```

Please feel free to close this issue.

**Comment by ealsur** [comment]
The stack trace looks like V2 SDK, not V3 (mainly because of `Microsoft.Azure.Documents.Linq.DocumentQuery`1.<ExecuteNextPrivateAsync>d__36`1.MoveNext()`, V3 SDK's namespace is Microsoft.Azure.Cosmos).

`TaskCanceledException` sounds like an HTTP timeout, in this case, trying to get Addresses for the target partitions.

[Newer V2 SDKs](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-dotnet) have fixes and improvements on resiliency for queries (particularly 2.11.5 and 2.12.0), so the recommendation would be to upgrade to those if possible.
