### ISSUE TITLE
ChangeFeed Estimator Instances fail with "NotFound" when running StopAsync()

### ISSUE THREAD

**Issue by cacceres95** [Azure/azure-cosmos-dotnet-v3#2389]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
We are seeing recurring CosmosExceptions thrown with the errors of "NotFound" and "TooManyRequests" when running StopAsync() on a changeFeedEstimator instance. These errors started showing up after we updated our SDK version from version 3.11.0 to 3.17.0

It is worth noting that when looking at the monitored container and the lease container we cannot correlate the 429's we are seeing in the logs with any actual throttling in those containers. 

**To Reproduce**
We have a worker application in service fabric that manages the instance creation of ChangeFeedProcessors and ChangeFeedEstimators in order to transfer data from one Cosmos Container to another. Whenever we deploy a new version of this Service Fabric application we attempt to gracefully shutdown the instances, but with the latest version of the SDK the errors continuously appear when we try to stop a ChangeFeedEstimator instances.

### Not Found Errors stack trace:
> Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 5e52a3dc-7020-44c7-a2e2-75cd702710ae; Reason: (Message: {"Errors":["Resource Not Found. Learn more: https:\/\/aka.ms\/cosmosdb-tsg-not-found"]}
ActivityId: 5e52a3dc-7020-44c7-a2e2-75cd702710ae, Request URI: /apps/417a6fa3-21c0-4fce-bf62-b97c83f9df74/services/bb57e92f-54ca-4e0a-be18-5f16c4e9bc35/partitions/924c314e-a985-4de9-b368-c73722bf6984/replicas/132585944413485073s, RequestStats: 
RequestStartTime: 2021-04-14T13:56:42.5868364Z, RequestEndTime: 2021-04-14T13:56:42.5868364Z,  Number of regions attempted:1
ResponseTime: 2021-04-14T13:56:42.5868364Z, StoreResult: StorePhysicalAddress: rntbd://10.0.0.18:11300/apps/417a6fa3-21c0-4fce-bf62-b97c83f9df74/services/bb57e92f-54ca-4e0a-be18-5f16c4e9bc35/partitions/924c314e-a985-4de9-b368-c73722bf6984/replicas/132585944413485073s, LSN: 1677091, GlobalCommittedLsn: 1677091, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#1677091, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
ResponseTime: 2021-04-14T13:56:42.5868364Z, StoreResult: StorePhysicalAddress: rntbd://10.0.0.22:11300/apps/417a6fa3-21c0-4fce-bf62-b97c83f9df74/services/bb57e92f-54ca-4e0a-be18-5f16c4e9bc35/partitions/924c314e-a985-4de9-b368-c73722bf6984/replicas/132494219595667850s, LSN: 1677091, GlobalCommittedLsn: 1677091, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#1677091, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
, SDK: Microsoft.Azure.Documents.Common/2.11.0, Windows/10.0.17763 cosmos-netstandard-sdk/3.17.1);
   at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
   at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Routing.ClientCollectionCache.ReadCollectionAsync(String collectionLink, CancellationToken cancellationToken, IDocumentClientRetryPolicy retryPolicyInstance)
   at Microsoft.Azure.Documents.BackoffRetryUtility'1.ExecuteRetryAsync(Func'1 callbackMethod, Func'3 callShouldRetry, Func'1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action'1 preRetryCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.BackoffRetryUtility'1.ExecuteRetryAsync(Func'1 callbackMethod, Func'3 callShouldRetry, Func'1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action'1 preRetryCallback)
   at Microsoft.Azure.Cosmos.Common.CollectionCache.<>c__DisplayClass10_0.<<ResolveByNameAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Cosmos.Common.AsyncCache'2.GetAsync(TKey key, TValue obsoleteValue, Func'1 singleValueInitFunc, CancellationToken cancellationToken, Boolean forceRefresh)
   at Microsoft.Azure.Cosmos.Common.CollectionCache.ResolveByNameAsync(String apiVersion, String resourceAddress, Boolean forceRefesh, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ContainerCore.GetCachedContainerPropertiesAsync(Boolean forceRefresh, ITrace trace, CancellationToken cancellationToken)
--- Cosmos Diagnostics ---{"name":"NoOp","id":"00000000-0000-0000-0000-000000000000","component":"Unknown","caller info":{"member":"NoOp","file":"NoOp","line":9001},"start time":"12:00:00:000","duration in milliseconds":0,"data":{},"children":[]}

### TooManyRequests Errors stack trace:
> Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: TooManyRequests (429); Substatus: 3200; ActivityId: d3c7b9a2-7ddd-43bf-9795-0f2b9fdb44a8; Reason: ({
  "Errors": [
    "Request rate is large. More Request Units may be needed, so no changes were made. Please retry this request later. Learn more: http://aka.ms/cosmosdb-error-429"
  ]
});
   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.ProcessMessage[T](ResponseMessage responseMessage, Func'2 createResponse)
   at Microsoft.Azure.Cosmos.DatabaseCore.ReadAsync(RequestOptions requestOptions, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](ITrace trace, Func'2 task)
   at Microsoft.Azure.Cosmos.ClientContextCore.OperationHelperWithRootTraceAsync[TResult](String operationName, RequestOptions requestOptions, Func'2 task)
   at Microsoft.Azure.Cosmos.DatabaseCore.GetRIDAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.Utils.CosmosContainerExtensions.GetMonitoredDatabaseAndContainerRidAsync(Container monitoredContainer, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.ChangeFeedEstimatorIterator.InitializeLeaseStoreAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.ChangeFeedEstimatorIterator.ReadNextAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.FeedEstimatorRunner.GetEstimatedRemainingWorkAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.FeedEstimatorRunner.EstimateAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.FeedEstimatorRunner.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.ChangeFeedEstimatorRunner.StopAsync()
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func'3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates'1 shouldRetryResultPredicates, Func'5 onRetryAsync, Int32 permittedRetryCount, IEnumerable'1 sleepDurationsEnumerable, Func'4 sleepDurationProvider, Boolean continueOnCapturedContext)
--- Cosmos Diagnostics ---{"name":"ReadAsync","id":"d5a2a50e-872f-4f1d-9888-30831306b56b","component":"Transport","caller info":{"member":"OperationHelperWithRootTraceAsync","file":"ClientContextCore.cs","line":207},"start time":"09:04:38:084","duration in milliseconds":2.7535,"data":{},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","id":"b9096eb6-d915-4cf6-a773-c7c042c7b7a8","component":"RequestHandler","caller info":{"member":"SendAsync","file":"RequestInvokerHandler.cs","line":148},"start time":"09:04:38:084","duration in milliseconds":2.5159,"data":{},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","id":"387beeab-61b7-40d0-805c-4327b8ce7191","component":"RequestHandler","caller info":{"member":"SendAsync","file":"RequestInvokerHandler.cs","line":51},"start time":"09:04:38:084","duration in milliseconds":2.5134,"data":{},"children":[{"name":"Send Async","id":"07d62363-4aab-47e3-9920-de2ebef5e7f2","component":"RequestHandler","caller info":{"member":"SendAsync","file":"RequestHandler.cs","line":50},"start time":"09:04:38:084","duration in milliseconds":2.5109,"data":{},"children":[{"name":"Send Async","id":"da68475c-7f73-4857-9c5c-2e341b41cb2d","component":"RequestHandler","caller info":{"member":"SendAsync","file":"RequestHandler.cs","line":50},"start time":"09:04:38:084","duration in milliseconds":2.4062,"data":{"CPU Load History":{"CPU History":"(2021-04-13T21:03:40.8793765Z 14.844), (2021-04-13T21:03:50.8737256Z 1.562), (2021-04-13T21:04:00.8773034Z 4.688), (2021-04-13T21:04:10.8738335Z 1.176), (2021-04-13T21:04:20.8754135Z 3.125), (2021-04-13T21:04:30.8669862Z 1.587)"}},"children":[{"name":"Send Async","id":"346355d0-381b-43ee-8054-21c7dbcf48bc","component":"RequestHandler","caller info":{"member":"SendAsync","file":"RequestHandler.cs","line":50},"start time":"09:04:38:084","duration in milliseconds":2.4045,"data":{},"children":[{"name":"Send Async","id":"6fc48ee4-5ac0-411f-993c-6e2c8934dfeb","component":"RequestHandler","caller info":{"member":"SendAsync","file":"AbstractRetryHandler.cs","line":23},"start time":"09:04:38:084","duration in milliseconds":2.4035,"data":{},"children":[{"name":"Send Async","id":"d85ac658-dc46-4e5e-8071-2b89843aec1f","component":"RequestHandler","caller info":{"member":"SendAsync","file":"RequestHandler.cs","line":50},"start time":"09:04:38:084","duration in milliseconds":2.1899,"data":{},"children":[{"name":"Microsoft.Azure.Documents.ServerStoreModel Transport Request","id":"3008f09e-a905-427d-8df4-3dcc114cba81","component":"Transport","caller info":{"member":"ProcessMessageAsync","file":"TransportHandler.cs","line":87},"start time":"09:04:38:084","duration in milliseconds":2.1684,"data":{"User Agent":"cosmos-netstandard-sdk/3.17.0|3.17.1|01|X64|Microsoft Windows 10.0.17763|.NET Core 3.1.5|","Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus1-fd42.documents.azure.com:11307/apps/814e7582-0a8b-498b-8d4f-92263e029030/services/0556682d-63fd-4fa7-a9c5-9fa9d976a600/partitions/53396c1c-8002-43b3-9b9d-edb0d3cc4bc0/replicas/132520408752982009s/"}],"RegionsContacted":["https://cosmos-vs-dt-su-pr-eus-01-eastus.documents.azure.com/"],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[{"ResponseTimeUTC":"2021-04-13T21:04:38.0866640Z","ResourceType":"Database","OperationType":"Read","LocationEndpoint":"https://cosmos-vs-dt-su-pr-eus-01-eastus.documents.azure.com/","StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-eastus1-fd42.documents.azure.com:11309/apps/814e7582-0a8b-498b-8d4f-92263e029030/services/0556682d-63fd-4fa7-a9c5-9fa9d976a600/partitions/53396c1c-8002-43b3-9b9d-edb0d3cc4bc0/replicas/132521222167179504s/, LSN: 1628989, GlobalCommittedLsn: 1628989, PartitionKeyRangeId: , IsValid: True, StatusCode: 429, SubStatusCode: 3200, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: False, TransportException: null"},{"ResponseTimeUTC":"2021-04-13T21:04:38.0866670Z","ResourceType":"Database","OperationType":"Read","LocationEndpoint":"https://cosmos-vs-dt-su-pr-eus-01-eastus.documents.azure.com/","StoreResult":"StorePhysicalAddress: rntbd://cdb-ms-prod-eastus1-fd42.documents.azure.com:11307/apps/814e7582-0a8b-498b-8d4f-92263e029030/services/0556682d-63fd-4fa7-a9c5-9fa9d976a600/partitions/53396c1c-8002-43b3-9b9d-edb0d3cc4bc0/replicas/132520408752982009s/, LSN: 1628989, GlobalCommittedLsn: 1628989, PartitionKeyRangeId: , IsValid: True, StatusCode: 429, SubStatusCode: 3200, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: False, TransportException: null"}]}},"children":[]}]}]}]}]}]}]}]}]}

**Expected behavior**
We would expect the ChangeFeedEstimator instance to safely stop the instance and release any resources occupied.

**Actual behavior**
CosmosExceptions are thrown with 404 and 429 error status codes. We see an increase usage in memory and CPU on the VMs that host these instances and an increase number of outgoing requests calls to the lease container.

**Environment summary**
SDK Version: 3.17.0
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
### Logs:
[Logs.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/6312662/Logs.zip)

**Comment by ealsur** [comment]
From the stack trace, the exception is actually happening during the initialization, since the Stop just awaits on the initialization task to make sure no tasks are left running, that is when the exception raises, but the exception actually happened during the running: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorRunner.cs#L96

This means that at some point during the Estimator, you got throttled, and the Task just captured that exception. Based on the stack trace, it looks like the Estimator could not obtain the container information and you should probably see 429s in Get Database or Get Collection.

The same goes for the other exception, basically there is a 404 (the collection does not exist) and due to the nature of the task awaiting, it surfaces on the Stop.

This could be an effect of the refactoring (ideally this should be thrown on the Start), but you’d still get these errors.
