### ISSUE TITLE
NullReferenceException when using GetItemLinqQueryable without partition key in LINQ filters

### ISSUE THREAD

**Issue by azzimuth** [Azure/azure-cosmos-dotnet-v3#2479]
**Describe the bug**
When I try to get items from the database using the GetItemLinqQueryable method without partition key in LINQ filters, I get `NullReferenceException` at `await cosmosQuery.CountAsync();`. As soon as I add the partition key to LINQ filters, everything works.

**To Reproduce**
Sample code [here](https://github.com/azzimuth/CosmosTest.git).

**Expected behavior**
Using GetItemLinqQueryable without LINQ filter for partition key does not throw an exception. The queryable returns the items matching the filters.

**Actual behavior**
Using GetItemLinqQueryable without LINQ filter for partition key throws an exception.

Exception details:
```javascript
System.Reflection.TargetInvocationException:` Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
 at lambda_method(Closure )
 --- End of inner exception stack trace ---
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
 at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.EvaluateConstant(Expression expression)
 at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
 at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visit
or)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
 
  at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Evaluate(Expression expression)
   at Microsoft.Azure.Cosmos.Linq.ConstantEvaluator.PartialEval(Expression expression, Func`2 fnCanBeEvaluated)
   at Microsoft.Azure.Cosmos.Linq.ConstantEvaluator.PartialEval(Expression expression)
   at Microsoft.Azure.Cosmos.Li
nq.SqlTranslator.TranslateQuery(Expression inputExpression, CosmosLinqSerializerOptions linqSerializerOptions, IDictionary`2 parameters)
   at Microsoft.Azure.Cosmos.Linq.DocumentQueryEvaluator.HandleMethodCallExpression(MethodCallExpression expression, IDictionary`2 parameters, CosmosLinqSerializerOptions linqSerializerOptions)
   at Microsoft.Azure.Cosmos.Linq.DocumentQueryEvaluator.Evaluate(Expression expression, CosmosLinqSerializerOptions linqSerializerOptions, IDictionary`2 parameters)
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery`1.CreateFeedIterator(Boolean isContinuationExpected)
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery`1.AggregateResultAsync(CancellationToken cancellationToken)
   at CosmosTest.Service.CosmosDbClient.GetLeadsAsync(LeadsSearch search) in C:\\Project\\CosmosTest\\Service\\CosmosDbClient.cs:line 33
```

**Environment summary**
SDK Version: 3.18.0
OS Version (e.g. Windows, Linux, MacOSX): 
Edition	Windows 10 Pro
Version	20H2
OS build	19042.985
Experience	Windows Feature Experience Pack 120.2212.2020.0

**Comment by j82w** [comment]
@azzimuth can you add the exception.ToString() to the description?

**Comment by azzimuth** [comment]
@j82w, done

**Comment by j82w** [comment]
It seems to be incorrectly handling the scenario if a function is passed in for a binary comparison that is not from the passed in passed in delegate.

`queryable = queryable.Where(lead => lead.LeadRequest.CountryCode.ToUpper() == search.MarketCode.ToUpper());`

As a temporary workaround until a fix is deploy you can do the following.
```c#
string searchMarkCode = search.MarketCode.ToUpper();
queryable = queryable.Where(lead => lead.LeadRequest.CountryCode == searchMarkCode);
```

**Comment by azzimuth** [comment]
Great, it works. Thanks!

**Comment by j82w** [comment]
I would always recommend passing the partition key in the request options when possible. It guarantees that the query is restricted to a single partition. Without the partition key it's possible it will do a cross partition query which will be significantly slower and cost more RUs.

**Comment by azzimuth** [comment]
@j82w, yes, we will consider changing the partition key to the other field.
