### ISSUE TITLE
wrong error when Aad access is unauthorized "The remote name could not be resolved myaccount-westus.documents.azure.com"

### ISSUE THREAD

**Issue by oscarcabrero** [Azure/azure-cosmos-dotnet-v3#2496]
3.19-preview1
**Describe the bug**
when attempt to open a new connection using auth token credential provider i get
the remote name could not be resolved: 'myaccount-westus.documents.azure.com'

i have 2 regions only 1 is write, but both failed with same issue. when using preferredlocations.

**Expected behavior**
the cosmos client is returned

**Actual behavior**
an exception is thrown

**Environment summary**
SDK Version: 3.19-preview1
OS Version Windows latest

**Additional context**
 at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.GetAccountPropertiesHelper.<GetAccountPropertiesAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.GatewayAccountReader.<InitializeReaderAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.CosmosAccountServiceConfiguration.<InitializeAsync>d__36.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.DocumentClient.<InitializeGatewayConfigurationReaderAsync>d__302.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.DocumentClient.<GetInitializationTaskAsync>d__96.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.DocumentClient.<EnsureValidClientAsync>d__156.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.DocumentClient.<GetPartitionKeyRangeCacheAsync>d__79.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ContainerCore.<GetFeedRangesAsync>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ClientContextCore.<RunWithDiagnosticsHelperAsync>d__38`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ClientContextCore.<OperationHelperWithRootTraceAsync>d__29`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.CosmosClient.<InitializeContainerAsync>d__61.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.CosmosClient.<CreateAndInitializeAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.CaseManagement.Common.Providers.DocumentDb.DbConnectionManager.<CreateAndInitializeAsync>d__10.MoveNext() in E:\repos\MSEG.CMC.CCM.Services.CaseManagement\Product\Source\Microsoft.CaseManagement.Provider.DocumentDb\DbConnectionManager.cs:line 117

**Comment by j82w** [comment]
@oscarcabrero does it work without the preferred regions?

**Comment by ealsur** [comment]
If you go to the machine experiencing this error, can you run `nslookup` or a similar tool to know if it can resolve DNS entries correctly?

**Comment by j82w** [comment]
@oscarcabrero I wasn't able to reproduce the issue. Can you provide a sample program and/or more details on the CosmosClient configuration? 

I created a CosmosClient with ApplicationPreferredRegions on an account with single master so only 1 write region that was replicated to 2 regions. I was able to connect, insert, and read data.

```c#
 CosmosClientOptions clientOptions = new CosmosClientOptions()
            {
                ApplicationPreferredRegions = new List<string>()
                {
                    Regions.EastUS2,
                    Regions.CentralUS
                }
            };
return new CosmosClient(
                    "https://{AccountName}.documents.azure.com:443/",
                    new ManagedIdentityCredential(),
                    clientOptions);
```

**Comment by oscarcabrero** [comment]
without the preferredregions i get a 401 access error
Request blocked by Auth myaccount : Request is blocked because principal [95b54b20-...] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata]

**Comment by oscarcabrero** [comment]
> If you go to the machine experiencing this error, can you run `nslookup` or a similar tool to know if it can resolve DNS entries correctly?

my machine cannot resolve those dns only the default non regional endpoint

**Comment by oscarcabrero** [comment]
it works fine now, i think it was a permissions issue. but throws a different error when it attempts to fallback to a regional endpoint. which our account does not have for some reason? do you know if this can be a problem moving forward?

**Comment by j82w** [comment]
The first issue is in the [GlobalEndpointManager](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/dc4cc731cd63437bdc1c1641cfe1fd90fa651b31/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L312). It only considers a 401 not authorized as a not retriable and it should also consider 403. It should just return the first exception which would clearly state it is a permission issue. I'll work on a fix for this. This won't be an issue if you have permissions now.

The secondary region returning the the `remote name could not be resolved: 'myaccount-westus.documents.azure.com'` points to it not existing yet. Is it possible this was a new region that was still in the process of being deployed as it takes a while for the process to complete? That would explain why the name could not be resolved.

**Comment by oscarcabrero** [comment]
@j

> The first issue is in the [GlobalEndpointManager](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/dc4cc731cd63437bdc1c1641cfe1fd90fa651b31/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L312). It only considers a 401 not authorized as a non-retriable exception and it should also consider 403. It should just return the first exception which would clearly state it is a permission issue. I'll work on a fix for this. This won't be an issue if you have permissions now.
> 
> The secondary region returning the the `remote name could not be resolved: 'myaccount-westus.documents.azure.com'` points to it not existing yet. Is it possible this was a new region that was still in the process of being deployed as it takes a while for the process to complete? That would explain why the name could not be resolved.

this account was created around 5 years ago. it is possible that the regional endpoints were never created? i just checked prod and neither of them resolve.

**Comment by j82w** [comment]
Can you provide the full exception message? The regional endpoints should exists as long as the account is on that region. I will have to test accessing the secondary region without the correct permissions to see if it reproduces.
