### ISSUE TITLE
Exception with BadRequest response thrown on App Service when performing query with CONTAINS

### ISSUE THREAD

**Issue by twentytwokhz** [Azure/azure-cosmos-dotnet-v3#2639]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
An exception is thrown when performing a query with the CONTAINS function.
NOTE: This works perfect locally, but once deployed it throws a **BadRequest**
Referring bug #1615 (@hora7ce, @george-ayris, @j82w )

**To Reproduce**
```csharp
var query = new QueryDefinition("SELECT * FROM c WHERE CONTAINS(c.platformId, '1', true)");
var options = new QueryRequestOptions { MaxConcurrency = -1, MaxItemCount = 25 };
var queryIterator = db.GetItemQueryIterator<T>(query, null, options);
var response = await queryIterator.ReadNextAsync(); // await causes the exception to be thrown
```

**Expected behavior**
Query should return the expected results

**Actual behavior**
Exception is thrown and a BadRequest response is returned with message
```"The CONTAINS function requires 2 argument(s)."```

**Environment summary**
SDK Version: 3.17.1 until 3.20.1 (all have the same problem)
OS Version: Windows (App Service Plan)

**Additional context**
```
Error: Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ;
Reason: (Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"errors":[{"severity":"Error","location":{"start":456,"end":494},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":498,"end":540},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":560,"end":601},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":605,"end":646},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":666,"end":704},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":708,"end":746},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":766,"end":801},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":805,"end":842},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."}]} ---> System.Runtime.InteropServices.COMException (0x800A0B00): 0x800A0B00
```

**Comment by j82w** [comment]
@timsander1 any suggestions?

**Comment by j82w** [comment]
@twentytwokhz is the app service plan in x64? If not can you try switching it to x64? Can you provide the full exception.ToString()?

**Comment by twentytwokhz** [comment]
@j82w  The app service plan does not have an architecture setting for x64/x86
The app service on the other hand has that setting available
In my particular case I tried to set it up with x64 and then tried x86 but had the same result

**Comment by j82w** [comment]
Our attempts to reproduce this have failed, and it is always working for us. 

1. Does it work if you deploy to a new app service?
2. What .NET version is your application?
3. Can you provide the full exception.ToString()?

**Comment by twentytwokhz** [comment]
1. It works **if** I deploy from **Visual Studio** to the target App Service (that was odd to find out 😕 )
2. My web app uses .NET 5.0 (as seen in the screenshot above)
3. The full exception from App Insights is below
```
Error, status code: 500. Error exception Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: (Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception. ---> Microsoft.Azure.Cosmos.Query.Core.Exceptions.ExpectedQueryPartitionProviderException: {"errors":[{"severity":"Error","location":{"start":121,"end":159},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":163,"end":205},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":229,"end":270},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":274,"end":315},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":339,"end":377},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":381,"end":419},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":443,"end":479},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":560,"end":599},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":121,"end":159},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":163,"end":205},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":229,"end":270},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":274,"end":315},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":339,"end":377},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":381,"end":419},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."},{"severity":"Error","location":{"start":443,"end":479},"code":"SC2050","message":"The CONTAINS function requires 2 argument(s)."}]}
 ---> System.Runtime.InteropServices.COMException (0x800A0B00): 0x800A0B00
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPartitionProvider.TryGetPartitionedQueryExecutionInfoInternal(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey)
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPartitionProvider.TryGetPartitionedQueryExecutionInfo(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.TryGetPartitionedQueryExecutionInfoAsync(SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.UnwrapPromise`1.TrySetFromTask(Task task, Boolean lookForOce)
   at System.Threading.Tasks.UnwrapPromise`1.ProcessInnerTask(Task task)
   at System.Threading.Tasks.UnwrapPromise`1.ProcessCompletedOuterTask(Task task)
   at System.Threading.Tasks.UnwrapPromise`1.InvokeCore(Task completingTask)
   at System.Threading.Tasks.UnwrapPromise`1.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.RunOrQueueCompletionAction(ITaskCompletionAction completionAction, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   --- End of inner exception stack trace ---
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPartitionProvider.TryGetPartitionedQueryExecutionInfo(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.TryGetPartitionedQueryExecutionInfoAsync(SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.UnwrapPromise`1.TrySetFromTask(Task task, Boolean lookForOce)
   at System.Threading.Tasks.UnwrapPromise`1.ProcessInnerTask(Task task)
   at System.Threading.Tasks.UnwrapPromise`1.ProcessCompletedOuterTask(Task task)
   at System.Threading.Tasks.UnwrapPromise`1.InvokeCore(Task completingTask)
   at System.Threading.Tasks.UnwrapPromise`1.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.RunOrQueueCompletionAction(ITaskCompletionAction completionAction, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
);
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPartitionProvider.TryGetPartitionedQueryExecutionInfo(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.TryGetPartitionedQueryExecutionInfoAsync(SqlQuerySpec sqlQuerySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected, Boolean allowNonValueAggregateQuery, Boolean hasLogicalPartitionKey, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.UnwrapPromise`1.TrySetFromTask(Task task, Boolean lookForOce)
   at System.Threading.Tasks.UnwrapPromise`1.ProcessInnerTask(Task task)
   at System.Threading.Tasks.UnwrapPromise`1.ProcessCompletedOuterTask(Task task)
   at System.Threading.Tasks.UnwrapPromise`1.InvokeCore(Task completingTask)
   at System.Threading.Tasks.UnwrapPromise`1.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.RunOrQueueCompletionAction(ITaskCompletionAction completionAction, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

--- Cosmos Diagnostics ---{"name":"Typed FeedIterator ReadNextAsync","id":"a0aa4ce3-45e5-43e9-9bdc-f21f7b0fa5e6","component":"Transport","caller info":{"member":"OperationHelperWithRootTraceAsync","file":"ClientContextCore.cs","line":219},"start time":"08:11:44:867","duration in milliseconds":808.4597,"data":{},"children":[{"name":"Create Query Pipeline","id":"d7d67ed2-0baa-46f8-b59e-c024bb3735bc","component":"Query","caller info":{"member":"TryCreateCoreContextAsync","file":"CosmosQueryExecutionContextFactory.cs","line":85},"start time":"08:11:44:919","duration in milliseconds":735.2225,"data":{},"children":[{"name":"Get Container Properties","id":"e69519b0-7400-48dd-843d-2917baedbf24","component":"Transport","caller info":{"member":"GetCachedContainerPropertiesAsync","file":"ClientContextCore.cs","line":363},"start time":"08:11:44:927","duration in milliseconds":374.5874,"data":{},"children":[{"name":"Get Collection Cache","id":"d04d6ca9-7529-4feb-a086-643d680708d0","component":"Routing","caller info":{"member":"GetCollectionCacheAsync","file":"DocumentClient.cs","line":542},"start time":"08:11:44:928","duration in milliseconds":0.9791,"data":{},"children":[{"name":"Waiting for Initialization of client to complete","id":"be7acc92-8ab3-4084-b998-10b9469fa61a","component":"Unknown","caller info":{"member":"EnsureValidClientAsync","file":"DocumentClient.cs","line":1380},"start time":"08:11:44:929","duration in milliseconds":0.0428,"data":{},"children":[]}]},{"name":"Read Collection","id":"850e216e-2773-43a1-90d6-cc26f0a86b9a","component":"Transport","caller info":{"member":"ReadCollectionAsync","file":"ClientCollectionCache.cs","line":63},"start time":"08:11:45:017","duration in milliseconds":255.6983,"data":{},"children":[]}]},{"name":"Service Interop Query Plan","id":"f4e6b749-c1db-4039-a401-cb279d63f00d","component":"Query","caller info":{"member":"GetQueryPlanWithServiceInteropAsync","file":"QueryPlanRetriever.cs","line":58},"start time":"08:11:45:312","duration in milliseconds":341.5921,"data":{},"children":[]}]},{"name":"POCO Materialization","id":"7c92665b-3cf4-44cf-95a9-4d2067d85ce5","component":"Poco","caller info":{"member":"ReadNextAsync","file":"FeedIteratorCore.cs","line":247},"start time":"08:11:45:674","duration in milliseconds":1.4955,"data":{},"children":[]}]}
```

**Comment by twentytwokhz** [comment]
Ok... mind-boggling update
I tried a few options:
1. Our self-hosted Linux agent (ubuntu-latest) - had the exception
2. Microsoft hosted Linux agent (ubuntu-latest) - had the exception
3. Microsoft hosted windows agent (windows-latest) - Surprise 🦄 🏆 !!!

It seems there is something wrong within the Linux agents - when performing builds that contain Microsoft.Azure.Cosmos references they are using an older ServiceInterop.dll

@j82w Could this be an issue on the Azure DevOps Agents team side? (not sure what's the name). Feel free to move it to the appropriate repo

**Comment by silviuniculita** [comment]
Hello, 

As a stopgap we've switched to doing on builds using Windows agents. We've also raised this issue with the Azure DevOps team. 

This ticket can be closed. 

Thank you for your support!

**Comment by twentytwokhz** [comment]
Closing as per @silviuniculita 's comment
