### ISSUE TITLE
ReadNextAsync throwing JSON Serialization error

### ISSUE THREAD

**Issue by sauravbhattacharya001** [Azure/azure-cosmos-dotnet-v3#2666]
I am getting a JsonSerlizationException on ReadNextAsync

```
{"A different value already has the Id '1'."}
{"Error reading object reference '1'. Path '[37].userType_language', line 1, position 53422."}
```

I have reproduced the error on a console application (code provided below). I think you need to ensure you have a Cosmos DB collection with >100,000 records (that is what I had on my side). Then run the following program after updating accordingly:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Azure.Identity;
using Business.CosmosDB;
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Cosmos.Linq;
using Newtonsoft.Json;

namespace ConsoleApp2
{
    public class FlattenedProduct
    {
        [JsonProperty(PropertyName = "id")]
        public string id
        {
            get;
            set;
        }
        public string userType_language { get; set; } // partition Key
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsFeatured { get; set; }

        [JsonProperty(PropertyName = "PartitionKey")]
        public string PartitionKey
        {
            get
            {
                return userType_language;
            }
        }
    }

    public class GridResults<T>
    {
        public int Total { get; set; }
        public List<T> Data { get; set; } = new List<T>();

        public long QueryDuration { get; set; }
    }
    class Program
    {
        static async Task Main(string[] args)
        {
            string endpoint = "https://xxx.documents.azure.com:443/";
            CosmosClient client = new CosmosClient(endpoint, new DefaultAzureCredential(), GetCosmosClientOptionsClientOptions());
            string databaseId = "xxx";
            var database = client.GetDatabase(databaseId);
            string collectionId = "FlattenedProduct";
            var container = database.GetContainer(collectionId);
            
            GridResults<FlattenedProduct> results = new GridResults<FlattenedProduct>();

            var requestOptions = new QueryRequestOptions();
            using (FeedIterator<FlattenedProduct> setIterator = container.GetItemLinqQueryable<FlattenedProduct>().Where(x => x.IsEnabled).ToFeedIterator<FlattenedProduct>())
            {
                Microsoft.Azure.Cosmos.FeedResponse<FlattenedProduct> items = null;
                var counter = 0;
                while (setIterator.HasMoreResults)
                {
                    try
                    {
                        items = await setIterator.ReadNextAsync();
                        foreach (var item in items)
                        {
                            results.Data.Add(item);
                        }

                        items = null;
                    }
                    catch (Exception e)
                    {
                        // exception here
                    }
                }
            }

        }

        protected static CosmosClientOptions GetCosmosClientOptionsClientOptions(int maxRetryAttemptsOnThrottledRequests = 3, int maxRetryWaitTimeInSeconds = 180)
        {
            return new CosmosClientOptions()
            {
                ConnectionMode = Microsoft.Azure.Cosmos.ConnectionMode.Direct,
                RequestTimeout = new TimeSpan(0, 1, 0),
                MaxTcpConnectionsPerEndpoint = 1000, 
                MaxRetryAttemptsOnRateLimitedRequests = maxRetryAttemptsOnThrottledRequests,
                MaxRetryWaitTimeOnRateLimitedRequests = TimeSpan.FromSeconds(maxRetryWaitTimeInSeconds),
                AllowBulkExecution = true
            };
        }
    }
}

```

**Expected behavior**
The records should have been retrieved without any issue

**Actual behavior**
A Json serialization error occurs. 

```
{"A different value already has the Id '1'."}
{"Error reading object reference '1'. Path '[37].userType_language', line 1, position 53422."}
```

**Environment summary**
SDK Version: 3.20.1
OS Version: Windows

**Additional context**
Here is the stack trace:
```
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.AddReference(JsonReader reader, String id, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Microsoft.Azure.Cosmos.CosmosJsonDotNetSerializer.FromStream[T](Stream stream)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.FromStream[T](Stream stream)
   at Microsoft.Azure.Cosmos.CosmosSerializerCore.FromFeedStream[T](Stream stream)
   at Microsoft.Azure.Cosmos.Serializer.CosmosElementSerializer.GetResourcesHelper[T](IReadOnlyList`1 cosmosElements, CosmosSerializerCore serializerCore, CosmosSerializationFormatOptions cosmosSerializationOptions)
   at Microsoft.Azure.Cosmos.Serializer.CosmosElementSerializer.GetResources[T](IReadOnlyList`1 cosmosArray, CosmosSerializerCore serializerCore)
   at Microsoft.Azure.Cosmos.QueryResponse`1..ctor(HttpStatusCode httpStatusCode, IReadOnlyList`1 cosmosElements, CosmosQueryResponseMessageHeaders responseMessageHeaders, CosmosDiagnostics diagnostics, CosmosSerializerCore serializerCore, CosmosSerializationFormatOptions serializationOptions)
   at Microsoft.Azure.Cosmos.QueryResponse`1.CreateResponse[TInput](QueryResponse cosmosQueryResponse, CosmosSerializerCore serializerCore)
   at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.CreateQueryFeedResponseHelper[T](ResponseMessage cosmosResponseMessage)
   at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.CreateQueryFeedUserTypeResponse[T](ResponseMessage responseMessage)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.<ReadNextAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ClientContextCore.<RunWithDiagnosticsHelperAsync>d__38`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ClientContextCore.<OperationHelperWithRootTraceAsync>d__29`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp2.Program.<Main>d__0.MoveNext() in C:\Users\...\ConsoleApp2\ConsoleApp2\Program.cs:line 65
```

**Comment by j82w** [comment]
There are few things I want to point out. 
1. Why is bulk enabled? How many operations are you planning to do? https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/#what-exactly-is-bulk 
2. Make sure the client is a singleton for the actual application. I'm assuming this is just to provide a repro, but wanted to call it out as it is a common mistake.
3. Is there a reason you set the `RequestTimeout` to 1 minute? https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-dot-net-sdk-request-timeout#requesttimeout
4. It's recommended to pass the partition key in the query request options. Cross partition queries will become slower as the size of the container is increased. The query will have visit more partitions which will increase it's e2e latency. 

I was not able to reproduce the issue. My current theory is there is a JSON object that is not a FlattenedProduct. Can you try do the following? It's not performant but it will let you see what JSON is failing to be converted to the FlattenedProduct
```c#
static async Task Main(string[] args)
        {
            CosmosClient client = new CosmosClient(
                "https://localhost:8081",
                "",
                GetCosmosClientOptionsClientOptions());
            string databaseId = "testdb";
            Database database = await client.CreateDatabaseIfNotExistsAsync(databaseId);
            string collectionId = "FlattenedProduct";
            Container container = await database.CreateContainerIfNotExistsAsync(
                collectionId,
                "/PartitionKey");

            GridResults<FlattenedProduct> results = new GridResults<FlattenedProduct>();

            using (FeedIterator<JObject> setIterator = container.GetItemQueryIterator<JObject>("select * from T where T.IsEnabled"))
            {
                while (setIterator.HasMoreResults)
                {
                    Microsoft.Azure.Cosmos.FeedResponse<JObject> items = await setIterator.ReadNextAsync();
                    foreach (var item in items)
                    {
                        try
                        {
                            results.Data.Add(item.ToObject<FlattenedProduct>());
                        }
                        catch (Exception e)
                        {
                            Console.WriteLine($"JObject failed to convert. {item} Exception {e}");
                            Console.Read();
                        }
                    }
                }
            }

            Console.WriteLine($"Success: {results.Data.Count}");
            Console.Read();
        }
```

**Comment by sauravbhattacharya001** [comment]
The issue is good now as in I have a work around,  but I am curious why this only happens when I use cosmos client and get GetItemQueryIterator. This didn't used to be an issue with Document Client and CreateDocumentQuery.

**Comment by j82w** [comment]
CosmosClient always converts the object to the specified type so there is no ambiguity on what the response type is. DocumentClient basically default to a JObject. Did you specify the T for DocumentClient query?

**Comment by sauravbhattacharya001** [comment]
Yes, did specify T for DocumentClient query?. The data is same, but the deserialization issue didn't happen on document client but happens with cosmos client unless I specific the metadata property handling to ignore.

**Comment by sauravbhattacharya001** [comment]
This is the previous version that doesnt throw any error. 
 
```
                DocumentClient client = new DocumentClient(uri, primaryKey, GetConnectionPolicy());
                GridResults<T> results = new GridResults<T>();
                FeedOptions feedOptions = new FeedOptions() { MaxItemCount = -1 };
                if (partitionKey != null)
                {
                    feedOptions.PartitionKey = new PartitionKey(partitionKey);
                }
                else
                {
                    feedOptions.EnableCrossPartitionQuery = true;
                }

                IDocumentQuery<T> dataQuery = client.CreateDocumentQuery<T>(UriFactory.CreateDocumentCollectionUri(databaseId, collectionId), feedOptions)
                    .ApplyFilter<T>(dbFilter)
                    .AsDocumentQuery<T>();                

                results.Total = client.CreateDocumentQuery<T>(UriFactory.CreateDocumentCollectionUri(databaseId, collectionId), feedOptions)
                    .FilteredCount<T>(dbFilter);

                while (dataQuery.HasMoreResults)
                {
                    FeedResponse<T> feedResponse = await dataQuery.ExecuteNextAsync<T>();
                    if (feedResponse != null)
                    {
                        results.Data.AddRange(feedResponse);
                    }
                }
```
Connection policy is created as follows:
```
            ConnectionPolicy cp = new ConnectionPolicy();
            cp.ConnectionMode = ConnectionMode.Direct;
            cp.ConnectionProtocol = Protocol.Tcp;
            cp.RequestTimeout = new TimeSpan(0, 1, 0);
            cp.MaxConnectionLimit = 1000;
            cp.RetryOptions = new RetryOptions
            {
                MaxRetryAttemptsOnThrottledRequests = maxRetryAttemptsOnThrottledRequests,
                MaxRetryWaitTimeInSeconds = maxRetryWaitTimeInSeconds
            };
```

There are no JsonSerializerSettings configured, so maybe the property is off by default?
