### ISSUE TITLE
MSI AuthenticationFailedException when deploying to Azure

### ISSUE THREAD

**Issue by sauravbhattacharya001** [Azure/azure-cosmos-dotnet-v3#2671]
I am getting the following RequestFailedException error for an MSI based app only when deployed to Azure. So far I don't have a repro. I am working on it, but am I doing anything obviously wrong from the error?

```
Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Headers:
Content-Length: 133
Date: Mon, 16 Aug 2021 22:04:55 GMT
---> Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Headers:
Content-Length: 133
Date: Mon, 16 Aug 2021 22:04:55 GMT

at Azure.Identity.ManagedIdentitySource.<HandleResponseAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Azure.Identity.ManagedIdentitySource.<AuthenticateAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Azure.Identity.ManagedIdentityClient.<AuthenticateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Azure.Identity.ManagedIdentityCredential.<GetTokenImplAsync>d__9.MoveNext()
--- End of inner exception stack trace ---
at Microsoft.Azure.Cosmos.TokenCredentialCache.<RefreshCachedTokenWithRetryHelperAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Cosmos.TokenCredentialCache.<GetTokenAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Cosmos.AuthorizationTokenProviderTokenCredential.<AddAuthorizationHeaderAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Cosmos.GatewayAccountReader.<GetDatabaseAccountAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.GetAccountPropertiesHelper.<GetAndUpdateAccountPropertiesAsync>d__13.MoveNext()
```

This is the init code:

        CosmosClient client = new CosmosClient(AppSettings.Get.CosmosDB_Endpoint.Value, new DefaultAzureCredential(), GetCosmosClientOptions());

        protected static CosmosClientOptions GetCosmosClientOptions(int maxRetryAttemptsOnThrottledRequests = 3, int maxRetryWaitTimeInSeconds = 180)
        {
            return new CosmosClientOptions()
            {
                ConnectionMode = Microsoft.Azure.Cosmos.ConnectionMode.Direct,
                RequestTimeout = new TimeSpan(0, 1, 0), 
                MaxTcpConnectionsPerEndpoint = 1000, 
                MaxRetryAttemptsOnRateLimitedRequests = maxRetryAttemptsOnThrottledRequests,
                MaxRetryWaitTimeOnRateLimitedRequests = TimeSpan.FromSeconds(maxRetryWaitTimeInSeconds),
                ApplicationRegion = LocationNames.EastUS,
                AllowBulkExecution = true,
                Serializer = new CosmosJsonNetSerializer(new JsonSerializerSettings()
                {
                    MetadataPropertyHandling = MetadataPropertyHandling.Ignore // To ignore $id values in the data.
                })
            };
        }

**Environment summary**
SDK Version: 3.20.1
OS Version Windows

**Comment by j82w** [comment]
This doesn't have anything to do with Cosmos DB. Please open an issue against the following repro which owns the Azure.Identity.AuthenticationFailedException
https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity

**Comment by sauravbhattacharya001** [comment]
FYI for anyone that has same issue: set the `AZURE_CLIENT_ID` environment variable on azure app service.
