### ISSUE TITLE
AggergateException with DocumentClientException on auth failure

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2680]
If the SDK initialization fails it seems like it can throw an aggregate exception. The aggregate exception contains a DocumentClientException and is not properly converted to a CosmosException.  This needs to be validated and is based on a custom reported issue where the Cosmos DB key was rotated.

The expected behavior is the SDK should throw a CosmosException with the correct status code instead of the internal DocumentClientException.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/64cbee30073c4ff3983b320e16909656261d1aa2/Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs#L423

Exception:
"outerAssembly": Microsoft.Azure.Documents.DocumentClientException,
"outerMessage": The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'get

Example of API call logic:
```c#
try
{
    return await this.container.UpsertItemAsync<T>(
                item,
                new PartitionKey(partitionKeyValue),
                requestOptions,
                cancellationToken: cancelToken);
}
catch (CosmosException ex) when (ex.StatusCode == System.Net.HttpStatusCode.Unauthorized)
{
    this.FallBackToSecondaryKey();
    throw;
}
```

"stackTrace":    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Cosmos.ContainerCore.<>c.<GetPartitionKeyDefinitionAsync>b__42_0(Task`1 containerPropertiesTask)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Cosmos.ContainerCore.ExtractPartitionKeyAndProcessItemStreamAsync[T](Nullable`1 partitionKey, String itemId, T item, OperationType operationType, ItemRequestOptions requestOptions, CosmosDiagnosticsContext diagnosticsContext, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ContainerCore.UpsertItemAsync[T](CosmosDiagnosticsContext diagnosticsContext, T item, Nullable`1 partitionKey, ItemRequestOptions requestOptions, CancellationToken cancellationToken)

**Comment by kirankumarkolli** [comment]
@j82w is it still a gap?

**Comment by NaluTripician** [comment]
In the current version of the SDK, when rotating the key while the application is running then doing an `UpsertItem` call like the one mentioned above the SDK correctly throws a `CosmosException` with a 401 Unauthorized error code. 

If you are still facing this problem, please reopen this issue.
