### ISSUE TITLE
Cosmos.Samples.Usage solution does not build under VS2019

### ISSUE THREAD

**Issue by samaea** [Azure/azure-cosmos-dotnet-v3#2699]
Describe the bug
Cosmos.Samples.Usage solution does not build under VS2019.

To Reproduce
Git cloned the repo into my Downloads folder. Locate and load azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos.Samples\UsageCosmos.Samples.Usage .sln in VS2019. Set the UserManagement project as the startup project. Build it.

Expected behavior
The solution should build.

Actual behavior
Warnings and compile errors.

**Environment summary**
SDK Version: Same SDK offered in the sample.
OS Version (e.g. Windows, Linux, MacOSX): Windows.

**Additional context**
```
Build started...
1>------ Build started: Project: AzureFunctions, Configuration: Debug Any CPU ------
2>------ Build started: Project: UserManagement, Configuration: Debug Any CPU ------
1>AzureFunctions -> C:\Users\hussel\Downloads\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos.Samples\Usage\AzureFunctions\bin\Debug\netcoreapp3.1\bin\Cosmos.Samples.AzureFunctions.dll
2>UserManagement -> C:\Users\hussel\Downloads\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos.Samples\Usage\UserManagement\bin\Debug\netcoreapp3.1\UserManagement.dll
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : File name: 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes()
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryRun()
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Error generating functions metadata
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :
1>C:\Users\hussel\.nuget\packages\microsoft.net.sdk.functions\1.0.27\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Metadata generation failed.
1>Done building project "AzureFunctions.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 20 up-to-date, 0 skipped ==========
```

**Comment by ealsur** [comment]
@samaea Thanks for the report, it looks like the Functions project stopped building at some point in time but because the CI gates were not verifying the build, we did not catch it. PR with the fix is out. You can incorporate that CSPROJ fix to mitigate your problem.
