### ISSUE TITLE
Empty property name causes parsing exception on Linux

### ISSUE THREAD

**Issue by AndriySvyryd** [Azure/azure-cosmos-dotnet-v3#2879]
`<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.23.0" />`

```C#
using Microsoft.Azure.Cosmos;

var client = new CosmosClient("");

await client.CreateDatabaseIfNotExistsAsync("WebTests");

var database = client.GetDatabase("WebTests");

await database.CreateContainerIfNotExistsAsync(
    new ContainerProperties("AppDbContext", "/pk")
    {
        PartitionKeyDefinitionVersion = PartitionKeyDefinitionVersion.V2
    });

var container = database.GetContainer("AppDbContext");

var query = container.GetItemQueryIterator<string>(@"
SELECT VALUE { """" : c}
      FROM root c
      OFFSET 0 LIMIT 1",
      requestOptions: new QueryRequestOptions { PartitionKey = new PartitionKey("test") });

while (query.HasMoreResults)
{
    var result = await query.ReadNextAsync();
    Console.WriteLine(result.FirstOrDefault());
}
```

> Unhandled exception. System.ArgumentException: value must not be null, empty, or whitespace.
   at Microsoft.Azure.Cosmos.SqlObjects.SqlPropertyName..ctor(String value)
   at Microsoft.Azure.Cosmos.SqlObjects.SqlPropertyName.Create(String value)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitObject_property(Object_propertyContext context)
   at sqlParser.Object_propertyContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitObjectCreateScalarExpression(ObjectCreateScalarExpressionContext context)
   at sqlParser.ObjectCreateScalarExpressionContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitUnary_scalar_expression(Unary_scalar_expressionContext context)
   at sqlParser.Unary_scalar_expressionContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitBinary_scalar_expression(Binary_scalar_expressionContext context)
   at sqlParser.Binary_scalar_expressionContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitLogical_scalar_expression(Logical_scalar_expressionContext context)
   at sqlParser.Logical_scalar_expressionContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at sqlBaseVisitor`1.VisitLogicalScalarExpression(LogicalScalarExpressionContext context)
   at sqlParser.LogicalScalarExpressionContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitSelect_value_spec(Select_value_specContext context)
   at sqlParser.Select_value_specContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at sqlBaseVisitor`1.VisitSelection(SelectionContext context)
   at sqlParser.SelectionContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitSelect_clause(Select_clauseContext context)
   at sqlParser.Select_clauseContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitSql_query(Sql_queryContext context)
   at sqlParser.Sql_queryContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitProgram(ProgramContext context)
   at sqlParser.ProgramContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.SqlQueryParser.Monadic.Parse(String text)
   at Microsoft.Azure.Cosmos.Query.Core.Parser.SqlQueryParser.TryParse(String text, SqlQuery& sqlQuery)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CosmosQueryExecutionContextFactory.TryCreateCoreContextAsync(DocumentContainer documentContainer, CosmosQueryContext cosmosQueryContext, InputParameters inputParameters, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.AsyncLazy`1.GetValueAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.LazyQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.NameCacheStaleRetryQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CatchAllQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.ReadNextAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.ReadNextAsync(ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](ITrace trace, Func`2 task)
   at Microsoft.Azure.Cosmos.ClientContextCore.OperationHelperWithRootTraceAsync[TResult](String operationName, RequestOptions requestOptions, Func`2 task, TraceComponent traceComponent, TraceLevel traceLevel)
   at Program.<Main>$(String[] args) in /mnt/c/Users/tanta/source/repos/CosmosIssue/CosmosIssue/Program.cs:line 25
   at Program.<Main>(String[] args)

**Comment by XzaR90** [comment]
Any status on this one or workaround with ef core? We cannot deploy .NET 6 to Azure App Service (Linux)

**Comment by basilfx** [comment]
I'm also able to reproduce this issue on macOS 12.2.1 with .NET 6.0.102 and Microsoft.Azure.Cosmos 3.26.1.

**Comment by basilfx** [comment]
My current work-around is building a preview version of 3.26.1 that does not include [this](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/releases/3.26.1/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs#L166) if-statement.

**Comment by vyarymovych** [comment]
@basilfx Our dev team has the same issue when reloading entity with `entry.GetDatabaseValues()` method (it's used to get the latest version of entity from database in order to handle `DbUpdateConcurrencyException`). 
Looks like this method sends exactly the same sql query as in the example @AndriySvyryd has posted here and it fails on Linux service plans with the same error.
Have you found a different solution or still using 3.26.1 preview version?

**Comment by basilfx** [comment]
@vyarymovych I applied the same patch on the latest version without problems.
