### ISSUE TITLE
Query test "UPPER" failing Expected:<"µ">. Actual:<"Μ">.

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#3005]
The Upper test started to fail in the gates and locally. It started to fail on between 1/26 and 1/27. There have been no changes to the files. This seems like breaking change caused by a windows upgrade. The .NET version of the gates is the same between both runs.

Switching to .NET core 3.1 causes the test to pass. It fails now in both .NET 5 and .NET 6.

It also reproduces with the following code:
```c#
string test = new string("\u00B5");
string toUpper = test.ToUpper();
string toUpperInvariant = test.ToUpper(CultureInfo.InvariantCulture);
string t2 = test.ToUpperInvariant();
Console.WriteLine($"{test}, {toUpper} {toUpperInvariant} {t2}");
```

The test is being ignored to unblock the gates. This issue is to track if the query team needs to follow up with .NET team on why the behavior changed as it can impact some queries.

Passed Wed at 7:41 AM:
https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=39244&view=logs&j=aa2fd561-a338-5537-45ee-49ae22aea958

Failed Thu at 2:55 AM:
https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=39261&view=logs&j=39a3bec8-d1f6-51ce-3606-c349921adf01&t=1f526921-4d85-5bc3-8272-9238eef9d23a

  Failed UPPER [7 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<"µ">. Actual:<"Μ">. 
  Stack Trace:
     at Microsoft.Azure.Cosmos.Tests.Query.OfflineEngineTests.BuiltinFunctionEvaluatorTests.AssertEvaluation(CosmosElement expected, SqlScalarExpression sqlScalarExpression, CosmosElement document) in D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.Tests\Query\OfflineEngineTests\BuiltinFunctionEvaluatorTests.cs:line 432
   at Microsoft.Azure.Cosmos.Tests.Query.OfflineEngineTests.BuiltinFunctionEvaluatorTests.UPPER() in D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.Tests\Query\OfflineEngineTests\BuiltinFunctionEvaluatorTests.cs:line 417

**Comment by neildsh** [comment]
Offline Engine is currently unused. We can audit all offline engine tests if we decide to use it at some point. Closing this issue out to reduce noise.
