### ISSUE TITLE
Unable to use other than default stream encoding in custom json serializer

### ISSUE THREAD

**Issue by perkastman** [Azure/azure-cosmos-dotnet-v3#301]
**Describe the bug**
When having a custom json serializer using some other encoding than Encoding.Default the payload gets corrupt. Changing Encoding.UTF8 to Encoding.Default will make the program work, but will not store the regional characters correctly encoded in Cosmos. 

**To Reproduce**

Given a container with id as partition key. 

```
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Azure.Cosmos;
using Newtonsoft.Json;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            MainAsync().Wait();
        }

        static async Task MainAsync()
        {
            var accountEndPoint = "ENTER_ENDPOINT_HERE";
            var accountKey = "ENTER_KEY_HERE";

            var cosmosClientBuilder = new CosmosClientBuilder(accountEndPoint, accountKey);

            cosmosClientBuilder.UseCustomJsonSerializer(new CustomSerializer());

            using (var cosmosClient = cosmosClientBuilder.Build())
            {
                var item = new Item { Name = "ÅÅÅÄÄÄÖÖÖ" };

                var container = cosmosClient.Databases["ENTER_DATABASE_HERE"].Containers["ENTER_CONTAINER_HERE"];

                var createdEntity = await container.Items.CreateItemAsync(item.Id.ToString(), item);
            }
        }

    }

    public class Item
    {
        public Item()
        {
            Id = Guid.NewGuid();
        }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        public string Name { get; set; }
    }

    public class CustomSerializer : CosmosJsonSerializer
    {
        private static readonly JsonSerializer serializer = JsonSerializer.Create();

        public override T FromStream<T>(Stream stream)
        {
            using (stream)
            {
                if (typeof(Stream).IsAssignableFrom(typeof(T)))
                {
                    return (T)(object)stream;
                }

                using (var streamReader = new StreamReader(stream))
                using (var jsonTextReader = new JsonTextReader(streamReader))
                {
                    return serializer.Deserialize<T>(jsonTextReader);
                }
            }
        }

        public override Stream ToStream<T>(T input)
        {
            var streamPayload = new MemoryStream();

            using (var streamWriter =
                new StreamWriter(streamPayload, encoding: Encoding.UTF8, bufferSize: 1024, leaveOpen: true))
            using (var writer = new JsonTextWriter(streamWriter))
            {
                writer.Formatting = Newtonsoft.Json.Formatting.None;
                serializer.Serialize(writer, input);
                writer.Flush();
                streamWriter.Flush();
            }

            streamPayload.Position = 0;
            return streamPayload;
        }
    }

}

```

**Expected behavior**
That an Item document should be crated.

**Actual behavior**
CosmosException: Response status code does not indicate success: 400 Substatus: 0 Reason: (Message: {"Errors":["The request payload is invalid. Ensure to provide a valid request payload."]}

**Environment summary**
SDK Version:   Microsoft.Azure.Cosmos version="3.0.0.10-preview" targetFramework="net472"
OS Version: Windows 10

**Additional context**

   at Microsoft.Azure.Cosmos.CosmosResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.ToObjectInternal[T](CosmosResponseMessage cosmosResponseMessage)
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.<CreateItemResponse>b__6_0[T](CosmosResponseMessage cosmosResponseMessage)
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.<>c__DisplayClass12_0`1.<MessageHelper>b__0(Task`1 action)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp2.Program.<MainAsync>d__1.MoveNext() in C:\Users\******\source\repos\ConsoleApp1\ConsoleApp2\Program.cs:line 32

**Comment by perkastman** [comment]
https://blogs.msdn.microsoft.com/shawnste/2005/03/15/dont-use-encoding-default/
