### ISSUE TITLE
Container.DeleteItemAsync() throws an exception if the EnableContentResponseOnWrite option is true

### ISSUE THREAD

**Issue by colgreen** [Azure/azure-cosmos-dotnet-v3#3011]
The method  DeleteItemAsync has a return type of  `Task<ItemResponse<T>>` where T is the item type. However, there is no scenario where the item is returned. Either:

 * EnableContentResponseOnWrite is false, in which case ItemResponse.Resource is null,
 or
 *  EnableContentResponseOnWrite is true, in which case DeleteItemAsync throws an exception.

If this is a bug then it would be good to get it fixed.
If this is expected behaviour then it would be good to explain this in the documentation for DeleteItemAsync(). 

If this is expected behaviour then ideally a different return type would be preferred that didn't have a slot for the Resource object, but (a) that would require a new return type specific to just deletes calls, and (b) it would be a pretty big breaking change to the API. So I think a documentation update would be good.

Demo app to recreate the exception...
```
using Microsoft.Azure.Cosmos;
using System.Net;

namespace TestEnableResponseOnWrite
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var client = new CosmosClient("AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==");
            var databaseResponse = await client.CreateDatabaseIfNotExistsAsync("TestEnableResponseOnWrite");
            if (HttpStatusCode.Created != databaseResponse.StatusCode
                && HttpStatusCode.OK != databaseResponse.StatusCode)
            {
                throw new Exception("Didn't create database");
            }
            var database = databaseResponse.Database;
            var containerResponse = await database.CreateContainerIfNotExistsAsync("TheContainer", "/description");
            if (HttpStatusCode.Created != containerResponse.StatusCode
                && HttpStatusCode.OK != containerResponse.StatusCode)
            {
                throw new Exception("Didn't create container");
            }
            var container = containerResponse.Container;
            await TestTrue(container);
        }

        private static async Task TestTrue(Container container)
        {
            ItemRequestOptions requestOptions = new ItemRequestOptions() { EnableContentResponseOnWrite = true };
            var item = new ToDoActivity { description = "foo" };
            ItemResponse<ToDoActivity> itemResponse = await container.CreateItemAsync(item, new PartitionKey(item.description), requestOptions);
            if (HttpStatusCode.Created != itemResponse.StatusCode)
            {
                throw new Exception("Didn't create item");
            }
            if (itemResponse.Resource is null)
            {
                Console.WriteLine("Test (EnableContentResponseOnWrite = true) failed");
            }
            else
            {
                Console.WriteLine("Test (EnableContentResponseOnWrite = true) passed");
            }

            // Delete the newly created item.
            // This throws an exception.
            ItemResponse<ToDoActivity> itemResponse2 = await container.DeleteItemAsync<ToDoActivity>(item.id, new PartitionKey(item.description), requestOptions);
        }
    }

    public class ToDoActivity
    {
        public string id => Guid.NewGuid().ToString();
        public string description { get; set; }
    }
}
```

Exception details:

```
Microsoft.Azure.Cosmos.CosmosException
  HResult=0x80131500
  Message=Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: c7ebc245-29bd-45de-bda1-a94f1b93eb71; Reason: (
Errors : [
  "Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found"
]
);
  Source=Microsoft.Azure.Cosmos.Client
  StackTrace:
   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.ProcessMessage[T](ResponseMessage responseMessage, Func`2 createResponse)
   at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.CreateItemResponse[T](ResponseMessage responseMessage)
   at Microsoft.Azure.Cosmos.ContainerCore.<DeleteItemAsync>d__62`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Cosmos.ClientContextCore.<RunWithDiagnosticsHelperAsync>d__39`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Cosmos.ClientContextCore.<OperationHelperWithRootTraceAsync>d__30`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestEnableResponseOnWrite.Program.<TestTrue>d__1.MoveNext() in C:\Users\colin\source\repos\CosmosTest\CosmosTest\Program.cs:line 48
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TestEnableResponseOnWrite.Program.<Main>d__0.MoveNext() in C:\Users\colin\source\repos\CosmosTest\CosmosTest\Program.cs:line 25

  This exception was originally thrown at this call stack:
    Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
    Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.ProcessMessage<T>(Microsoft.Azure.Cosmos.ResponseMessage, System.Func<Microsoft.Azure.Cosmos.ResponseMessage, T>)
    Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.CreateItemResponse<T>(Microsoft.Azure.Cosmos.ResponseMessage)
    Microsoft.Azure.Cosmos.ContainerCore.DeleteItemAsync<T>(string, Microsoft.Azure.Cosmos.PartitionKey, Microsoft.Azure.Cosmos.Tracing.ITrace, Microsoft.Azure.Cosmos.ItemRequestOptions, System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
    Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync<TResult>(Microsoft.Azure.Cosmos.Tracing.ITrace, System.Func<Microsoft.Azure.Cosmos.Tracing.ITrace, System.Threading.Tasks.Task<TResult>>)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...
    [Call Stack Truncated]
```

Also see:
https://stackoverflow.com/questions/67878798/deleteitemasync-is-not-returned-the-item-being-deleted

---

To add some context regarding why we might want the deleted resource. We have some potential scenarios where some kind of high level orchestration occurs across two or more services, and one example of that might be performing an eventually consistent delete of resources in different services that are logically linked in some way. What you might want to do is delete a resource, but retrieve it so that you have the option of re-creating it if we wish to roll back the wider transaction/orchestration. It's probably a rare scenario, but that was why we had an abstraction laye rover DeleteItemAsync that optionally returned the deleted item. Now we would have to perform a separate GET, then a DELETE, and that introduces a race condition (i.e. someone else could have update the resource between the GET and the DELETE).

**Comment by ealsur** [comment]
The exception you are sharing is a 404, it means the resource trying to be deleted does not exist (or one of the parents).

The problem is your code:

```
 public class ToDoActivity
    {
        public string id => Guid.NewGuid().ToString();
        public string description { get; set; }
    }
``` 

It generates a new Guid everytime you call the getter on the `id` property, so the line: 

```
ItemResponse<ToDoActivity> itemResponse2 = await container.DeleteItemAsync<ToDoActivity>(item.id, new PartitionKey(item.description), requestOptions);
```

Is not using the same `id` as the Create call.

**Comment by ealsur** [comment]
Change it to:

```
public class ToDoActivity
{
    public string id { get; set; } = Guid.NewGuid().ToString();
    public string description { get; set; }
}
``` 

And it would work as you expect it.

**Comment by colgreen** [comment]
Thanks @ealsur . In which case, the remaining problem is that ItemResponse.Resource is null even when EnableContentResponseOnWrite = true.

**Comment by ealsur** [comment]
That is by design. The REST API documentation for a Delete document operation does not include the body. https://docs.microsoft.com/en-us/rest/api/cosmos-db/delete-a-document#body

**Comment by colgreen** [comment]
hmm, ok. However, the CosmosClient API docs make no mention of this. See: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.deleteitemasync   

but I see your point that the underlying Cosmos API doesn't support returning the resource

**Comment by ealsur** [comment]
We could certainly add a remark on the C# API surface, the operations tend to map to the REST API.

**Comment by colgreen** [comment]
I will raise a new issue against the doc page. Thanks for your help.

**Comment by ealsur** [comment]
This repo owns the docs too, they are auto-generated off the code: 

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs#L822-L847
