### ISSUE TITLE
Exception thrown when application name contains certain characters

### ISSUE THREAD

**Issue by anstein-msft** [Azure/azure-cosmos-dotnet-v3#3040]
Cosmos .net package 3.24.0

When using the following code

`   
CosmosClient cClient = new CosmosClient(CosmosEndpointUri, CosmosPrimaryKey, new CosmosClientOptions()
                                        {
                                            ApplicationName = MethodBase.GetCurrentMethod().DeclaringType.Name
                                        });
`

And the method "MethodBase.GetCurrentMethod().Name" is returning the following string:

`<Run>d__9`

There is a generic exception thrown...

![image](https://user-images.githubusercontent.com/72947641/154751138-e2f53995-8806-4e64-8eea-53be1a333b78.png)

_System.FormatException: The format of value '6.0.0-rc.2.21480.5|N|<Run>d__9' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at Microsoft.Azure.Documents.HttpClientExtension.AddUserAgentHeader(HttpClient httpClient, UserAgentContainer userAgent)
   at Microsoft.Azure.Cosmos.CosmosHttpClientCore.CreateHelper(HttpClient httpClient, HttpMessageHandler httpMessageHandler, TimeSpan requestTimeout, UserAgentContainer userAgentContainer, ApiType apiType, ICommunicationEventSource eventSource)
   at Microsoft.Azure.Cosmos.CosmosHttpClientCore.CreateWithConnectionPolicy(ApiType apiType, ICommunicationEventSource eventSource, ConnectionPolicy connectionPolicy, HttpMessageHandler httpMessageHandler, EventHandler`1 sendingRequestEventArgs, EventHandler`1 receivedResponseEventArgs)
   at Microsoft.Azure.Cosmos.DocumentClient.Initialize(Uri serviceEndpoint, ConnectionPolicy connectionPolicy, Nullable`1 desiredConsistencyLevel, HttpMessageHandler handler, ISessionContainer sessionContainer, Nullable`1 enableCpuMonitor, IStoreClientFactory storeClientFactory, TokenCredential tokenCredential)
   at Microsoft.Azure.Cosmos.DocumentClient..ctor(Uri serviceEndpoint, AuthorizationTokenProvider cosmosAuthorization, EventHandler`1 sendingRequestEventArgs, ConnectionPolicy connectionPolicy, Nullable`1 desiredConsistencyLevel, JsonSerializerSettings serializerSettings, ApiType apitype, EventHandler`1 receivedResponseEventArgs, HttpMessageHandler handler, ISessionContainer sessionContainer, Nullable`1 enableCpuMonitor, Func`2 transportClientHandlerFactory, IStoreClientFactory storeClientFactory)
   at Microsoft.Azure.Cosmos.ClientContextCore.Create(CosmosClient cosmosClient, CosmosClientOptions clientOptions)
   at Microsoft.Azure.Cosmos.CosmosClient..ctor(String accountEndpoint, AuthorizationTokenProvider authorizationTokenProvider, CosmosClientOptions clientOptions)
   at Microsoft.Azure.Cosmos.CosmosClient..ctor(String accountEndpoint, String authKeyOrResourceToken, CosmosClientOptions clientOptions)
   at D365SDKAccess.ParallelBatchExecuteMultipleEntityInsert.Run(HttpRequestMessage req, ILogger log) in C:\src\DOD Projects\ATEC\Azure Functions\D365SDKAccess\ParallelBatchExecuteMultipleEntityInsert.cs:line 77_

I had to scratch my head for too long to figure out what the issue was. Ideally, a CosmosException would be thrown instead that stated that the application name was invalid (or the code handling the HTTP requests would handle this edge case).

**Comment by ealsur** [comment]
The ApplicationName value is used on the Headers. The validation that you are seeing is not being done by the SDK:

```
System.FormatException: The format of value '6.0.0-rc.2.21480.5|N|d__9' is invalid.
at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
```

It means the value you are passing is invalid as an HTTP header and it's being validated by the framework (`System.Net.Http`).

**Comment by anstein-msft** [comment]
OK, but validation on the application name can be done before creating an HTTP request. The point is to make this simpler for developers to understand what the issue is.

**Comment by anstein-msft** [comment]
OK, I understand now.

What about a try catch around each header.Add() call (or around all of the calls collectively), and in the catch, return friendly string "Adding header "X" <example: ApplicationName" failed. Even that would have be better than current state.

In this case, you are not owning the validation but are helping the developer isolate where the issue is to fix it.

**Comment by anstein-msft** [comment]
Something like below.

Admittedly, looking at the code, the only value I can see that could cause this issue is the ApplicationName, but this code accounts for future uses of properties in the userAgentContainer, in the AddUserAgentHeader method. 

![image](https://user-images.githubusercontent.com/72947641/155215319-1d76e1b0-2a98-4e8f-8b8d-b661110202de.png)
