### ISSUE TITLE
Please support upgrading from Manual to Autoscale throughput via .NET SDK

### ISSUE THREAD

**Issue by hkuadithya** [Azure/azure-cosmos-dotnet-v3#3147]
To be very honest, I've found working with CosmosDB SDK very frustrating. I speak as a Microsoft employee working on one of the Azure services. 

It looks like the SDK supports only a subset of features supported on Portal. I was trying to upgrade the throughput to Autoscale for our prod CosmosDB containers using .NET SDK. It looks like changing the throughput type to autoscale is only supported in Portal, CLI or powershell.

### Tried this code for updating throughput
```
var maxAutoscaleThrougput = 5000;
await container.ReplaceThroughputAsync(ThroughputProperties.CreateAutoscaleThroughput(maxAutoscaleThroughput));
```

### This will throw this exception
```
Microsoft.Azure.Cosmos.CosmosException
  HResult=0x80131500
  Message=Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: b6ac2d8b-6c06-4592-a541-b86fe9197633; 
Reason: (Message: {"Errors":["x-ms-cosmos-migrate-offer-to-autopilot must be supplied and offercontent must not contain autopilotSettings for migration from manual throughput to autoscale."]}
 ResourceType: Offer, OperationType: PreReplaceValidation
, SDK: Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, Windows/10.0.22593 cosmos-netstandard-sdk/3.24.1);
  Source=Microsoft.Azure.Cosmos.Client
  StackTrace:
   at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
   at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
```
---

Looking at the FAQs [here](https://docs.microsoft.com/en-us/azure/cosmos-db/autoscale-faq#can-i-enable-autoscale-on-an-existing-database-or-a-container-):-
>By design, you can't use the Cosmos DB client SDKs or ARM template to migrate between manual and autoscale. 

* What exactly is the concern here? Why isn't it supported "by design"?

**Comment by j82w** [comment]
Why does your application need this?

The reason it is not supported is this usually points to an antipattern.
1. Switching to autoscale should be a 1 time operation. Putting a 1 time operation inside the application seems like a bad design because that will need to be cleaned up after it is ran, and unnecessarily complicates the application. The better model would be to have a one time script that can be ran to convert all the containers.
2. Scaling should not be handled by the application code, because the workload should scale out horizontally. Having multiple instances all trying to change the container throughput will cause conflicts.

**Comment by hkuadithya** [comment]
@j82w The reason for this is because your V2 CosmosDB SDK didn't support autoscale. Therefore, all our older databases provisioned using V2 SDK are using manual throughput.

I don't agree with your point about autoscale setting being used in Application code. You can easily retrieve the `Container` object and check if Autoscale is enabled. If it's not enabled, then you can write code in application to enable it. Thus, the request to autoscale will be done just once.

```
Container container = cosmosClient.GetDatabase("DatabaseName").GetContainer("ContainerName");

ThroughputProperties autoscaleContainerThroughput = await container.ReadThroughputAsync(requestOptions: null); 

int? autoscaleMaxThroughput = autoscaleContainerThroughput.AutoscaleMaxThroughput;

if (autoscaleMaxThroughput  == null) {
      await container.ReplaceThroughputAsync(ThroughputProperties.CreateAutoscaleThroughput(5000));
}
```

We're a large-scale service in Microsoft Azure supporting 40+ regions with multiple CosmosDB accounts. If it were that easy or trivial to "write a one-time script that can be ran to convert all the containers", I wouldn't have raised this GitHub issue in the first place.

**Comment by j82w** [comment]
The problem with the model above with large scale services how does it decide which instance will actually update the container? If this happens during an upgrade then it's possible hundreds or even thousands of requests are sent to that container as each one of the individual apps are restarted. This can cause metadata throttling which could negatively impact other apps that are restarting from the upgrade.

What happens during upgrades when some apps are the older version and some are newer version? Will the old instance try changing the SKU because the throughput changed? Possibly leading to the container switching back and forth. 

What happens if some regions/containers have been scaled and setting the autoscale will now cause throttling?
