### ISSUE TITLE
ReadContainerAsync throws aggregate exception "Name or service not known"

### ISSUE THREAD

**Issue by IsaacUser** [Azure/azure-cosmos-dotnet-v3#3195]
A service hosted in AKS periodically calls the `ReadContainerAsync` function on a container. This works fine most of the time, but after some time it will begin to throw a seemingly DNS-related exception. In some cases, this persists until the service is restarted. My suspicion is that something goes awry with the address caching.

The issue started occurring sometime after [v3.24.0](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#-3240---2022-01-31), including the most recent version. My suspicion is that it may have been introduced in [v3.26.1](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#-3261---2022-03-16) - but I'm not sure

SDK Version: 3.27.0 

Exception message being thrown with the AccountName removed
```
Error message: One or more errors occurred. (Connection refused ([AccountName].documents.azure.com:443)) (Name or service not known ([AccountName]-eastus.documents.azure.com:443)) (Connection refused ([AccountName]-eastus2.documents.azure.com:443)) (Name or service not known ([AccountName]-southcentralus.documents.azure.com:443)) (Name or service not known ([AccountName]-northcentralus.documents.azure.com:443)) (Connection refused ([AccountName]-centralus.documents.azure.com:443)) (Name or service not known ([AccountName]-canadacentral.documents.azure.com:443)) (Name or service not known ([AccountName]-canadaeast.documents.azure.com:443)) (Name or service not known ([AccountName]-westcentralus.documents.azure.com:443)) (Name or service not known ([AccountName]-westus.documents.azure.com:443)) (Name or service not known ([AccountName]-westus3.documents.azure.com:443)) (Name or service not known ([AccountName]-westus2.documents.azure.com:443)) (Name or service not known ([AccountName]-northeurope.documents.azure.com:443)) (Name or service not known ([AccountName]-uksouth.documents.azure.com:443)) (Name or service not known ([AccountName]-ukwest.documents.azure.com:443)) (Name or service not known ([AccountName]-francecentral.documents.azure.com:443)) (Name or service not known ([AccountName]-westeurope.documents.azure.com:443)) (Name or service not known ([AccountName]-francesouth.documents.azure.com:443)) (Name or service not known ([AccountName]-switzerlandwest.documents.azure.com:443)) (Name or service not known ([AccountName]-germanywestcentral.documents.azure.com:443)) (Name or service not known ([AccountName]-germanynorth.documents.azure.com:443)) (Name or service not known ([AccountName]-switzerlandnorth.documents.azure.com:443)) (Name or service not known ([AccountName]-norwaywest.documents.azure.com:443)) (Name or service not known ([AccountName]-norwayeast.documents.azure.com:443)) (Name or service not known ([AccountName]-swedencentral.documents.azure.com:443)) (Name or service not known ([AccountName]-swedensouth.documents.azure.com:443)) (Name or service not known ([AccountName]-brazilsoutheast.documents.azure.com:443)) (Name or service not known ([AccountName]-brazilsouth.documents.azure.com:443)) (Name or service not known ([AccountName]-japaneast.documents.azure.com:443)) (Name or service not known ([AccountName]-japanwest.documents.azure.com:443)) (Name or service not known ([AccountName]-koreacentral.documents.azure.com:443)) (Name or service not known ([AccountName]-koreasouth.documents.azure.com:443)) (Name or service not known ([AccountName]-qatarcentral.documents.azure.com:443)) (Name or service not known ([AccountName]-uaecentral.documents.azure.com:443)) (Name or service not known ([AccountName]-uaenorth.documents.azure.com:443)) (Name or service not known ([AccountName]-australiaeast.documents.azure.com:443)) (Name or service not known ([AccountName]-jioindiawest.documents.azure.com:443)) (Name or service not known ([AccountName]-centralindia.documents.azure.com:443)) (Name or service not known ([AccountName]-jioindiacentral.documents.azure.com:443)) (Name or service not known ([AccountName]-westindia.documents.azure.com:443)) (Name or service not known ([AccountName]-australiacentral.documents.azure.com:443)) (Name or service not known ([AccountName]-australiacentral2.documents.azure.com:443)) (Name or service not known ([AccountName]-australiasoutheast.documents.azure.com:443)) (Name or service not known ([AccountName]-southindia.documents.azure.com:443)) (Name or service not known ([AccountName]-eastasia.documents.azure.com:443)) (Name or service not known ([AccountName]-southafricawest.documents.azure.com:443)) (Name or service not known ([AccountName]-southeastasia.documents.azure.com:443)) (Name or service not known ([AccountName]-southafricanorth.documents.azure.com:443)) (Name or service not known ([AccountName]-chinaeast.documents.azure.com:443)) (Name or service not known ([AccountName]-chinaeast2.documents.azure.com:443)) (Name or service not known ([AccountName]-chinaeast3.documents.azure.com:443)) (Name or service not known ([AccountName]-chinanorth.documents.azure.com:443)) (Name or service not known ([AccountName]-ussecwest.documents.azure.com:443)) (Name or service not known ([AccountName]-usseceast.documents.azure.com:443)) (Name or service not known ([AccountName]-usnatwest.documents.azure.com:443)) (Name or service not known ([AccountName]-usnateast.documents.azure.com:443)) (Name or service not known ([AccountName]-usgovtexas.documents.azure.com:443)) (Name or service not known ([AccountName]-usgovarizona.documents.azure.com:443)) (Name or service not known ([AccountName]-usdodeast.documents.azure.com:443)) (Name or service not known ([AccountName]-usdodcentral.documents.azure.com:443)) (Name or service not known ([AccountName]-chinanorth2.documents.azure.com:443)) (Name or service not known ([AccountName]-chinanorth3.documents.azure.com:443)) (Name or service not known ([AccountName]-eastusslv.documents.azure.com:443)) (Name or service not known ([AccountName]-germanycentral.documents.azure.com:443)) (Name or service not known ([AccountName]-germanynortheast.documents.azure.com:443)) (Name or service not known ([AccountName]-centraluseuap.documents.azure.com:443)) (Name or service not known ([AccountName]-usgovvirginia.documents.azure.com:443)) (Name or service not known ([AccountName]-eastus2euap.documents.azure.com:443))
```
stacktrace:
```
at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.GetAccountPropertiesHelper.GetAccountPropertiesAsync()
   at Microsoft.Azure.Cosmos.GatewayAccountReader.InitializeReaderAsync()
   at Microsoft.Azure.Cosmos.CosmosAccountServiceConfiguration.InitializeAsync()
   at Microsoft.Azure.Cosmos.DocumentClient.InitializeGatewayConfigurationReaderAsync()
   at Microsoft.Azure.Cosmos.DocumentClient.GetInitializationTaskAsync(IStoreClientFactory storeClientFactory)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Cosmos.AsyncCacheNonBlocking`2.GetAsync(TKey key, Func`2 singleValueInitFunc, Func`2 forceRefresh)
   at Microsoft.Azure.Cosmos.AsyncCacheNonBlocking`2.GetAsync(TKey key, Func`2 singleValueInitFunc, Func`2 forceRefresh)
   at Microsoft.Azure.Cosmos.DocumentClient.EnsureValidClientAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.EnsureValidClientAsync(RequestMessage request, ITrace trace)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(String resourceUriString, ResourceType resourceType, OperationType operationType, RequestOptions requestOptions, ContainerInternal cosmosContainerCore, FeedRange feedRange, Stream streamPayload, Action`1 requestEnricher, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.CosmosClient.<>c__DisplayClass52_0.<<CreateDatabaseIfNotExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](ITrace trace, Func`2 task)
   at Microsoft.Azure.Cosmos.ClientContextCore.OperationHelperWithRootTraceAsync[TResult](String operationName, RequestOptions requestOptions, Func`2 task, TraceComponent traceComponent, TraceLevel traceLevel)
```

**Comment by j82w** [comment]
@IsaacUser are you recreating the CosmosClient? It should be a singleton and the above code path is only called on creation. The SDK has multiple caches so recreating it is not recommended. Make sure to follow the best practices. 
https://docs.microsoft.com/en-us/azure/cosmos-db/sql/best-practice-dotnet

**Comment by IsaacBoy** [comment]
> @IsaacUser are you recreating the CosmosClient? It should be a singleton and the above code path is only called on creation. The SDK has multiple caches so recreating it is not recommended. Make sure to follow the best practices. https://docs.microsoft.com/en-us/azure/cosmos-db/sql/best-practice-dotnet

No it's a singleton. Can you please reopen the bug?
