### ISSUE TITLE
Null stream causing ArgumentNullException during serialization while running query

### ISSUE THREAD

**Issue by asgoe** [Azure/azure-cosmos-dotnet-v3#3210]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
We have recently moved to using the CosmosDb V3 SDK. For one our services we received ArgumentNullExceptions when running SQL queries. Looking at the call stack it seems that the server is passing a null stream to the custom serializer. This is not happening for all queries but only a certain subset of them. We opened an ICM to the Sql Query team and they pointed to this issue: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1079. The call stack is similar to it and seems that the issue is coming from line 32 of this code: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonSerializerWrapper.cs

This was impacting our customers so we had to rollback to the V2 code. This is blocking rollout of our V3 code.
ICM: [Incident 308754558](https://portal.microsofticm.com/imp/v3/incidents/details/308754558/home) : Null stream causing ArgumentNullException while running a Sql query

Error Call stack: 
`System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at Microsoft.Intune.CloudStorage.Common.Serializer.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosSqlQuerySpecJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.Azure.Cosmos.CosmosJsonDotNetSerializer.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.ToStream[T](T input)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.<ExecuteItemQueryAsync>d__10.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.NetworkAttachedDocumentContainer.<MonadicQueryAsync>d__16.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CrossPartition.OrderBy.OrderByQueryPartitionRangePageAsyncEnumerator.InnerEnumerator.<GetNextPageAsync>d__15.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.PartitionRangePageAsyncEnumerator`2.<MoveNextAsync>d__16.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.BufferedPartitionRangePageAsyncEnumerator`2.<PrefetchAsync>d__5.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.ParallelPrefetch.<>c__DisplayClass0_1.<<PrefetchInParallelAsync>b__0>d.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.ParallelPrefetch.<PrefetchInParallelAsync>d__0.MoveNext()
   at Microsoft.Azure.Cosmos.Pagination.ParallelPrefetch.<PrefetchInParallelAsync>d__0.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CrossPartition.OrderBy.OrderByCrossPartitionQueryPipelineStage.<MoveNextAsync_InitializeAsync>d__23.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.SkipEmptyPageQueryPipelineStage.<MoveNextAsync>d__13.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.LazyQueryPipelineStage.<MoveNextAsync>d__8.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.NameCacheStaleRetryQueryPipelineStage.<MoveNextAsync>d__10.MoveNext()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CatchAllQueryPipelineStage.<MoveNextAsync>d__1.MoveNext()
   at Microsoft.Azure.Cosmos.Query.QueryIterator.<ReadNextAsync>d__14.MoveNext()
   at Microsoft.Azure.Cosmos.ClientContextCore.<RunWithDiagnosticsHelperAsync>d__39`1.MoveNext()
   at Microsoft.Azure.Cosmos.ClientContextCore.<OperationHelperWithRootTraceAsync>d__30`1.MoveNext()
   at Microsoft.Intune.CloudStorage.Common.CosmosDbFeedIterator.<>c__DisplayClass19_0.<<ReadNextAsync>b__0>d.MoveNext()
   at Microsoft.Intune.CloudStorage.Common.ReconnectExecutor.<ExecuteAsync>d__2.MoveNext()
   at Microsoft.Intune.CloudStorage.Common.CosmosDbClient.<>c__DisplayClass49_0.<<ExecuteAsync>b__0>d.MoveNext()
   at Microsoft.Intune.CloudStorage.Common.Retry.ObservableThrottlingRetryExecutor.<OnExecutingAsync>d__3`1.MoveNext()
   at Microsoft.Intune.CloudStorage.Common.CosmosDbClient.<ExecuteAsync>d__49.MoveNext()`

**To Reproduce**
This issue was happening only on few custom queries, but was consistent.

**Expected behavior**
No Nullreference exception

**Actual behavior**
Null reference exception is being thrown

**Environment summary**
SDK Version: 3.25.0 version of Microsoft.Azure.Cosmos
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by asgoe** [comment]
Tagging the people from the previous issue: @kirankumarkolli/[j82w](https://github.com/j82w)

**Comment by ealsur** [comment]
@asgoe the error points to https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/CosmosSqlQuerySpecJsonConverter.cs#L52

Which means the value of the QuerySpec parameter is null and your `Microsoft.Intune.CloudStorage.Common.Serializer` implementation is not handling this case and throwing.

The exception comes from your `Microsoft.Intune.CloudStorage.Common.Serializer` code.

**Comment by asgoe** [comment]
One question, do we need to handle the case of a null stream being passed to the custom serializer as well?

**Comment by ealsur** [comment]
In this case, there won't be a null stream because the query parameters are always values, ToStream is called when converting from a value to a Stream.

FromStream, the stream ideally is never null, it would be used when converting a service response to your types. @j82w do you know any scenario where the Stream would be null on FromStream? I personally don't recall any, our implementation does not even handle that: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs#L78-L96

**Comment by asgoe** [comment]
For the ToStream code path when a QuerySpec parameter is null, would just returning the null field of stream work? (https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.null?view=net-6.0)

**Comment by asgoe** [comment]
@ealsur starting working on the fix for this. Instead of just changing our serializer, I am trying to understand the expectation that the CosmosSqlQuerySpecJsonConverter.cs has if a null value needs to be passed. For a query like below, what should the SqlParameter value be set to if we want to match on null? I have tried passing in "" and "null" but neither of them return the correct result. Are you expecting the StreamReader to generate a null value in the below code?
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/cd18f1d1a07003b4ec4cd0ddf6d6c5696609631b/Microsoft.Azure.Cosmos/src/CosmosSqlQuerySpecJsonConverter.cs#L52

Query:
SELECT c.Key FROM c where c.StringValue="bar" and c.UniqueTestId="9801d737-27d7-40e1-b168-1d47c5e5ecde" and c.NullableGuid=**null**
