### ISSUE TITLE
Null reference is thrown when calling GetItemLinqQueryable with expression containing Guid.Empty condition check

### ISSUE THREAD

**Issue by pawel87** [Azure/azure-cosmos-dotnet-v3#3216]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When calling 'Where' method with expression on GetItemLinqQueryable - "Null reference exception" is thrown when Guid.Empty condition is a part of expression passed to Where method.

**To Reproduce**

`
var items= await GetItemsAsync(p => p.Id != Guid.Empty);
`
`
public async Task<IEnumerable<T>> GetItemsAsync(Expression<Func<T, bool>> predicate, string partitionKey = null)
{
   using var streamIterator = _container.GetItemLinqQueryable<T>().Where(predicate).ToStreamIterator();
   while (streamIterator.HasMoreResults)
   {
        //fetch data....
    }
}
`

**Expected behavior**
Return items from specific container based on passed LINQ expression.

**Actual behavior**
"Object reference not set to an instance of an object." exception is thrown

**Environment summary**
SDK Version: 3.27.0
OS Version: Windows

**Additional context**

The same code works as expected in version 3.26.0
It seems like following PR introduced issue:
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2924/files#diff-e47b89653d6e02bcd95fbcacc6822b7c8769a6a4e936d3aa59ddde29f014a336

You can find stack trace below:

`
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.EvaluateMemberAccess(Expression expression)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.EvaluateMemberAccess(Expression expression)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.EvaluateConstant(Expression expression)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Visit(Expression expression)
   at Microsoft.Azure.Cosmos.Linq.SubtreeEvaluator.Evaluate(Expression expression)
   at Microsoft.Azure.Cosmos.Linq.ConstantEvaluator.PartialEval(Expression expression, Func`2 fnCanBeEvaluated)
   at Microsoft.Azure.Cosmos.Linq.ConstantEvaluator.PartialEval(Expression expression)
   at Microsoft.Azure.Cosmos.Linq.SqlTranslator.TranslateQuery(Expression inputExpression, CosmosLinqSerializerOptions linqSerializerOptions, IDictionary`2 parameters)
   at Microsoft.Azure.Cosmos.Linq.DocumentQueryEvaluator.HandleMethodCallExpression(MethodCallExpression expression, IDictionary`2 parameters, CosmosLinqSerializerOptions linqSerializerOptions)
   at Microsoft.Azure.Cosmos.Linq.DocumentQueryEvaluator.Evaluate(Expression expression, CosmosLinqSerializerOptions linqSerializerOptions, IDictionary`2 parameters)
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery`1.CreateStreamIterator(Boolean isContinuationExcpected)
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery`1.ToStreamIterator()
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqExtensions.ToStreamIterator[T](IQueryable`1 query)
`

**Comment by j82w** [comment]
It likely fixed by this change: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3210 I'll start working on a release which should hopefully be done by end of the week.

**Comment by j82w** [comment]
@pawel87 please try the latest SDK 3.27.1

**Comment by pawel87** [comment]
> @pawel87 please try the latest SDK 3.27.1

It works now as expected! Thanks a lot for quick fix :)
