### ISSUE TITLE
System.ObjectDisposedException: Cannot access a closed Stream

### ISSUE THREAD

**Issue by giladl99-eng** [Azure/azure-cosmos-dotnet-v3#3263]
Following our migration to cosmos SDK v3 and usage of feed range API, we started to see this exception occasionally in our traces:

Error while copying content to a stream. ---> System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.Stream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.StreamToStreamCopy.CopyAsync(Stream source, Stream destination, Int32 bufferSize, Boolean disposeSource, CancellationToken cancellationToken)

It is coming from cosmos client when trying to pull feed ranges, see full stack trace attached:

at Microsoft.Azure.Cosmos.GatewayStoreClient.<InvokeAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.<ProcessMessageAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Routing.PartitionKeyRangeCache.<ExecutePartitionKeyRangeReadChangeFeedAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

at Microsoft.Azure.Cosmos.Routing.PartitionKeyRangeCache.<TryLookupAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Routing.PartitionKeyRangeCache.<TryGetOverlappingRangesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ContainerCore.<GetFeedRangesAsync>d__35.MoveNext()

**Comment by FabianMeiswinkel** [comment]
Looks like you forgot to attach the full callstack (the one in the bug description doesn't show what API on container is called and from where). Can you please attach the full callstack?

**Comment by giladl99-eng** [comment]
[docdb sdkv3 stack trace.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/8888955/docdb.sdkv3.stack.trace.txt)

**Comment by ealsur** [comment]
```
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.Stream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.StreamToStreamCopy.CopyAsync(Stream source, Stream destination, Int32 bufferSize, Boolean disposeSource, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.GatewayStoreClient.<BufferContentIfAvailableAsync>d__13.MoveNext()
```

Looks like the issue is related to System.Net.Http. In this flow, the application received the HTTP response and our SDK code is asking the HttpResponseMessage to copy the Stream content to a MemoryStream:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8154849cdf441b3c9669550b64344be7e4c84ad3/Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs#L228-L239

The ownership of the source Stream is on the System.Net space, why was it disposed is something we don't quite know but it's not controlled by the SDK code.

**Comment by ealsur** [comment]
Which .NET Framework / NET Standard implementation version are you running on?

**Comment by giladl99-eng** [comment]
.NET 4.6.2

**Comment by ealsur** [comment]
@giladl99-eng What is the lifetime of your CosmosClient? Are there any events that would call its Dispose? The only relationship I can see if, when the CosmosClient is disposed the HttpClient is disposed. I wonder if this occurs while a response Content is being accessed, if this might the reason.

**Comment by giladl99-eng** [comment]
Hi Matias,

We use cosmos client as singleton, dispose happens when our service shuts down. We saw those exceptions frequently with no correlation to process termination.

**Comment by ealsur** [comment]
We were able to root cause and find the source of this problem, it was affecting only Bounded Staleness/Strong accounts and it was related to the handling of quorum responses.

**Comment by ealsur** [comment]
Incorrect linking. This is not the case that was fixed and found. This Issue's stack trace and error is not related to the issue found and fixed.

The issue we found and fixed was related to Bounded Staleness/Strong barrier requests on the TCP stack, this stack trace is for an HTTP operation obtaining metadata information and the disposing is tied to the HttpClient Stream management.
