### ISSUE TITLE
Cannot connect to the Cosmos DB Emulator via a proxy and encounter Unauthorized (401)

### ISSUE THREAD

**Issue by DarknessChen** [Azure/azure-cosmos-dotnet-v3#3275]
**Describe the bug**
We are trying to do some local developments and use a proxy in-between the application under test and the Cosmos DB emulator. However, we cannot connect to the Cosmos DB emulator successfully and always encounter this problem: 
```
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: Unauthorized (401); Substatus: 0;
ActivityId: 0ce9dbe3-1040-4a53-978e-13a803028667; Reason: (The input authorization token can't serve the request.
The wrong key is being used or the expected payload is not built as per the protocol. For more info: https://aka.ms/cosmosdb-tsg-unauthorized. 
Server used the following payload to sign: 'get
thu, 16 jun 2022 21:01:56 gmt
'
ActivityId: 0ce9dbe3-1040-4a53-978e-13a803028667, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, Windows/10.0.19044 cosmos-netstandard-sdk/3.27.2);
```

We infer the problem may be related to SSL validation, so we modified the application by following https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1232#issuecomment-670673733 or [this article](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21#disable-ssl-validation) to try to disable SSL, but the same problem still appears. And the requests are still using the HTTPS protocol.

We found that the request to construct the Cosmos client via [CosmosClient(String, String, CosmosClientOptions)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclient.-ctor?view=azure-dotnet#microsoft-azure-cosmos-cosmosclient-ctor(system-string-system-string-microsoft-azure-cosmos-cosmosclientoptions)) always succeeds with a status code 200. However, after constructing the client successfully, when using [CreateDatabaseIfNotExistsAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclient.createdatabaseifnotexistsasync?view=azure-dotnet) to create the database, we will receive the Unauthorized (401) error.

**To Reproduce**
Set up a [Mockserver](https://www.mock-server.com/proxy/getting_started.html) proxy between the .NET application and the emulator, and then let the application use `CreateDatabaseIfNotExistsAsync` to create a database in the emulator.

**Expected behavior**
The application should be able to connect to the emulator to create the database.

**Actual behavior**
There would be a 401 (Unauthorised) error returned.

**Environment summary**
`Platform`: Everything in Windows 10 Pro
`Microsoft.Azure.Cosmos version`: 3.27.0
`.NET`: 6.0
`Proxy`: [Mockserver](https://www.mock-server.com/mock_server/HTTPS_TLS.html#:~:text=MockServer%20will%20only%20be%20able,509%20certificates%20provided.)

**Additional Context**
We have checked that both the proxy and the emulator certificates already exist in the machine.
<details>
<summary>Whole stack trace</summary>

```
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: Unauthorized (401); Substatus: 0; ActivityId: 0ce9dbe3-1040-4a53-978e-13a803028667; Reason: (The input authorization token can't serve the request. The wrong key is being used or the expected payload is not built as per the protocol. For more info: https://aka.ms/cosmosdb-tsg-unauthorized. Server used the following payload to sign: 'get
thu, 16 jun 2022 21:01:56 gmt
'
ActivityId: 0ce9dbe3-1040-4a53-978e-13a803028667, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, Windows/10.0.19044 cosmos-netstandard-sdk/3.27.2);
StackTrace:    at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
   at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.GetMasterAddressesViaGatewayAsync(DocumentServiceRequest request, ResourceType resourceType, String resourceAddress, String entryUrl, Boolean forceRefresh, Boolean useMasterCollectionResolver)
   at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.ResolveMasterAsync(DocumentServiceRequest request, Boolean forceRefresh)
   at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.TryGetAddressesAsync(DocumentServiceRequest request, PartitionKeyRangeIdentity partitionKeyRangeIdentity, ServiceIdentity serviceIdentity, Boolean forceRefreshPartitionAddresses, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.AddressResolver.ResolveAddressesAndIdentityAsync(DocumentServiceRequest request, Boolean forceRefreshPartitionAddresses, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.AddressResolver.ResolveAsync(DocumentServiceRequest request, Boolean forceRefreshPartitionAddresses, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Routing.GlobalAddressResolver.ResolveAsync(DocumentServiceRequest request, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.AddressSelector.ResolveAddressesAsync(DocumentServiceRequest request, Boolean forceAddressRefresh)
   at Microsoft.Azure.Documents.AddressSelector.ResolveAllTransportAddressUriAsync(DocumentServiceRequest request, Boolean includePrimary, Boolean forceRefresh)
   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicasInternalAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)
   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicaAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)
   at Microsoft.Azure.Documents.QuorumReader.ReadQuorumAsync(DocumentServiceRequest entity, Int32 readQuorum, Boolean includePrimary, ReadMode readMode)
   at Microsoft.Azure.Documents.QuorumReader.ReadStrongAsync(DocumentServiceRequest entity, Int32 readQuorumValue, ReadMode readMode)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass31_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy, Func`2 prepareRequestAsyncDelegate)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
  Failed Should_complete [845 ms]
  Error Message:
   OneTimeSetUp: Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: Unauthorized (401); Substatus: 0; ActivityId: 0ce9dbe3-1040-4a53-978e-13a803028667; Reason: (The input authorization token can't serve the request. The wrong key is being used or the expected payload is not built as per the protocol. For more info: https://aka.ms/cosmosdb-tsg-unauthorized. Server used the following payload to sign: 'get
thu, 16 jun 2022 21:01:56 gmt
'
ActivityId: 0ce9dbe3-1040-4a53-978e-13a803028667, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, Windows/10.0.19044 cosmos-netstandard-sdk/3.27.2);
Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 845 ms - MassTransit.Azure.Cosmos.Tests.dll (net6.0)
```
</details>

**Comment by ealsur** [comment]
This is not related to SSL, SSL errors are different. This is the Emulator returning 401, it's not a mis-behavior or error on the SDK.

Why is the Emulator returning 401 is outside of this repo's expertise, but check the date/time on the error message to understand if there isn't a clock skew on the machines.

**Comment by ealsur** [comment]
Closing as out of scope of this repository, for Emulator related issues please look at the support link in https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-local-emulator

If removing the Proxy solves the issue, it could be a misconfiguration on the proxy itself (unsure if Mockserver requires any extra configuration, the IWebProxy interface is available in CosmosClientOptions).

Based on personal experience, this means either the key you are using is a read-only key (but Emulator has only one), or the payload (auth payload) is invalid due to clock skew.
