### ISSUE TITLE
ToFeedIterator throws a non-specific exception when an invalid continuation token is passed in the query

### ISSUE THREAD

**Issue by vit-svoboda** [Azure/azure-cosmos-dotnet-v3#3416]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
`IQueryable<T>` extension method `ToFeedIterator` makes it impossible to write error handling for an invalid continuation token being  passed in the query. A general `JsonInvalidTokenException` wrapped in `ExceptionWithStackTraceException` is thrown instead of a descriptive `CosmosException`.

**To Reproduce**
```
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Cosmos.Fluent;
using Microsoft.Azure.Cosmos.Linq;

var client = new CosmosClientBuilder("<cosmos connection string>")
    .WithConnectionModeDirect()
    .Build();

var container = client.GetContainer("<database name>", "<collection name>");
var continuationToken = "not json goes boom";

var queryable = container.GetItemLinqQueryable<dynamic>(continuationToken: continuationToken);

// Throws JsonInvalidTokenException wrapped in ExceptionWithStackTraceException 
var iterator = queryable.ToFeedIterator(); 

var response = await iterator.ReadNextAsync();
```

**Expected behavior**
Either `ToFeedIterator` or `ReadNextAsync` throws `CosmosException` saying "The continuation token specified in the request is malformed. Re-run the query without it and iterate." with the `SubStatusCode` mentioned in https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3074.

**Actual behavior**
`ToFeedIterator` throws `ExceptionWithStackTraceException` with inner `JsonInvalidTokenException` saying "Encountered an element that is not a valid JSON value (false / null / true / object / array / number / string), Windows/10.0.19044 cosmos-netstandard-sdk/3.29.1" but no mention of what has been parsed.

**Environment summary**
SDK Version: 3.30.0
OS Version (e.g. Windows, Linux, MacOSX): Windows 10

**Additional context**
The descriptive `CosmosException` is thrown from the `ReadNextAsync` if the `FeedIterator` is created like so:
```
var queryDefinition = queryable.ToQueryDefinition();

var iterator = client.GetDatabaseQueryIterator<object>(
    queryDefinition,
    continuationToken);
```
But when I use `ToFeedIterator` instead, the `ExceptionWithStackTraceException` terminates the execution before I get to call `ReadNextAsync`.

This problem started with SDK version 3.14.0.

**Comment by ealsur** [comment]
@leminh98 Could you take a look at this report?

**Comment by camillemarie** [comment]
I'm running into a similar issue (non-public Exception type, making it difficult to `catch`) with Container.GetItemQueryIterator<T> and a non-json continuation token (specifically: a v2 continuation token passed into v3).

**To Reproduce**
Call `GetItemQueryIterator<T>` with:
- a null QueryDefinition (so it creates a ReadFeed iterator)
- an invalid non-json continuation token (in my case: a continuation token returned from an application running V2 SDK)

```
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.Cosmos.Fluent;
using Microsoft.Azure.Cosmos.Linq;

var client = new CosmosClientBuilder("<cosmos connection string>")
    .WithConnectionModeDirect()
    .Build();

var container = client.GetContainer("<database name>", "<collection name>");
var continuationToken = "+RID:~8AtcAKunVa8CAAAAAAAAAA==#RT:1#TRC:2#ISV:2#IEO:65567#QCF:8#FPC:AQIAAAAAAAAACgAAAAAAAAA=";

var queryRequestOptions = new QueryRequestOptions
{
    MaxItemCount = 1000,
    PartitionKey = "<Your partition key">,
    ResponseContinuationTokenLimitInKb = 8
};

// Use null query definition to ensure it goes down the ReadFeed code path and throws the internal JsonUnexpectedTokenException
// The Query path handles this nicely and throws a CosmosException instead
var queryIterator = container.GetItemQueryIterator<TResult>(
    queryDefinition: null,
    continuationToken: continuationToken,
    requestOptions: queryRequestOptions))

```
**Expected behavior**
`GetItemQueryIterator` or `ReadNextAsync` should throw a `CosmosException`, similar to the following:
```
Response status code does not indicate success: BadRequest (400); Substatus: 20007; ActivityId: ; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 20007; ActivityId: ; Reason: (Malformed Continuation Token: +RID:~8AtcALfggvYCAAAAAAAAAA==#RT:1#TRC:2#ISV:2#IEO:65567#QCF:8#FPC:AQIAAAAAAAAACgAAAAAAAAA=););
```

**Actual behavior**
`GetItemQueryIterator` throws a non-public exception type, making it difficult to catch.


Microsoft.Azure.Cosmos.Query.Core.Monads.ExceptionWithStackTraceException: TryCatch resulted in an exception

InnerException: Microsoft.Azure.Cosmos.Json.JsonUnexpectedTokenException: Encountered an unexpected JSON token., Windows/10.0.22621 cosmos-netstandard-sdk/3.29.1"

```
System.Exception {Microsoft.Azure.Cosmos.Json.JsonUnexpectedTokenException}
   at Microsoft.Azure.Cosmos.Json.JsonReader.JsonTextReader.Read() in D:\a\1\s\Microsoft.Azure.Cosmos\src\Json\JsonReader.JsonTextReader.cs:line 276
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.Parser.Parse(IJsonTextReaderPrivateImplementation jsonTextReader) in D:\a\1\s\Microsoft.Azure.Cosmos\src\Json\JsonNavigator.JsonTextNavigator.cs:line 453
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator.<>c__DisplayClass3_0.<.ctor>g__CreateRootNode|0() in D:\a\1\s\Microsoft.Azure.Cosmos\src\Json\JsonNavigator.JsonTextNavigator.cs:line 65
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.JsonTextNavigator..ctor(ReadOnlyMemory`1 buffer) in D:\a\1\s\Microsoft.Azure.Cosmos\src\Json\JsonNavigator.JsonTextNavigator.cs:line 83
   at Microsoft.Azure.Cosmos.Json.JsonNavigator.Create(ReadOnlyMemory`1 buffer) in D:\a\1\s\Microsoft.Azure.Cosmos\src\Json\JsonNavigator.cs:line 53
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.Monadic.CreateFromBuffer[TCosmosElement](ReadOnlyMemory`1 buffer) in D:\a\1\s\Microsoft.Azure.Cosmos\src\CosmosElements\CosmosElement.cs:line 108
----------------------------------------------------
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.Monadic.CreateFromBuffer[TCosmosElement](ReadOnlyMemory`1 buffer)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.Monadic.Parse[TCosmosElement](String serializedCosmosElement)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.Monadic.Parse(String serializedCosmosElement)
   at Microsoft.Azure.Cosmos.CosmosElements.CosmosElement.Parse(String json)
   at Microsoft.Azure.Cosmos.ReadFeed.ReadFeedIteratorCore..ctor(IDocumentContainer documentContainer, String continuationToken, ReadFeedPaginationOptions readFeedPaginationOptions, QueryRequestOptions queryRequestOptions, ContainerInternal container, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ContainerCore.GetItemQueryStreamIteratorInternal(SqlQuerySpec sqlQuerySpec, Boolean isContinuationExcpected, String continuationToken, FeedRangeInternal feedRange, QueryRequestOptions requestOptions)
   at Microsoft.Azure.Cosmos.ContainerCore.GetItemQueryStreamIterator(QueryDefinition queryDefinition, String continuationToken, QueryRequestOptions requestOptions)
   at Microsoft.Azure.Cosmos.ContainerInlineCore.GetItemQueryStreamIterator(QueryDefinition queryDefinition, String continuationToken, QueryRequestOptions requestOptions)
   at Microsoft.Azure.Cosmos.ContainerCore.GetItemQueryIterator[T](QueryDefinition queryDefinition, String continuationToken, QueryRequestOptions requestOptions)
   at Microsoft.Azure.Cosmos.ContainerInlineCore.GetItemQueryIterator[T](QueryDefinition queryDefinition, String continuationToken, QueryRequestOptions requestOptions)
```

SDK Version: 3.31.0 (Not sure why the exception shows 3.29.1)
OS Version: Windows 11



**Additional context**
We are upgrading from V2 to V3, and we want continuations to work seamlessly for our customers during the transition (it's an edge case, but there will be a window where some regions are on V2 and some are V3). We have logic to catch and fallback on the CosmosException 400/20007 for Queries, but it does not work for ReadFeed due to the internal exception type thrown by GetItemQueryIterator. We're catching a generic Exception and parsing the error message for now, but that's obviously not ideal.

**Comment by vilemj-Viclick** [comment]
I'd like to add that a more specific exception is welcome not only for malformed tokens but also plain old invalid continuation tokens.
A made-up token like this: `[{\"token\":\"+RID:~5lk-AN3tC100#RTD:h\",\"range\":{\"min\":\"\",\"max\":\"FF\"}}]` will make the SDK throw an exception like this:
```
"Microsoft.Azure.Cosmos.CosmosException with message "Response status code does not indicate success: BadRequest (400); 
Substatus: 0;
ActivityId: <Irrelevant>; 
Reason: (Message: {"Errors":["The continuation token specified in the request is malformed. Re-run the query without it and iterate."]}
```
A specific (and ideally documented) sub-status code would be appreciated.

**Comment by vit-svoboda** [comment]
Our testing also discovered that the SDK throws various other errors if the provided continuation token is not valid JSON. `Microsoft.Azure.Cosmos.CosmosException` with 400 BadRequest message and the following details.
* Reason: (Missing a closing quote (") in JSON.
* Reason: (Read a JSON end object ("}") symbol without a matching JSON start object symbol ("{"
* Reason: (Encountered an unexpected JSON token.

None of that hints the error is caused by a continuation token, so proper error handling is quite difficult.
