### ISSUE TITLE
[Encryption] Preview Encryption Emulator Tests are flaky

### ISSUE THREAD

**Issue by neildsh** [Azure/azure-cosmos-dotnet-v3#3435]
**Describe the bug**
The encryption emulator tests pipeline is flaky, and one or more tests tends to fail at random. Rerunning the pipeline will usually make it pass

**To Reproduce**
Any pull request runs this pipeline

**Expected behavior**
The pipeline should have deterministic behavior.

**Actual behavior**
The pipeline fails at random.

**Additional context**
Attaching build logs from one run.
[encryption_emulator_tests_pipeline_failure1.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/9465337/encryption_emulator_tests_pipeline_failure1.txt)

**Comment by sc978345** [comment]
Log from failed test:

2022-10-25T23:55:02.9139404Z Starting test execution, please wait...
2022-10-25T23:55:03.0496456Z A total of 1 test files matched the specified pattern.
2022-10-25T23:56:23.7804198Z   Failed EncryptionChangeFeedDecryptionSuccessful [1 m 2 s]
2022-10-25T23:56:23.7809697Z   Error Message:
2022-10-25T23:56:23.7811848Z    Test method Microsoft.Azure.Cosmos.Encryption.EmulatorTests.MdeEncryptionTests.EncryptionChangeFeedDecryptionSuccessful threw exception: 
2022-10-25T23:56:23.7814848Z System.NullReferenceException: Object reference not set to an instance of an object.
2022-10-25T23:56:23.7821409Z   Stack Trace:
2022-10-25T23:56:23.7825412Z       at Microsoft.Azure.Cosmos.Encryption.EmulatorTests.MdeEncryptionTests.<>c__DisplayClass51_0.<ValidateChangeFeedProcessorResponse>b__1(TestDoc doc) in D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\tests\EmulatorTests\MdeEncryptionTests.cs:line 2774
2022-10-25T23:56:23.7835987Z    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
2022-10-25T23:56:23.7838758Z    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
2022-10-25T23:56:23.7840916Z    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
2022-10-25T23:56:23.7842979Z    at Microsoft.Azure.Cosmos.Encryption.EmulatorTests.MdeEncryptionTests.ValidateChangeFeedProcessorResponse(Container container, TestDoc testDoc1, TestDoc testDoc2) in D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\tests\EmulatorTests\MdeEncryptionTests.cs:line 2774
2022-10-25T23:56:23.7845591Z    at Microsoft.Azure.Cosmos.Encryption.EmulatorTests.MdeEncryptionTests.EncryptionChangeFeedDecryptionSuccessful() in D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\tests\EmulatorTests\MdeEncryptionTests.cs:line 845
2022-10-25T23:56:23.7847166Z    at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
2022-10-25T23:56:23.7847906Z 
2022-10-25T23:57:01.8964807Z Results File: D:\a\_temp\VssAdministrator_WIN-LBH1HAQ42KE_2022-10-25_23_55_16.trx
2022-10-25T23:57:01.9014824Z 
2022-10-25T23:57:01.9102608Z Failed!  - Failed:     1, Passed:    32, Skipped:     0, Total:    33, Duration: 1 m 46 s - Microsoft.Azure.Cosmos.Encryption.EmulatorTests.dll (net6.0)
2022-10-25T23:57:01.9340104Z      1>Done Building Project "D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\tests\EmulatorTests\Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj" (VSTest target(s)) -- FAILED.
2022-10-25T23:57:01.9415528Z 
2022-10-25T23:57:01.9418452Z Build FAILED.
2022-10-25T23:57:01.9426369Z 
2022-10-25T23:57:01.9428926Z        "D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\tests\EmulatorTests\Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj" (VSTest target) (1:7) ->
2022-10-25T23:57:01.9432033Z        "D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\tests\EmulatorTests\Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj" (default target) (1:8) ->
2022-10-25T23:57:01.9434192Z        "D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj" (default target) (2:6) ->
2022-10-25T23:57:01.9435705Z        (CoreCompile target) -> 
2022-10-25T23:57:01.9439855Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\MdeSrc\Cryptography\Serializers\StandardSerializers\UInt64Serializer.cs(18,20): warning CS3019: CLS compliance checking will not be performed on 'UInt64Serializer' because it is not visible from outside this assembly [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9444886Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\MdeSrc\Cryptography\Serializers\StandardSerializers\UInt32Serializer.cs(18,20): warning CS3019: CLS compliance checking will not be performed on 'UInt32Serializer' because it is not visible from outside this assembly [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9449173Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\MdeSrc\Cryptography\Serializers\StandardSerializers\UInt16Serializer.cs(18,20): warning CS3019: CLS compliance checking will not be performed on 'UInt16Serializer' because it is not visible from outside this assembly [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9452487Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\MdeSrc\Cryptography\Serializers\StandardSerializers\SByteSerializer.cs(16,20): warning CS3019: CLS compliance checking will not be performed on 'SByteSerializer' because it is not visible from outside this assembly [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9454972Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\MdeSrc\Cryptography\Serializers\StandardSerializers\NullableUInt64Serializer.cs(16,20): warning CS3019: CLS compliance checking will not be performed on 'NullableUInt64Serializer' because it is not visible from outside this assembly [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9457932Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\MdeSrc\Cryptography\Serializers\StandardSerializers\NullableUInt32Serializer.cs(16,20): warning CS3019: CLS compliance checking will not be performed on 'NullableUInt32Serializer' because it is not visible from outside this assembly [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9460850Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\MdeSrc\Cryptography\Serializers\StandardSerializers\NullableUInt16Serializer.cs(16,20): warning CS3019: CLS compliance checking will not be performed on 'NullableUInt16Serializer' because it is not visible from outside this assembly [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9464326Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\MdeSrc\Cryptography\Serializers\StandardSerializers\NullableSByteSerializer.cs(16,20): warning CS3019: CLS compliance checking will not be performed on 'NullableSByteSerializer' because it is not visible from outside this assembly [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9466821Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\QueryDefinitionExtensions.cs(46,51): warning CS3002: Return type of 'QueryDefinitionExtensions.AddParameterAsync(QueryDefinition, string, object, string, CancellationToken)' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9469002Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\QueryDefinitionExtensions.cs(47,34): warning CS3001: Argument type 'QueryDefinition' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9471214Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionContainerExtensions.cs(41,45): warning CS3002: Return type of 'EncryptionContainerExtensions.InitializeEncryptionAsync(Container, CancellationToken)' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9476069Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionContainerExtensions.cs(42,28): warning CS3001: Argument type 'Container' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9478411Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionContainerExtensions.cs(78,39): warning CS3002: Return type of 'EncryptionContainerExtensions.ToEncryptionFeedIterator<T>(Container, IQueryable<T>)' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9480824Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionContainerExtensions.cs(79,28): warning CS3001: Argument type 'Container' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9483297Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionContainerExtensions.cs(113,36): warning CS3002: Return type of 'EncryptionContainerExtensions.ToEncryptionStreamIterator<T>(Container, IQueryable<T>)' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9485388Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionContainerExtensions.cs(114,28): warning CS3001: Argument type 'Container' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9487465Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionContainerExtensions.cs(154,39): warning CS3002: Return type of 'EncryptionContainerExtensions.CreateQueryDefinition(Container, string)' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9492859Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionContainerExtensions.cs(154,76): warning CS3001: Argument type 'Container' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9496533Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionCosmosClientExtensions.cs(38,36): warning CS3002: Return type of 'EncryptionCosmosClientExtensions.WithEncryption(CosmosClient, IKeyEncryptionKeyResolver, string, TimeSpan?)' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9514698Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionCosmosClientExtensions.cs(39,31): warning CS3001: Argument type 'CosmosClient' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9517840Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionCosmosClientExtensions.cs(40,39): warning CS3001: Argument type 'IKeyEncryptionKeyResolver' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9521719Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionDatabaseExtensions.cs(54,63): warning CS3002: Return type of 'EncryptionDatabaseExtensions.CreateClientEncryptionKeyAsync(Database, string, string, EncryptionKeyWrapMetadata, CancellationToken)' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9525008Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionDatabaseExtensions.cs(55,27): warning CS3001: Argument type 'Database' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9527898Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionDatabaseExtensions.cs(58,39): warning CS3001: Argument type 'EncryptionKeyWrapMetadata' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9531073Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionDatabaseExtensions.cs(159,63): warning CS3002: Return type of 'EncryptionDatabaseExtensions.RewrapClientEncryptionKeyAsync(Database, string, EncryptionKeyWrapMetadata, CancellationToken)' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9534680Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionDatabaseExtensions.cs(160,27): warning CS3001: Argument type 'Database' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9537409Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionDatabaseExtensions.cs(162,39): warning CS3001: Argument type 'EncryptionKeyWrapMetadata' is not CLS-compliant [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9539496Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionContainer.cs(966,17): warning SA1515: Single-line comment should be preceded by blank line [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9543028Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionCosmosClient.cs(205,58): warning SA1202: 'public' members should come before 'protected' members [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9546807Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionKeyStoreProviderImpl.cs(74,32): warning SA1202: 'public' members should come before 'private' members [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9549111Z          D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\EncryptionQueryDefinition.cs(13,18): warning SA1201: A constructor should not follow a property [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9551203Z          CSC : warning SA0001: XML comment analysis is disabled due to project configuration [D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\src\Microsoft.Azure.Cosmos.Encryption.csproj]
2022-10-25T23:57:01.9552279Z 
2022-10-25T23:57:01.9553236Z     32 Warning(s)
2022-10-25T23:57:01.9554134Z     0 Error(s)
2022-10-25T23:57:01.9554661Z 
2022-10-25T23:57:01.9555374Z Time Elapsed 00:03:22.03
2022-10-25T23:57:02.1190653Z ##[error]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1
2022-10-25T23:57:08.2319819Z Result Attachments will be stored in LogStore
2022-10-25T23:57:08.4165822Z Run Attachments will be stored in LogStore
2022-10-25T23:57:08.6342066Z ##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
2022-10-25T23:57:08.6357970Z Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
2022-10-25T23:57:08.6362975Z ##[error]Dotnet command failed with non-zero exit code on the following projects : D:\a\1\s\Microsoft.Azure.Cosmos.Encryption\tests\EmulatorTests\Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj
2022-10-25T23:57:08.6652574Z ##[section]Async Command Start: Publish test results
2022-10-25T23:57:12.6932548Z Publishing test results to test run '1132112'.
2022-10-25T23:57:12.6977821Z TestResults To Publish 33, Test run id:1132112
2022-10-25T23:57:12.7039607Z Test results publishing 33, remaining: 0. Test run id: 1132112
2022-10-25T23:57:14.9922827Z Published Test Run : https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_TestManagement/Runs?runId=1132112&_a=runCharts
2022-10-25T23:57:16.6539292Z Flaky failed test results are opted out of pass percentage
2022-10-25T23:57:16.7263877Z ##[section]Async Command End: Publish test results
2022-10-25T23:57:16.7267770Z ##[section]Finishing: PREVIEW Microsoft.Azure.Cosmos.Encryption.EmulatorTests

**Comment by kirankumarkolli** [comment]
@vipulvishal-ms can you please take a look?

**Comment by Pilchie** [comment]
:eyes:

**Comment by Pilchie** [comment]
If we can't prioritize this and identify a fix within this week, we should disable these tests until we can. It unduly impacts the productivity of the entire team.
