### ISSUE TITLE
Could not cast or convert from System.DateTime to System.DateOnly

### ISSUE THREAD

**Issue by ekjuanrejon** [Azure/azure-cosmos-dotnet-v3#3578]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Attempting to reading cosmos documents.

**To Reproduce**
Update to .net 7. Change DateTime to DateOnly

**Expected behavior**
parse DateTime to DateOnly

**Actual behavior**
exception thrown

**Environment summary**
SDK Version: 3.31.2
OS Version Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment]
@ekjuanrejon Could you please give more information and a way to reproduce your problem? If this is an exception, please include the full exception details including stack trace. As it is, this Issue is not actionable.

**Comment by ealsur** [comment]
@NaluTripician Please follow up on this once/if more information becomes available

**Comment by ekjuanrejon** [comment]
Sure. Will add more information..but looks like it is down to newtonsoft.json

**Comment by ekjuanrejon** [comment]
`fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Newtonsoft.Json.JsonSerializationException: Error converting value 01/01/2023 00:00:00 to type 'System.DateOnly'. Path '[9].document.tranches[0].issueDate', line 1, position 9254.
       ---> System.ArgumentException: Could not cast or convert from System.DateTime to System.DateOnly.
         at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)         at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
         --- End of inner exception stack trace ---
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
         at Microsoft.Azure.Cosmos.CosmosJsonDotNetSerializer.FromStream[T](Stream stream)
         at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.FromStream[T](Stream stream)
         at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.FromStream[T](Stream stream)
         at Microsoft.Azure.Cosmos.CosmosSerializerCore.FromFeedStream[T](Stream stream)
         at Microsoft.Azure.Cosmos.Serializer.CosmosElementSerializer.GetResourcesHelper[T](IReadOnlyList`1 cosmosElements, CosmosSerializerCore serializerCore, CosmosSerializationFormatOptions cosmosSerializationOptions)
         at Microsoft.Azure.Cosmos.Serializer.CosmosElementSerializer.GetResources[T](IReadOnlyList`1 cosmosArray, CosmosSerializerCore serializerCore)
         at Microsoft.Azure.Cosmos.QueryResponse`1..ctor(HttpStatusCode httpStatusCode, IReadOnlyList`1 cosmosElements, CosmosQueryResponseMessageHeaders responseMessageHeaders, CosmosDiagnostics diagnostics, CosmosSerializerCore serializerCore, CosmosSerializationFormatOptions serializationOptions, RequestMessage requestMessage)
         at Microsoft.Azure.Cosmos.QueryResponse`1.CreateResponse[TInput](QueryResponse cosmosQueryResponse, CosmosSerializerCore serializerCore)
         at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.CreateQueryFeedResponseHelper[T](ResponseMessage cosmosResponseMessage)
         at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.CreateQueryFeedUserTypeResponse[T](ResponseMessage responseMessage)
         at Microsoft.Azure.Cosmos.FeedIteratorCore`1.ReadNextAsync(ITrace trace, CancellationToken cancellationToken)
         at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](ITrace trace, Func`2 task, Func`2 openTelemetry, String operationName, RequestOptions requestOptions)
         at Microsoft.Azure.Cosmos.ClientContextCore.OperationHelperWithRootTraceAsync[TResult](String operationName, RequestOptions requestOptions, Func`2 task, Func`2 openTelemetry, TraceComponent traceComponent, TraceLevel traceLevel`

**Comment by ekjuanrejon** [comment]
document looks like the following: was created using DateTime with .net 6

{
	"issueDate": "2022-09-01T00:00:00",
	"maturityDate": "2023-02-23T00:00:00"
}

**Comment by ealsur** [comment]
@ekjuanrejon What is the Type you are trying to deserialize it to?

**Comment by ekjuanrejon** [comment]
DateTime to DateOnly

**Comment by ealsur** [comment]
@ekjuanrejon I am referring to the C# type you are using to model the query results? Which are the properties and which are their types? We need to be able to reproduce the issue in order to understand where the problem is and if it's at all related to the code in this repository or rather (most probably) a Newtonsoft.Json behavior.

**Comment by ekjuanrejon** [comment]
the model was written using DateTime... with .net 6. Now with .net 7 changed to date only

**Comment by ealsur** [comment]
@NaluTripician I believe this would have enough information to attempt to repro

**Comment by NaluTripician** [comment]
@ekjuanrejon since the value is a `DateTime` value it cannot be directly converted into a DateOnly value. To do this you must use the `DateOnly.FromDateTime` [method](https://learn.microsoft.com/en-us/dotnet/api/system.dateonly.fromdatetime?view=net-7.0).  If the `FromDateTime` method does not solve the problem could you please provide me with the method call that is causing the error to help continue my investigation.

**Comment by ekjuanrejon** [comment]
@NaluTripician 

I'm using the following methods from the sdk

` var itemResponse = await _container
                .ReadItemAsync<CosmosDocument>(id, id)
                .ConfigureAwait(false);
				
var query = _container
                .GetItemLinqQueryable<CosmosDocument>()
                .Where(r => r.Status == 15);`

**Comment by ekjuanrejon** [comment]
https://github.com/JamesNK/Newtonsoft.Json/releases/tag/13.0.2

supports dateonly & date time. i've tried to use 13.0.2 but the problem persists

sdk is using 10.0.2
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj#L115

**Comment by ealsur** [comment]
@ekjuanrejon One correction, SDK has a nuget dependency of >= 10.0.2, which means it will use 10.0.2 but if your app defines a higher version, it will use it, so you can add the 13.0.2 version to your app and the SDK will use that.

**Comment by NaluTripician** [comment]
@ekjuanrejon I believe I know what the problem is and possible way to fix it. 

The problem here occurred because you changed your model from using the `DateTime` class to the `DateOnly` class. Because your previous model was using the `DateTime` class, your old data that is stored in Cosmos still uses the `DateTime` format. Take this for example:
### Model in C#
```
public class Document
{
    public string? id { get; set; }
    public DateTime startTime { get; set; }
    public DateTime endTime { get; set; }
}
```

### Cosmos Data 
```
{
    "id": "time1",
    "startTime": "2022-11-29T07:36:55.4843314-08:00",
    "endTime": "2022-11-29T07:37:00.4989767-08:00",
    "_rid": "cc9AAJv5GKKBhB4AAAAAAA==",
    "_self": "dbs/cc9AAA==/colls/cc9AAJv5GKI=/docs/cc9AAJv5GKKBhB4AAAAAAA==/",
    "_etag": "\"0100b147-0000-0700-0000-6386271e0000\"",
    "_attachments": "attachments/",
    "_ts": 1669736222
}
```

Now that you are using `DateOnly` in place of `DateTime` in your model, when Newtonsoft tries to deserialize it, it fails as a `DateTime` object cannot be cast into a `DateOnly` object.  This is something the occurs in both .NET 6 and .NET 7. There is a way to avoid this problem by writing a custom deserializer for your model. Here is the bare-bones one that I wrote which allowed me to read the `DateTime` item stored in Cosmos using a new model which used `DateOnly`

### New Model + Deserializer

```
public class Document
{
    public string? id { get; set; }
    [JsonConverter(typeof(CustomDeserializer))]
    public DateOnly startTime { get; set; }
    [JsonConverter(typeof(CustomDeserializer))]
    public DateOnly endTime { get; set; }
}

public class CustomDeserializer : DateTimeConverterBase
    {
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            return existingValue;
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }
    }
        
```

While this does fix the issue other things to consider is if `DateOnly` is the best type to use for your model as you were using `DateTime` previously and `DateOnly` would cause a loss of data. But please let me know if this resolves your issue.

**Comment by ealsur** [comment]
Thanks @NaluTripician for the detailed outcome. @ekjuanrejon I believe your question is answered and solution provided, let us know otherwise.
