### ISSUE TITLE
Cross Partition Order By Failing with _rid not defined exception

### ISSUE THREAD

**Issue by krispenner** [Azure/azure-cosmos-dotnet-v3#3608]
I am hitting the exception thrown at this line:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6b1fa035cdb50201aa7483cc3774eb0b521e8a47/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByQueryResult.cs#L58

When I execute this query:

```sql
SELECT * FROM (SELECT VALUE d.item FROM d WHERE d.tenant = "xtenant" AND d.store = "xstore" AND d.kind = "xkind" AND d.container = "xcontainer" AND d.type = "xtype") c ORDER BY c.CreatedDateTime
```

**Underlying object does not have an '_rid' or '__sys_rid' field.'**

```
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CrossPartition.OrderBy.OrderByQueryResult.get_Rid()
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CrossPartition.OrderBy.OrderByCrossPartitionQueryPipelineStage.MoveNextAsync_DrainPageAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CrossPartition.OrderBy.OrderByCrossPartitionQueryPipelineStage.MoveNextAsync(ITrace trace)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.SkipEmptyPageQueryPipelineStage.<MoveNextAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.LazyQueryPipelineStage.<MoveNextAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.NameCacheStaleRetryQueryPipelineStage.<MoveNextAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CatchAllQueryPipelineStage.<MoveNextAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.<ReadNextAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.<ReadNextAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ClientContextCore.<RunWithDiagnosticsHelperAsync>d__39`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Cosmos.ClientContextCore.<OperationHelperWithRootTraceAsync>d__30`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

Can someone please explain why that is and what I can do to resolve it? This same query works fine in the Azure Cosmos DB portal data explorer.

Thank you.

**Comment by neildsh** [comment]
Thanks for reporting this @krispenner . We will take a look and try to see what is happening.

**Comment by krispenner** [comment]
@neildsh any update to share? I assume my inner `SELECT VALUE` is somehow conflicting with the query re-writing that the client SDK is trying to wrap my query in.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6b1fa035cdb50201aa7483cc3774eb0b521e8a47/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByQueryResult.cs#L13-L14

**Comment by krispenner** [comment]
@ealsur I know you do a lot of Cosmos DSK development, can you please help? We have tens of thousands of items to retrieve and we just want the most recent 100 so we require sorting to work.

**Comment by ealsur** [comment]
@krispenner sadly this is a bit outside of my area of expertise. @neildsh, are there any findings around this issue that can be shared? Could this be a problem with the query itself?

**Comment by krispenner** [comment]
@neildsh please help. Is there any way to just disable or bypass the query re-writing by the client SDK? I don't know why the `r._rid` field is required but this query re-writing is really breaking our code.

**Comment by neildsh** [comment]
Hello @krispenner , I apologize for my late response. This is a bug in the query rewriting logic. However, to unblock yourself, can you use the following query instead:

```
SELECT VALUE d.item
FROM d
WHERE d.tenant = "xtenant"
     AND d.store = "xstore"
     AND d.kind = "xkind"
     AND d.container = "xcontainer"
     AND d.type = "xtype"
ORDER BY d.CreatedDateTime```

**Comment by krispenner** [comment]
Hi @neildsh, we are also performing our own query re-writing in a generic data access client. We accept a query like:
```sql
SELECT * FROM c ORDER BY c.CreatedDateTime
```
and inject
```sql
(SELECT VALUE d.item FROM d WHERE d.tenant = "xtenant" AND d.store = "xstore" AND d.kind = "xkind" AND d.container = "xcontainer" AND d.type = "xtype")
```
into it to ensure we only return data for the tenant of the current request and some other filter restrictions applied. The client calling via our data access is not aware of this and treats their SQL query as if it's acting on the outer properties of the document, but in fact all their properties are on an inner `item` property on the document.

It also needs to handle outer `WHERE` clauses, so trying to make that work dynamically is not trivial without this subquery injection approach. For example, if the client sends:
```sql
SELECT * FROM c WHERE c.Breed = "Poddle" ORDER BY c.CreatedDateTime
```
the actual result query after our injection code would be:

```sql
SELECT * FROM (SELECT VALUE d.item FROM d WHERE d.tenant = "xtenant" AND d.store = "xstore" AND d.kind = "xkind" AND d.container = "xcontainer" AND d.type = "xtype") c WHERE c.Breed = "Poddle" ORDER BY c.CreatedDateTime
```

Our document structure looks like this:
```json
{
   "id": "1",
   "tenant": "tenant1",
   "store": "MyFarm", 
   "kind": "data", 
   "container": "animals", 
   "type": "Dog", 
   "item": {
        "Id": "ajdfuf83",
        "Name": "Rex",
        "Breed": "Poodle",
        "CreatedDateTime": "2021-02-16T12:00:00:00"
    }
}
```

I don't see how to make this work dynamically without injecting our own `(SELECT VALUE d.item...)` into it. What would be some other options for me? Do you see a different way I can manage our query re-writing to make this work? Maybe I can use a Azure REST API to call Cosmos directly with my raw query and not use the SDK for cross partition queries? That seems a bit extreme but may be required.

**Comment by neildsh** [comment]
@krispenner I think it depends on how complex the query that you receive from your clients is. For example, can that query contain subqueries or aggregations? Also, note that officially CosmosDB supports only [correlated subqueries](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/subquery). Would it be possible to tighten the contract with your clients to accept more strongly typed objects rather than free form SQL text ?

**Comment by krispenner** [comment]
@neildsh I am not able to tighten our contracts with our clients. The data the clients store is dynamic and not know to us. 

Has this bug been scheduled yet to be fixed in the SDK? Is there any ETA you can share?

**Comment by krispenner** [comment]
@neildsh any update?

**Comment by neildsh** [comment]
Hello @krispenner, my apologies for the late response - I dont work much on the sdk anymore. When I mentioned that this was a bug in the sdk, I meant that the sdk should throw a BadRequestException when given a query like yours. Fixing this will not make your query start working.

Disabling SDK rewriting will not help you because it will lead to incorrect results. The reason the SDk rewrites the queries is so that it can correctly combine partial results across continuations or across partitions.

What I meant by tightening the contract was to get some kind of structured query object instead of free form SQL which is difficult to parse and very error prone to bind.

Having said that, I am trying to check if there are any options by changing how you currently rewrite the query.

If that fails, the big hammer would be to use the [managed parser](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Query/Core/Parser/SqlQueryParser.cs) but that only does parsing and not binding, and comes with its own set of warts.

**Comment by krispenner** [comment]
Hi @neildsh, thank you for the above suggestion. I will use your join suggestion and perform some very basic SQL parsing to avoid the subquery if I detect that the query is a cross-partition order by, otherwise I will continue to use the subquery.

Are there other commands other that ORDER BY that can cause this `_rid` issue?

```cs
var isCrossPartitionOrderBy = query.Contains(" ORDER BY ", StringComparison.OrdinalIgnoreCase) && query.PartitionKeys.Count == 0;
```

For now, all the cross partition order queries are very basic, so I'm parsing the query then with a regular expression and building the join you suggested. The managed parser looks like more effort that I don't have time for right now.

I still think it's shame the SDK can't detect the subquery and somehow work around it with either a sub-subquery or the join you suggested. 

Just let me know if other commands can cause this please and I can look into handling them with your join suggestion as well.

Thank you so much!

**Comment by neildsh** [comment]
Hello @krispenner , this issue is not restricted to `_rid`. You will hit this anytime the query rewrite has a projection that does not line up with your subquery.  Thus, you will see this on ORDER BY, GROUP BY, DISTINCT etc. You can check this by adding your own test cases to [QueryPlanBaselineTests](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanBaselineTests.cs) and taking a look at the rewritten query in the output xml file.

I agree that the SDK not handling distribution with the subqueries is a shortcoming. This has to do with the way the query pipeline is structured. There is an initiative to fix this (here's a [sample change](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3988) for this), but it is a big change to the architecture and will take a long time to implement.

**Comment by neildsh** [comment]
Hello @krispenner, I am closing this issue for now since I believe that I have addressed all the questions raised. Feel free to reopen if you have more questions.
