### ISSUE TITLE
COSMOSDB - Unable to query with newly generated resourcetoken (.NET)

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-cosmos-dotnet-v3#3657]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#33545](https://github.com/Azure/azure-sdk-for-net/issues/33545).

## Details

- **Package Name**: Microsoft.Azure.Cosmos
- **Package Version**: 3.12.0
- **Operating system**: Windows

- Is the bug related to **documentation** in
  - [ ] SDK API docs on [MS Docs](https://learn.microsoft.com/en-us/azure/cosmos-db/secure-access-to-data?tabs=using-primary-key#resource-tokens)

**Describe the bug**
Unable to perform CRUD with newly generated resource token with ALL permissions.

```
private async Task RefreshResourceToken(String user, PermissionMode permission)
        {
            CosmosClient client = new CosmosClient(Program.EndpointUri, Program.PrimaryKey, new CosmosClientOptions() { ApplicationName = "CosmosDBDotnetQuickstart" });
            Database db = client.GetDatabase(this.databaseId);
            User userId = db.GetUser(user);
            Container container = db.GetContainer(this.containerId);

            PermissionResponse permissionResponse;
            PermissionProperties permissionPropertiesproperties = new(
                        id: "permission01read",
                        permissionMode: permission,
                        container: container
                        );

            //permissionResponse = await userId.CreatePermissionAsync(permissionPropertiesproperties);
            permissionResponse = await userId.UpsertPermissionAsync(permissionPropertiesproperties);
            this.ResourceToken = permissionResponse.Resource.Token;
            
            this.cosmosClient = new CosmosClient(accountEndpoint: Program.EndpointUri, authKeyOrResourceToken: this.ResourceToken);
            await this.CreateDatabaseAsync();
            await this.CreateContainerAsync();
            await this.ScaleContainerAsync();
        }
```

**To Reproduce**
1. Created a user,
2. Created Permission with read or ALL permission,
3. From permission fetched the resource token, stored it.
4. Using the resource token, create cosmos client and use it with the permissions it has.
5. Once the resource token expires, create another resource token as shown in the function, with ALL permissions.
6. Unable to query because of the following issue: 
```
Reason: (**Insufficient permissions provided in the authorization header for the corresponding request. Please retry with another authorization header.**
ActivityId: 6c04888e-ded2-4723-a576-51c3a4ef5958, Microsoft.Azure.Documents.Common/2.14.0, Please see CosmosDiagnostics, Windows/10.0.22621 cosmos-netstandard-sdk/3.11.4);
```

**Expected behavior**
Should be able to perform CRUD with the newly generated resource token.

**Comment by iprashantp** [comment]
Issue is happening with version 3.31.2 as well.
Full stack trace
```
Forbidden error occurred: Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: Forbidden (403); Substatus: 0; ActivityId: <activityId>; Reason: (Insufficient permissions provided in the authorization header for the corresponding request. Please retry with another authorization header.
ActivityId: <activityId>, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, Windows/10.0.22621 cosmos-netstandard-sdk/3.29.4);
   at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
   at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.GetMasterAddressesViaGatewayAsync(DocumentServiceRequest request, ResourceType resourceType, String resourceAddress, String entryUrl, Boolean forceRefresh, Boolean useMasterCollectionResolver)
   at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.ResolveMasterAsync(DocumentServiceRequest request, Boolean forceRefresh)
   at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.TryGetAddressesAsync(DocumentServiceRequest request, PartitionKeyRangeIdentity partitionKeyRangeIdentity, ServiceIdentity serviceIdentity, Boolean forceRefreshPartitionAddresses, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.AddressResolver.ResolveAddressesAndIdentityAsync(DocumentServiceRequest request, Boolean forceRefreshPartitionAddresses, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.AddressResolver.ResolveAsync(DocumentServiceRequest request, Boolean forceRefreshPartitionAddresses, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Routing.GlobalAddressResolver.ResolveAsync(DocumentServiceRequest request, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.AddressSelector.ResolveAddressesAsync(DocumentServiceRequest request, Boolean forceAddressRefresh)
   at Microsoft.Azure.Documents.AddressSelector.ResolveAllTransportAddressUriAsync(DocumentServiceRequest request, Boolean includePrimary, Boolean forceRefresh)
   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicasInternalAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)
   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicaAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)
   at Microsoft.Azure.Documents.QuorumReader.ReadQuorumAsync(DocumentServiceRequest entity, Int32 readQuorum, Boolean includePrimary, ReadMode readMode)
   at Microsoft.Azure.Documents.QuorumReader.ReadStrongAsync(DocumentServiceRequest entity, Int32 readQuorumValue, ReadMode readMode)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass31_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy, Func`2 prepareRequestAsyncDelegate)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
```

**Comment by ealsur** [comment]
@iprashantp The exception seems to be truncated. Can you share the `ToString()` of it?

Also, the code snippet does not show you are performing Data Plane CRUD (on items), but rather a CreateDatabase call. You are creating Permissions assigned to a Container level, they cannot perform Database level operations.

**Comment by iprashantp** [comment]
I was trying to do database level operations with container level permissions. Hence facing the issues.

**Comment by ealsur** [comment]
By definition that would not work, right? Your permissions are scoped to a Container, if you are trying to do operations outside of the Container (for example, creating a Database), that should fail and it's expected, because the scope is outside the Container you selected, isn't it?

**Comment by iprashantp** [comment]
Thanks. We can close this one.
