### ISSUE TITLE
Open Telemetry: Tests fail in preview mode

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#3693]
When running the emulator tests on preview mode, the Listener tests fail:

dotnet.exe test D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.EmulatorTests\Microsoft.Azure.Cosmos.EmulatorTests.csproj --filter "TestCategory!=Quarantine & TestCategory!=Functional & TestCategory!=Query & TestCategory!=ReadFeed & TestCategory!=Batch & TestCategory!=ChangeFeed" --verbosity normal --configuration Release /p:OS=Windows /p:IsPreview=true

Failed ItemIterator [24 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<Client>. Actual:<Internal>.  Actual Kind is Internal but expected is Client for Operation.CreateDatabaseAsync
  Stack Trace:
     at Microsoft.Azure.Cosmos.Tracing.AssertActivity.IsValid(Activity activity) in D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.EmulatorTests\Tracing\AssertActivity.cs:line 19
   at Microsoft.Azure.Cosmos.Tests.CustomListener.OnNext(KeyValuePair`2 value) in D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.EmulatorTests\Tracing\CustomListener.cs:line 70
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Azure.Core.Pipeline.DiagnosticScope.ActivityAdapter.Dispose() in D:\a\1\s\Microsoft.Azure.Cosmos\src\OSS\Azure.Core\DiagnosticScope.cs:line 339
   at Microsoft.Azure.Cosmos.Telemetry.OpenTelemetryCoreRecorder.Dispose() in D:\a\1\s\Microsoft.Azure.Cosmos\src\Telemetry\OpenTelemetry\OpenTelemetryCoreRecorder.cs:line 155
   at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](String containerName, String databaseName, OperationType operationType, ITrace trace, Func`2 task, Func`2 openTelemetry, String operationName, RequestOptions requestOptions) in D:\a\1\s\Microsoft.Azure.Cosmos\src\Resource\ClientContextCore.cs:line 547
   at Microsoft.Azure.Cosmos.ClientContextCore.OperationHelperWithRootTraceAsync[TResult](String operationName, String containerName, String databaseName, OperationType operationType, RequestOptions requestOptions, Func`2 task, Func`2 openTelemetry, TraceComponent traceComponent, TraceLevel traceLevel) in D:\a\1\s\Microsoft.Azure.Cosmos\src\Resource\ClientContextCore.cs:line 264
   at Microsoft.Azure.Cosmos.SDK.EmulatorTests.BaseCosmosClientHelper.TestInit(Boolean validateSinglePartitionKeyRangeCacheCall, Action`1 customizeClientBuilder, String accountEndpointOverride) in D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.EmulatorTests\Utils\BaseCosmosClientHelper.cs:line 33
   at Microsoft.Azure.Cosmos.SDK.EmulatorTests.CosmosItemTests.TestInitialize() in D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.EmulatorTests\CosmosItemTests.cs:line 60

**Comment by MarcelWouters** [comment]
@sourabh1007  is Open Telemetry already available? I cannot find any documentation how to enable this.

**Comment by sourabh1007** [comment]
Its available in private preview mode. It's not publicly available yet. It latest preview package, we have a feature flag  _IsDistributedTracingEnabled_ which is enabled by default. With open telemetry, you can enable it with below code snippet

```
AppContext.SetSwitch("Azure.Experimental.EnableActivitySource", true);

 Sdk.CreateTracerProviderBuilder()
                .AddCustomOtelExporter() // use any exporter here
                .AddSource("Azure.Cosmos.Operation")
                .Build();
```

You can have a taste of it and feel free to create bug/feature request.

**Comment by MarcelWouters** [comment]
Thanks @sourabh1007

**Comment by ealsur** [comment]
Release builds keep failing https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=45276&view=logs&j=c06cc8f3-5abf-5ba0-4e17-574388acf50c&t=14bcbd74-ab09-58b5-1be4-bf3bdfbc0ee7
