### ISSUE TITLE
IndexOutOfRange exception occured in HttpResponseHeadersWrapper ctor, while doing cosmosException.ToString()

### ISSUE THREAD

**Issue by akashperfect** [Azure/azure-cosmos-dotnet-v3#3765]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
When trying to log cosmos exception, doing cosmosException.ToString() is causing IndexOutOfRangeException and stackTrace points out to HttpResponseHeadersWrapper ctor.

Stack Trace:
```
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.Azure.Cosmos.HttpResponseHeadersWrapper..ctor(HttpResponseHeaders responseHeaders, HttpContentHeaders httpContentHeaders)
   at Microsoft.Azure.Cosmos.Tracing.TraceData.SummaryDiagnostics.AggregateGatewayStatistics(IReadOnlyList`1 httpResponseStatisticsList)
   at Microsoft.Azure.Cosmos.Tracing.TraceData.SummaryDiagnostics.CollectSummaryFromTraceTree(ITrace currentTrace)
   at Microsoft.Azure.Cosmos.Tracing.TraceData.SummaryDiagnostics.CollectSummaryFromTraceTree(ITrace currentTrace)
   at Microsoft.Azure.Cosmos.Tracing.TraceData.SummaryDiagnostics.CollectSummaryFromTraceTree(ITrace currentTrace)
   at Microsoft.Azure.Cosmos.Tracing.TraceData.SummaryDiagnostics.CollectSummaryFromTraceTree(ITrace currentTrace)
   at Microsoft.Azure.Cosmos.Tracing.TraceData.SummaryDiagnostics.CollectSummaryFromTraceTree(ITrace currentTrace)
   at Microsoft.Azure.Cosmos.Tracing.TraceData.SummaryDiagnostics.CollectSummaryFromTraceTree(ITrace currentTrace)
   at Microsoft.Azure.Cosmos.Tracing.TraceData.SummaryDiagnostics.CollectSummaryFromTraceTree(ITrace currentTrace)
   at Microsoft.Azure.Cosmos.Tracing.TraceData.SummaryDiagnostics.CollectSummaryFromTraceTree(ITrace currentTrace)
   at Microsoft.Azure.Cosmos.Tracing.TraceWriter.TraceJsonWriter.WriteTrace(IJsonWriter writer, ITrace trace, Boolean isRootTrace)
   at Microsoft.Azure.Cosmos.Diagnostics.CosmosTraceDiagnostics.ToJsonString()
   at Microsoft.Azure.Cosmos.CosmosException.ToStringHelper(StringBuilder stringBuilder)
   at Microsoft.Azure.Cosmos.CosmosException.ToString()
```

**To Reproduce**
This happens when there are high number of calls and multiple threads are trying to log cosmos exception.

**Expected behavior**
No such exception should be thrown when trying to do CosmosException.ToString()

**Actual behavior**
System.IndexOutOfRangeException is thrown when trying to do CosmosException.ToString()

**Environment summary**
SDK Version: 3.31.2
OS Version (e.g. Windows, Linux, MacOSX) Linux

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).
Stack Trace is attached above.

**Comment by ealsur** [comment]
Related to 

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/d41f0995618cb344fcaf3c16e002960493aaa016/Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs#L73-L86

Creating a `HttpResponseHeadersWrapper` just to obtain the SubStatusCode seems to be the potential problem.

There must be a way to obtain the SubStatusCode in a read-only manner without needing to create the `HttpResponseHeadersWrapper`, we just need to read `WFConstants.BackendHeaders.SubStatus` from `httpResponseStatistics.HttpResponseMessage.Headers`.

@kundadebdatta Could you take a look?
