### ISSUE TITLE
Format exception when using culture and partitionKey, difference between Windows and Linux

### ISSUE THREAD

**Issue by mlankamp** [Azure/azure-cosmos-dotnet-v3#3796]
**Describe the bug**
We see different behavior between running queries on Linux versus Windows, when using culture Info and partition key/cross-partition key queries.

**To Reproduce**
```C#
using Microsoft.Azure.Cosmos.Fluent;
using Microsoft.Azure.Cosmos;
using Newtonsoft.Json;

namespace ConsoleApp1;

internal class Program
{
    static void Main(string[] args)
    {
        var client = new CosmosClientBuilder("---url---", "---key---").Build();
        var container = client.GetContainer("--database--", "--container--");

        Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");

        // Retrieves data
        var noCultureWithPartitionKey = container.GetItemLinqQueryable<QueryObject>(true, null, new QueryRequestOptions() { PartitionKey = new PartitionKey("bc7df108-4c93-4534-ba32-167d77274511") })
            .Where(c => c.Area > 5.65252);
        Console.WriteLine(noCultureWithPartitionKey.Count());

        // Retrieves data, cross partition
        var noCultureNoPk = container.GetItemLinqQueryable<QueryObject>(true, null, new QueryRequestOptions() { PartitionKey = null })
            .Where(c => c.Area > 5.65252);
        Console.WriteLine(noCultureNoPk.Count());

        // Change the culture
        Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("fr-FR");

        // Throws error
        try
        {
            var withCultureWithPartitionKey = container.GetItemLinqQueryable<QueryObject>(true, null, new QueryRequestOptions() { PartitionKey = new PartitionKey("bc7df108-4c93-4534-ba32-167d77274511") })
                .Where(c => c.Area > 5.65252);
            Console.WriteLine(withCultureWithPartitionKey.Count());
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }

        // Same query, cross partition
        var withCultureNoPk = container.GetItemLinqQueryable<QueryObject>(true, null, new QueryRequestOptions() { PartitionKey = null })
            .Where(c => c.Area > 5.65252);
        Console.WriteLine(withCultureNoPk.Count());
    }
}

class QueryObject{

    [JsonProperty("id")]
    public string Id{ get; set; }

    [JsonProperty("partitionKey")]
    public string PartitionKey { get; set; }

    [JsonProperty("area")]
    public double Area{ get; set; }
}
```

Results on *Windows*:
```
10
240193
10
240193
```

Results on *Linux*:
```
10
240193
Input string was not in a correct format.
240193
```

**Expected behavior**
Same behavior when running on Windows/Linux/Docker, independent on the thread culture.

**Actual behavior**
We are running a docker container with an webapi which uses request localization based on the accept language header. Customers from Norway, France are running into problems, because of the "Input string was not in a correct format." exception (all our queries are on a specific partition key). 

**Environment summary**
SDK Version: 2.32.3
OS Version Windows vs Linux (Ubuntu) vs Official Docker images

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by mlankamp** [comment]
Looks to be the same behaviour as #542, but only happens on Linux and not cross-partition

**Comment by ealsur** [comment]
@mlankamp Can you share the full stacktrace exception that happens on the non-LINQ scenario?

**Comment by mlankamp** [comment]
Using the following code:
```c#
var options = new QueryRequestOptions() { PartitionKey = new PartitionKey("bc7df108-4c93-4534-ba32-167d77274511") };
var withCultureWithPartitionKey = container.GetItemQueryIterator<QueryObject>("SELECT * FROM c WHERE c.area > 5.65252", null, options);
while (withCultureWithPartitionKey.HasMoreResults) {

    var response = await withCultureWithPartitionKey.ReadNextAsync();
    Console.WriteLine(response.Count);
}
```
gives the following error:
```
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll: 'Input string was not in a correct format.'
Stack trace:
 >   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.GetNumber64ValueFromNode(IParseTree parseTree)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitLiteral(LiteralContext context)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitLiteralScalarExpression(LiteralScalarExpressionContext context)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitUnary_scalar_expression(Unary_scalar_expressionContext context)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitBinary_scalar_expression(Binary_scalar_expressionContext context)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitBinary_scalar_expression(Binary_scalar_expressionContext context)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitLogical_scalar_expression(Logical_scalar_expressionContext context)
 >   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitWhere_clause(Where_clauseContext context)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.CstToAstVisitor.VisitSql_query(Sql_queryContext context)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.SqlQueryParser.Monadic.Parse(String text)
 >   at Microsoft.Azure.Cosmos.Query.Core.Parser.SqlQueryParser.TryParse(String text, SqlQuery& sqlQuery)
 >   at Microsoft.Azure.Cosmos.Query.Core.ExecutionContext.CosmosQueryExecutionContextFactory.<TryCreateCoreContextAsync>d__6.MoveNext()
 >   at Microsoft.Azure.Cosmos.Query.Core.AsyncLazy`1.<GetValueAsync>d__7.MoveNext()
 >   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.LazyQueryPipelineStage.<MoveNextAsync>d__8.MoveNext()
 >   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.NameCacheStaleRetryQueryPipelineStage.<MoveNextAsync>d__10.MoveNext()
 >   at Microsoft.Azure.Cosmos.Query.Core.Pipeline.CatchAllQueryPipelineStage.<MoveNextAsync>d__1.MoveNext()
 >   at Microsoft.Azure.Cosmos.Query.QueryIterator.<ReadNextAsync>d__14.MoveNext()
 >   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.<ReadNextAsync>d__8.MoveNext()
 >   at Microsoft.Azure.Cosmos.ClientContextCore.<RunWithDiagnosticsHelperAsync>d__40`1.MoveNext()
 >   at Microsoft.Azure.Cosmos.ClientContextCore.<OperationHelperWithRootTraceAsync>d__30`1.MoveNext()
 >   at ConsoleApp1.Program.<Main>d__0.MoveNext() in C:\source\repos\ConsoleApp1\Program.cs:line 25
```

**Comment by mlankamp** [comment]
Maybe https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f262f8941f541332509eba64a2297e9d5e221675/Microsoft.Azure.Cosmos/src/Query/Core/Parser/CstToAstVisitor.cs#L966
should be:

```c# 
number64 = double.Parse(text, CultureInfo.InvariantCulture);
```

**Comment by mlankamp** [comment]
Did some testing, in versions <= 3.12.0 the problem isn't present.

**Comment by mlankamp** [comment]
Maybe this helps to find the problem. When I use the query, but make the partition part of the query it works:

```c#
var options = new QueryRequestOptions() { PartitionKey = null) };

var withCultureWithPartitionKey = container.GetItemQueryIterator<QueryObject>("SELECT * FROM c WHERE c.area > 5.65252 and c.partitionKey='bc7df108-4c93-4534-ba32-167d77274511'", null, options);
while (withCultureWithPartitionKey.HasMoreResults) {

    var response = await withCultureWithPartitionKey.ReadNextAsync();
    Console.WriteLine(response.Count);
}
```

This causes https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f262f8941f541332509eba64a2297e9d5e221675/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs#L191 to not call the `SqlQueryParser` which doesn't result in the error

**Comment by ealsur** [comment]
Might be this line:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e41eea5ad6db54e51e953552bfccf751c0de291f/Microsoft.Azure.Cosmos/src/Query/Core/Parser/CstToAstVisitor.cs#L966

@neildsh Could you help confirm if this might be the culprit? The double.Parse not having invariant culture might be causing this exception on query parsing?

**Comment by mlankamp** [comment]
I can provide a PR (and unit-test also ) if you want
