### ISSUE TITLE
Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=7.0.0.0

### ISSUE THREAD

**Issue by LastTribunal** [Azure/azure-cosmos-dotnet-v3#3811]
Microsoft.Azure.Cosmos  3.32.3

Running in Service Fabric .net 4.8

ystem.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
  Source=Microsoft.Azure.Cosmos.Client
  StackTrace:
   at Microsoft.Azure.Cosmos.DocumentClient.Initialize(Uri serviceEndpoint, ConnectionPolicy connectionPolicy, Nullable`1 desiredConsistencyLevel, HttpMessageHandler handler, ISessionContainer sessionContainer, Nullable`1 enableCpuMonitor, IStoreClientFactory storeClientFactory, TokenCredential tokenCredential, String cosmosClientId, RemoteCertificateValidationCallback remoteCertificateValidationCallback)
   at Microsoft.Azure.Cosmos.DocumentClient..ctor(Uri serviceEndpoint, AuthorizationTokenProvider cosmosAuthorization, EventHandler`1 sendingRequestEventArgs, ConnectionPolicy connectionPolicy, Nullable`1 desiredConsistencyLevel, JsonSerializerSettings serializerSettings, ApiType apitype, EventHandler`1 receivedResponseEventArgs, HttpMessageHandler handler, ISessionContainer sessionContainer, Nullable`1 enableCpuMonitor, Func`2 transportClientHandlerFactory, IStoreClientFactory storeClientFactory, Boolean isLocalQuorumConsistency, String cosmosClientId, RemoteCertificateValidationCallback remoteCertificateValidationCallback)
   at Microsoft.Azure.Cosmos.ClientContextCore.Create(CosmosClient cosmosClient, CosmosClientOptions clientOptions)
   at Microsoft.Azure.Cosmos.CosmosClient..ctor(String accountEndpoint, AuthorizationTokenProvider authorizationTokenProvider, CosmosClientOptions clientOptions)
   at Microsoft.Azure.Cosmos.Fluent.CosmosClientBuilder.Build()
   at Configuration.SettingsFactory.CosmosDocQuery.Retrieve(String endpointUrl, String accessKey, String database, String collection, String document) in C:\Dev\eRcptMain\Configuration\SettingsFactory\CosmosDocQuery.cs:line 12
   at Configuration.AppSettingsEntry.Initialize(ConfigurationPackage configurationPackage) in C:\Dev\eRcptMain\Configuration\AppSettingsEntry.cs:line 24
   at Cache.Cache.CreateServiceReplicaListeners() in C:\Dev\eRcptMain\Cache\Services\CacheService.cs:line 37
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<OpenCommunicationListenersAsync>d__27.MoveNext()

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

**Comment by ealsur** [comment]
@LastTribunal Can you please clarify what is the ask in this Issue? 

The Cosmos DB SDK does not depend on `System.Configuration.ConfigurationManager` 7.0.0, it depends on `>=6.0.0` -> https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.32.3#dependencies-body-tab

DLL and dependency resolution is done by the application and framework. Why a certain DLL is not found at runtime or why it is attempting to load 7.0 instead of 6.0 or how does your application resolve Nuget conflicts is something that is particular to your own deployment.

**Comment by LastTribunal** [comment]
I solved this by using api.config redirects
