### ISSUE TITLE
HttpRequestException during runtime read API call

### ISSUE THREAD

**Issue by blankor1** [Azure/azure-cosmos-dotnet-v3#4006]
**Describe the bug**
A read operation failed because connection to Cosmos DB failed with a transient network error. But what we received is a HttpRequestException which looks like a TCP timeout(SocketException(10060)) not a CosmosException. The detailed exception is shown below.

But seeing from this work item (https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2093), this sort of exception should already be covered by native SDK retry policy especially for read operations. And in the exception trace there is also a "SendWithVersionDetectionAndRetryAsync()" method. So could you help confirm why we still receive this exception in our client side? 

And if this exception is expected, could you suggest a way on how to perform retries for such type of network errors? For now we only retry on the retriable CosmosException according to this doc: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/conceptual-resilient-sdk-applications

**To Reproduce**
Transient network error. Can't reproduce locally.

**Expected behavior**
Receive a CosmosException, or retry by native SDK library.

**Actual behavior**
Received a HttpRequestException.

**Environment summary**
SDK Version: 3.31.0
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
```
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (<-databaseName->.documents.azure.com:443)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Azure.Cosmos.CosmosHttpClientCore.ExecuteHttpHelperAsync(HttpRequestMessage requestMessage, ResourceType resourceType, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.CosmosHttpClientCore.SendHttpHelperAsync(Func`1 createRequestMessageAsync, ResourceType resourceType, HttpTimeoutPolicy timeoutPolicy, IClientSideRequestStatistics clientSideRequestStatistics, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.GetDatabaseAccountAsync(Func`1 requestMessage, IClientSideRequestStatistics clientSideRequestStatistics, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.DocumentClient.GetDatabaseAccountPrivateAsync(Uri serviceEndpoint, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.GetAccountPropertiesHelper.GetAndUpdateAccountPropertiesAsync(Uri endpoint)
   at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.GetAccountPropertiesHelper.GetAccountPropertiesAsync()
   at Microsoft.Azure.Cosmos.Common.AsyncCache`2.GetAsync(TKey key, TValue obsoleteValue, Func`1 singleValueInitFunc, CancellationToken cancellationToken, Boolean forceRefresh)
   at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.GetDatabaseAccountAsync(Boolean forceRefresh)
   at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.RefreshDatabaseAccountInternalAsync(Boolean forceRefresh)
   at Microsoft.A--TRUNCATED--
```

**Comment by sourabh1007** [comment]
You are getting this Socket Exception: https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2#WSAETIMEDOUT

As mentioned in https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2093#issuecomment-751697666 , We are retrying only on HttpRequestException not on SocketException ref. this code https://github.com/Azure/azure-cosmos-dotnet-v3/blob/5ec7b4bcd7e2e0698736cd374f2196682227c913/Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs#L71

These exceptions are generally transient and should not occur continuously. If it happens repeatedly, you should contact your networking team to find out the root cause. 
There is no recommendation to handle socket exception from SDK side. It is mentioned on above comment why it is not handled in SDK.
May be you can catch and retry in your application.

**Comment by sourabh1007** [comment]
can you please provide the full stack trace? and How often you are experiencing this issue?

**Comment by blankor1** [comment]
@sourabh1007 Yes, this exception is thrown during the API call. And I see there is "RefreshDatabaseAccountInternalAsync" and "SendWithVersionDetectionAndRetryAsync" method in the stack trace. But this exception still occurred during the runtime.

Not very often. For all microsevices in all environments, there is only 8 this exception in a month.

Our log is truncated. Below one is the longest one I can get for now which shows clearly that it has already retried but still thrown. (Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync)
```
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (cpc-csmsdb-alert-prod-altausse.documents.azure.com:443)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Azure.Cosmos.CosmosHttpClientCore.ExecuteHttpHelperAsync(HttpRequestMessage requestMessage, ResourceType resourceType, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.CosmosHttpClientCore.SendHttpHelperAsync(Func`1 createRequestMessageAsync, ResourceType resourceType, HttpTimeoutPolicy timeoutPolicy, IClientSideRequestStatistics clientSideRequestStatistics, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayAccountReader.GetDatabaseAccountAsync(Uri serviceEndpoint)
   at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.GetAccountPropertiesHelper.GetAndUpdateAccountPropertiesAsync(Uri endpoint)
   at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.GetAccountPropertiesHelper.GetAccountPropertiesAsync()
   at Microsoft.Azure.Cosmos.GatewayAccountReader.InitializeReaderAsync()
   at Microsoft.Azure.Cosmos.CosmosAccountServiceConfiguration.InitializeAsync()
   at Microsoft.Azure.Cosmos.DocumentClient.InitializeGatewayConfigurationReaderAsync()
   at Microsoft.Azure.Cosmos.DocumentClient.GetInitializationTaskAsync(IStoreClientFactory storeClientFactory)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`--TRUNCATED--
```

**Comment by ealsur** [comment]
@blankor1 This is an initialization error:

```
at Microsoft.Azure.Cosmos.GatewayAccountReader.InitializeReaderAsync()
   at Microsoft.Azure.Cosmos.CosmosAccountServiceConfiguration.InitializeAsync()
   at Microsoft.Azure.Cosmos.DocumentClient.InitializeGatewayConfigurationReaderAsync()
   at Microsoft.Azure.Cosmos.DocumentClient.GetInitializationTaskAsync(IStoreClientFactory storeClientFactory)
```

It means, it is happening on the first ever request a client instance is doing, and if this is happening on runtime (when you already started the app and you already had past request) it means you are not fully following the Singleton pattern.

The SDK does have retry policies in place for `HttpRequestException`:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/08981bf2fd87f110ca4a1e2af5f82974857c1aaf/Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs#L85C14-L85C14

But they apply to a running client, in this stack, the client could not even finish initializing. 

For initialization, there are some retries (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/08981bf2fd87f110ca4a1e2af5f82974857c1aaf/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L115) but they would only happen if you are specifying either `CosmosClientOptions.ApplicationPreferredRegions` or `CosmosClientOptions.ApplicationRegion`.

**Comment by sourabh1007** [comment]
@ealsur has provided analysis on the basis of the exception stacktrace. Please reopen with details if you need more information regarding this.

**Comment by blankor1** [comment]
Sorry for the late update. Thank @ealsur and @sourabh1007 for your detailed information! We will enable the CosmosClientOptions.ApplicationRegion in the future to have the retry behavior during the initialization.

I have a follow up question about this issue: 
**Does SDK client have a default timeout for this sort of HttpRequestException(SocketException(10060)? Or can we configure this timeout value in somewhere?** 

I have this question because during the Aug 30 Australia outage, we receive many HttpRequestException again in read API call. And it takes **more than 16 minutes** for the ReadItemAsync() API to hit the HttpRequestException. 
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/36236746/f30d240b-50d5-4285-a2ef-a110643f55f3)

**Comment by blankor1** [comment]
Do you see any potential reason why the HttpRequestException response time take a fluctuating and long time to be received by the service? If it's keeping retry until the maxRetryCount 120, then it should be a relatively fix range like 120*5 seconds = 600 seconds (about 10 minutes).

Also I have 3 questions regarding the timeout configuration and cancellationtoken
I see two timeout configurations:
    [CosmosClientOptions.RequestTimeout](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/83509cc173f01fc7cbf20a0eb8d06da53f5f3b94/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L228): default value 6 seconds.
    [CosmosClientOptions.OpenTcpConnectionTimeout](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/83509cc173f01fc7cbf20a0eb8d06da53f5f3b94/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L388) : default value 5 seconds.

1. What is the scope of these properties?
        For example, if one API call(ReadItemAsync) contains a request to open a TCP connection, which value will be respected? Will these timeout values also apply on the HTTP request in the above HttpRequestException case(it's underlying is still a TCP connection)? 

2. The doc xml has a mark (Direct/TCP) on the property OpenTcpConnectionTimeout. Does this mean it only apply to direct mode TCP connection? Will it still take effect if the client is in Gateway mode?

3. Can the cancellationToken guarantee to cancel a request? For example, a write request has reached the database server and has been executed, but the response timeout happened due to the network traffic, can cancellationToken cancel this write operation on the server-side?

**Comment by ealsur** [comment]
@blankor1 I don't know why HttpRequestException might take X or Y time, the failure is not driven by the SDK. SDK sets a timeout, but if you are getting HttpRequestException it is not the timeout that is firing. I have seen HttpRequestException take 60 seconds to happen, so 60x120 = 2 hs.

Please see https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-dotnet-sdk-request-timeout?tabs=cpu-new#customize-the-timeout-on-the-azure-cosmos-db-net-sdk for answers to your questions. 

One clarification, OpenTcpConnectionTimeout is, by its name, applied to TCP connections, not HTTP. There is no Open HTTP Timeout, HttpClient uses the same timeout (RequestTimeout) for both steps (connection and request). Newer .NET versions added an extra setting but they did not expose it on NETStandard. If you are customizing the HttpClient with the HttpClientFactory you might want to test setting it: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3771
