### ISSUE TITLE
Unobserved task exception on gateway failure

### ISSUE THREAD

**Issue by rinatmini** [Azure/azure-cosmos-dotnet-v3#4010]
SDK Version: 3.35.2
The failure in backend (error gateway response) causes an unobserved task exception in the background gateway cache refreshing.
Doesn't fail the application work, but lands in an observer and may trigger alerts.

Maybe related to #3994
```
[SubscribeAndLogUnhandledExceptions,LogSourceExtensions.cs(27) <NoCorrelationId>] Unobserved task exception: System.Threading.Tasks.UnwrapPromise`1[System.Threading.Tasks.VoidTaskResult] {DocumentClientException("The requested resource is no longer available
at the server. ActivityId: 1e8489e3-2cda-41fb-afce-50852a4a31b9, Request URI: /9c967a2b-7b0d-4f49-a38d-36f1391fda86/49ad7700-95bd-4037-ac52-b32664b76756, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Windows/10.0.20348 cosmos-netstandard-sdk/3.30.8") Source: 'Microsoft.Azure.Cosmos.Client'
at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.GetServerAddressesViaGatewayAsync(DocumentServiceRequest request, String collectionRid, IEnumerable`1 partitionKeyRangeIds, Boolean forceRefresh)
at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.GetAddressesForRangeIdAsync(DocumentServiceRequest request, PartitionAddressInformation cachedAddresses, String collectionRid, String partitionKeyRangeId, Boolean forceRefresh)
at Microsoft.Azure.Cosmos.AsyncCacheNonBlocking`2.AsyncLazyWithRefreshTask`1.CreateAndWaitForBackgroundRefreshTaskAsync(Func`2 createRefreshTask)
at Microsoft.Azure.Cosmos.AsyncCacheNonBlocking`2.UpdateCacheAndGetValueFromBackgroundTaskAsync(TKey key, AsyncLazyWithRefreshTask`1 initialValue, Func`2 callbackDelegate, String operationName)
at Microsoft.Azure.Cosmos.AsyncCacheNonBlocking`2.RefreshAsync(TKey key, Func`2 singleValueInitFunc)
at Microsoft.Azure.Cosmos.Routing.GatewayAddressCache.<>c__DisplayClass25_0.<<TryGetAddressesAsync>b__5>d.MoveNext() }
=== Error logged at ===
at Microsoft.Skype.Pstn.Common.Logging.LogSource.Critical(Exception exception, InterpolatedString& message) in /_/Microsoft.Skype.Pstn.Common/Logging/LogSource.cs:line 526
at Microsoft.Skype.Pstn.Common.Logging.LogSourceExtensions.<>c__DisplayClass0_0.<SubscribeAndLogUnhandledExceptions>b__1(Object sender, UnobservedTaskExceptionEventArgs args) in /_/Microsoft.Skype.Pstn.Common/Logging/LogSourceExtensions.cs:line 27
at System.Threading.Tasks.TaskExceptionHolder.Finalize()
```

**Comment by cizra** [comment]
What's the ETA with this bug?

**Comment by ealsur** [comment]
@cizra We'll triage this issue and see how it can fit with the current work already assigned to existing developers. The understanding is that this is not a critical issue, the code behavior (for better or worse) has been there for a while.

What made this an issue now? Are you experiencing a spike on Gateway interaction failures due to a Gateway availability problem?

**Comment by cizra** [comment]
No, there's no spike of misbehavior. It's just that we finally took the time to dig in and see who is generating those failures.

We have a monitor that monitors UnobservedTaskExceptions (with an urgent alert attached), so we keep getting alerts from this bug, every now and then.

**Comment by ealsur** [comment]
@cizra Could you share details (if possible) of what is the monitor that you are using to capture these unobserved exceptions? We are interested into seeing if we can add the same to our tests to fix this and other potential places.

**Comment by cizra** [comment]
@ealsur I think this should do the trick:

```csharp
            TaskScheduler.UnobservedTaskException += (sender, args) =>
            {
                log.Critical(args.Exception.Unwrap(), $"Unobserved task exception: {sender?.GetType()}");
            };
```

**Comment by cizra** [comment]
Thank you for fixing this. @ealsur when is this scheduled for release?

**Comment by ealsur** [comment]
@cizra We don't have strict release schedules, we normally release whenever new features are completed and ready for consumption or there are critical bugfixes. As far as I am aware, we are waiting on https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3934 at the moment.
