### ISSUE TITLE
Exception in ChangeFeedProcessor is swallowed

### ISSUE THREAD

**Issue by AgSync-Aaron** [Azure/azure-cosmos-dotnet-v3#405]
**Describe the bug**
When I have an exception in my onChangesDelegate on ChangeFeedProcessor it gets swallowed and the listener doesn't stop. 

**To Reproduce**
Create a change feed listener with an explicit exception and run.

**Expected behavior**
I would expect the exception to break the listener.

**Actual behavior**
The exception is swalllowed.

**Environment summary**
SDK Version:3.0.0.17-preview
OS Version (e.g. Windows, Linux, MacOSX): window 10

**Comment by AgSync-Aaron** [comment]
In a related note, if I get 100 items (default) in my change notification and processing stops half way through, can I notify the lease that I've successfully processed some (update the ContinuationToken)?

**Comment by ealsur** [comment]
@AgSync-Aaron Do you have a repro? We have tests covering the scenario of the current processor closing on exception (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionSupervisorTests.cs#L119).

**Comment by ealsur** [comment]
As a response to the question: No, the batch is either processed completely (delegate completes successfully), or not (exception happens). There is no way to notify for a partial success.

Basically the flow is:
1. FeedProcessor sends the next batch to your delegate
2. Your delegate processes changes successfully
3. Checkpoint happens, back to step 1

If you throw an exception in step 2, the lease for that partition key value will be released and then picked up by the current or another host instance. When it's picked up, it will check the last known lease update and continue from there (retry the last batch).

The only scenario where the batch might not be retried is if the batch that throws is the first ever (lease has no Continuation). Because when the host picks up the lease again to reprocess, it has no point in time to retry from.

**Comment by AgSync-Aaron** [comment]
Thank you for the response.

I'm trying to get a change feed processor working in the new .net core 3.0 worker pattern based on the `BackgroundService` class.  When there is a failure in the change feed delegate I want to stop the worker.  If there is some kind of bug in my code I don't want it running in an infinite loop and repeatedly processing the other items in the batch that don't cause an error.

How can I force the processor to stop?

I've tried the following 2 approaches and have even attempted calling the `StopAsync()` from the exception handler and I can't get anything to work. Just infinite loops.

```c#
public override async Task StartAsync(CancellationToken cancellationToken)
{
    await _changeFeedProcessor.StartAsync();
    await base.StartAsync(cancellationToken);
}

public override Task StopAsync(CancellationToken cancellationToken)
{
    await _changeFeedProcessor.StopAsync()
    return base.StopAsync(cancellationToken);
}
```
and...
```c#
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    await _changeFeedProcessor.StartAsync();
    await Task.Delay(Timeout.Infinite, stoppingToken);
    await _changeFeedProcessor.StopAsync();
}
```

**Comment by AgSync-Aaron** [comment]
Here is a sample that just runs forever...
```c#
        static async Task Main(string[] args)
        {
            Console.WriteLine("Hello World!");


            var cosmos = new CosmosClient("AccountEndpoint=https:.........");
            var db = cosmos.GetDatabase("database");
            var FeedContainer = db.GetContainer("feeder");
            var LeaseContainer = db.GetContainer("lease");

            var processor = FeedContainer.CreateChangeFeedProcessorBuilder<dynamic>("test-processor", (d, ct) =>
            {
                for (int i = 0; i < d.Count; i++)
                {
                    Console.WriteLine($"Processing item: {i} of {d.Count}");
                    if (i > 2)
                    {
                        Console.WriteLine("Throwing...");
                        throw new Exception("Testing...");
                    }
                }
                return Task.CompletedTask;
            }).WithLeaseContainer(LeaseContainer)
            .WithInstanceName(Environment.MachineName)
            .Build();

            await processor.StartAsync();

            await Task.Delay(Timeout.Infinite);
        }
```
Console output:
```
Hello World!
Processing item: 0 of 13
Processing item: 1 of 13
Processing item: 2 of 13
Processing item: 3 of 13
Throwing...
Processing item: 0 of 15
Processing item: 1 of 15
Processing item: 2 of 15
Processing item: 3 of 15
Throwing...
Processing item: 0 of 21
Processing item: 1 of 21
Processing item: 2 of 21
Processing item: 3 of 21
Throwing...
```
Output window:
```
The thread 0x4164 has exited with code 0 (0x0).
The thread 0x218c has exited with code 0 (0x0).
The thread 0x50b4 has exited with code 0 (0x0).
DocDBTrace Warning: 0 : Exception System.Exception: RequestUri: , Testing...,    at ConsoleApp3.Program.<>c.<Main>b__0_0(IReadOnlyCollection`1 d, CancellationToken ct) in C:\Users\<<snip>>\source\repos\ConsoleApp3\ConsoleApp3\Program.cs:line 30
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.ChangeFeedObserverBase`1.ProcessChangesAsync(ChangeFeedObserverContext context, IReadOnlyCollection`1 docs, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.ObserverExceptionWrappingChangeFeedObserverDecorator`1.ProcessChangesAsync(ChangeFeedObserverContext context, IReadOnlyCollection`1 docs, CancellationToken cancellationToken)
DocDBTrace Information: 0 : 2019-06-12T16:35:10.7497738Z, CorrelatedActivityId: a701bc35-af6d-4e7c-8c9a-6bbe7a1a668a | Pipelined~Context.CreateAsync
DocDBTrace Warning: 0 : Exception happened on Observer.ProcessChangesAsync
DocDBTrace Information: 0 : 2019-06-12T16:35:10.7637987Z, CorrelatedActivityId: a701bc35-af6d-4e7c-8c9a-6bbe7a1a668a, ActivityId: 00000000-0000-0000-0000-000000000000 | parallel~contextbase.initializeasync, queryspec {"query":"SELECT * FROM c WHERE STARTSWITH(c.id, 'test-processor<<snip>>.documents.azure.com_yFQqAA==_yFQqAKibR1g=..')"}, maxbuffereditemcount: 100, target partitionkeyrange count: 1, maximumconcurrencylevel: 0, documentproducer initial page size 100
DocDBTrace Information: 0 : Host '<<snip>>' 1 partitions, 1 hosts, 0 available leases, target = 1, min = 0, max = 0, mine = 1, will try to take 0 lease(s) for myself'.
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
DocDBTrace Information: 0 : Lease with token 0: renewer task stopped.
DocDBTrace Warning: 0 : Exception Microsoft.Azure.Cosmos.ChangeFeed.Exceptions.ObserverException: RequestUri: , Exception has been thrown by the Observer.,    at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.ObserverExceptionWrappingChangeFeedObserverDecorator`1.ProcessChangesAsync(ChangeFeedObserverContext context, IReadOnlyCollection`1 docs, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.AutoCheckpointer`1.ProcessChangesAsync(ChangeFeedObserverContext context, IReadOnlyCollection`1 docs, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.FeedProcessorCore`1.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedManagement.PartitionSupervisorCore`1.RunAsync(CancellationToken shutdownToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedManagement.PartitionSupervisorCore`1.RunAsync(CancellationToken shutdownToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedManagement.PartitionControllerCore.ProcessPartitionAsync(PartitionSupervisor partitionSupervisor, DocumentServiceLease lease)
DocDBTrace Warning: 0 : Exception System.Exception: RequestUri: , Testing...,    at ConsoleApp3.Program.<>c.<Main>b__0_0(IReadOnlyCollection`1 d, CancellationToken ct) in C:\Users\<<snip>>\source\repos\ConsoleApp3\ConsoleApp3\Program.cs:line 30
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.ChangeFeedObserverBase`1.ProcessChangesAsync(ChangeFeedObserverContext context, IReadOnlyCollection`1 docs, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.ObserverExceptionWrappingChangeFeedObserverDecorator`1.ProcessChangesAsync(ChangeFeedObserverContext context, IReadOnlyCollection`1 docs, CancellationToken cancellationToken)
DocDBTrace Warning: 0 : Lease with token Microsoft.Azure.Cosmos.ChangeFeed.Exceptions.ObserverException: Exception has been thrown by the Observer. ---> System.Exception: Testing...
   at ConsoleApp3.Program.<>c.<Main>b__0_0(IReadOnlyCollection`1 d, CancellationToken ct) in C:\Users\<<snip>>\source\repos\ConsoleApp3\ConsoleApp3\Program.cs:line 30
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.ChangeFeedObserverBase`1.ProcessChangesAsync(ChangeFeedObserverContext context, IReadOnlyCollection`1 docs, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.ObserverExceptionWrappingChangeFeedObserverDecorator`1.ProcessChangesAsync(ChangeFeedObserverContext context, IReadOnlyCollection`1 docs, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.ObserverExceptionWrappingChangeFeedObserverDecorator`1.ProcessChangesAsync(ChangeFeedObserverContext context, IReadOnlyCollection`1 docs, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.AutoCheckpointer`1.ProcessChangesAsync(ChangeFeedObserverContext context, IReadOnlyCollection`1 docs, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedProcessing.FeedProcessorCore`1.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedManagement.PartitionSupervisorCore`1.RunAsync(CancellationToken shutdownToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedManagement.PartitionSupervisorCore`1.RunAsync(CancellationToken shutdownToken)
   at Microsoft.Azure.Cosmos.ChangeFeed.FeedManagement.PartitionControllerCore.ProcessPartitionAsync(PartitionSupervisor partitionSupervisor, DocumentServiceLease lease): processing failed
DocDBTrace Information: 0 : Lease with token 0: released
DocDBTrace Information: 0 : 2019-06-12T16:35:23.8083034Z, CorrelatedActivityId: 7b5ea5ae-2ec0-488f-9d3b-4e615bdf94f2 | Pipelined~Context.CreateAsync
DocDBTrace Information: 0 : 2019-06-12T16:35:23.8155358Z, CorrelatedActivityId: 7b5ea5ae-2ec0-488f-9d3b-4e615bdf94f2, ActivityId: 00000000-0000-0000-0000-000000000000 | parallel~contextbase.initializeasync, queryspec {"query":"SELECT * FROM c WHERE STARTSWITH(c.id, 'test-processor<<snip>>.documents.azure.com_yFQqAA==_yFQqAKibR1g=..')"}, maxbuffereditemcount: 100, target partitionkeyrange count: 1, maximumconcurrencylevel: 0, documentproducer initial page size 100
DocDBTrace Information: 0 : Host '<<snip>>' 1 partitions, 1 hosts, 1 available leases, target = 1, min = 0, max = 0, mine = 0, will try to take 1 lease(s) for myself'.
DocDBTrace Information: 0 : Lease with token 0: acquired
DocDBTrace Information: 0 : Lease with token 0: renewer task started.
Exception thrown: 'System.Exception' in ConsoleApp3.dll
An exception of type 'System.Exception' occurred in ConsoleApp3.dll but was not handled in user code
Testing...
```

**Comment by ealsur** [comment]
The idea of the Processor is to run forever until you manually shut it down and to be resilient to transient failures, it is by design.

If your exceptions are not transient or you want to stop everything if one happens, you could simply call the StopAsync from within the delegate by catching any possible exception:

    ChangeFeedProcessor processor = null;
    processor = this.Container
        .CreateChangeFeedProcessorBuilder("test", async (IReadOnlyCollection<TestClass> docs, CancellationToken token) =>
        {
            try
            {
                throw new Exception("something happened");
            }
            catch (Exception)
            {
                await processor.StopAsync();
            }
        })
        .WithInstanceName("random")
        .WithLeaseContainer(this.LeaseContainer).Build();

    await processor.StartAsync();

There is something you need to be aware of though, you can run multiple instances of Processors for load distribution, so shutting down one instance doesn't mean the others will also shut down.

**Comment by AgSync-Aaron** [comment]
The `processor.StopAsync()` worked in this simple example. I've tried doing that in the .Net core 3 worker process, but it didn't work. I'm now pretty sure that's my issue and not a bug. I need to figure out where I went wrong.

> There is something you need to be aware of though, you can run multiple instances of Processors for load distribution, so shutting down one instance doesn't mean the others will also shut down.
I figured, but thanks for the clarification.

After I stopped the processor, it continued to renew the lease. I'll assume that's as expected.
```
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
The thread 0x6cc8 has exited with code 0 (0x0).
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
The thread 0x3b2c has exited with code 0 (0x0).
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
DocDBTrace Information: 0 : Lease with token 0: renewed lease with result True
```

Closing issue as user error. Hopefully this can help someone else with the same confusion.

**Comment by ealsur** [comment]
Maybe it would be better to instead of shutting down from inside the delegate, just signal something, that will eventually stop the worker process and stop the processor? I'm not super familiar with NET Core 3 workers, so I'm not sure how is their life cycle.

**Comment by AgSync-Aaron** [comment]
I'm learning more about them as I go. I found I am able to DI in a `IHostApplicationLifetime` and I can call `StopApplication()` 💥 to gracefully stop the service with the application.
