### ISSUE TITLE
Cannot load Cosmos.ServiceInterop.dll in MacOS

### ISSUE THREAD

**Issue by ezachariadis** [Azure/azure-cosmos-dotnet-v3#4065]
Hello,

I am new to asp.net core and cosmos db but have a lot of experience with the .Net ecosystem.

Machine: Mac M1 Pro
Latest Venture MacOS
Latest .Net 7 for ARM64

Description

I was following the official tutorial about asp.net core and cosmos db and when I tried to execute the command from Swagger this error appears

```c#
QueryPartitionProvider.TryCreateServiceProvider failed with exception System.DllNotFoundException: Unable to load shared library 'Microsoft.Azure.Cosmos.ServiceInterop.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file)
dlopen(/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib, 0x0001): tried: '/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file)
dlopen(Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib, 0x0001): tried: 'Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/usr/lib/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file, not in dyld cache), 'Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/usr/local/lib/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/usr/lib/Microsoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file, not in dyld cache)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file)
dlopen(/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib, 0x0001): tried: '/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file)
dlopen(libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib, 0x0001): tried: 'libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/usr/lib/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file, not in dyld cache), 'libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/usr/local/lib/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file), '/usr/lib/libMicrosoft.Azure.Cosmos.ServiceInterop.dll.dylib' (no such file, not in dyld cache)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/Microsoft.Azure.Cosmos.ServiceInterop.dll, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/Microsoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/Microsoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/Microsoft.Azure.Cosmos.ServiceInterop.dll' (no such file)
dlopen(/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/Microsoft.Azure.Cosmos.ServiceInterop.dll, 0x0001): tried: '/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/Microsoft.Azure.Cosmos.ServiceInterop.dll' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/Microsoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/Microsoft.Azure.Cosmos.ServiceInterop.dll' (not a mach-o file)
dlopen(Microsoft.Azure.Cosmos.ServiceInterop.dll, 0x0001): tried: 'Microsoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OSMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/usr/lib/Microsoft.Azure.Cosmos.ServiceInterop.dll' (no such file, not in dyld cache), 'Microsoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/usr/local/lib/Microsoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/usr/lib/Microsoft.Azure.Cosmos.ServiceInterop.dll' (no such file, not in dyld cache)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libMicrosoft.Azure.Cosmos.ServiceInterop.dll, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file)
dlopen(/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/libMicrosoft.Azure.Cosmos.ServiceInterop.dll, 0x0001): tried: '/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/Users/sugarhell/wkspaces/NeuroVRBackEnd/bin/Release/net7.0/libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file)
dlopen(libMicrosoft.Azure.Cosmos.ServiceInterop.dll, 0x0001): tried: 'libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/usr/lib/libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file, not in dyld cache), 'libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/usr/local/lib/libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file), '/usr/lib/libMicrosoft.Azure.Cosmos.ServiceInterop.dll' (no such file, not in dyld cache)

``` 

It seems that the query triggers that error

```c#
 public async Task<IEnumerable<Product>> RetrieveAllProductsAsync()
        {
            var queryable = Container.GetItemLinqQueryable<Product>();

            using FeedIterator<Product> feed = queryable.Where(p=>p.Price < 1000).OrderByDescending(p => p.Price).ToFeedIterator();

            List<Product> results = new List<Product>();

            while(feed.HasMoreResults){
                var response = await feed.ReadNextAsync();

                foreach (Product item in response)
                {
                    results.Add(item);
                }
            }

            return results;

        }
``` 

The DLL exists in the bin folder and in the runtime folder. I have tried to:

Reinstall .NET
Delete the bin file, clean and rebuild the project

Thank you very much for your time

**Comment by ealsur** [comment]
@ezachariadis Does the query fail to execute?

**Comment by ealsur** [comment]
Not being able to load the ServiceInterop DLL is expected and by design (https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/performance-tips-query-sdk?tabs=v3&pivots=programming-language-csharp#use-local-query-plan-generation) it is something currently only available on Windows.

However, this should not cause the query execution to fail. If it fails, please share the failure (Exception).

**Comment by ezachariadis** [comment]
> Not being able to load the ServiceInterop DLL is expected and by design (https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/performance-tips-query-sdk?tabs=v3&pivots=programming-language-csharp#use-local-query-plan-generation) it is something currently only available on Windows.
> 
> However, this should not cause the query execution to fail. If it fails, please share the failure (Exception).

Hey, yeah it fails. It returns an empty array but if I remove the Where in the query, it works again.

```c#
QueryPartitionProvider.TryCreateServiceProvider failed with exception System.DllNotFoundException: Unable to load shared library 'Microsoft.Azure.Cosmos.ServiceInterop.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 

``` 

then this piece of code executes but nothing happens

```c#
at Microsoft.Azure.Documents.ServiceInteropWrapper.CreateServiceProvider(String configJsonString, IntPtr& serviceProvider)
   at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPartitionProvider.TryCreateServiceProvider(String queryEngineConfiguration)
```

**Comment by ealsur** [comment]
> It returns an empty array 

Are you getting an empty response or are you getting an exception? If your application is getting an exception, please attach the full `ToString()` of the exception here. If you are getting an empty response, empty pages are [expected](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/pagination#query-executions), are you getting ALL empty pages until `HasMoreResults` is `false` in a loop?
