### ISSUE TITLE
TriggerOperation missing Upsert member

### ISSUE THREAD

**Issue by DavidAlexanderPerez** [Azure/azure-cosmos-dotnet-v3#4104]
**Describe the bug**
The `TriggerOperation` enum is missing an `Upsert` member. It is not currently possible to specify that a trigger should be executed on upsert operations only.

**To Reproduce**
Any enum member of `TriggerOperation` besides `All` will result in the error `Trigger 'triggerId' was defined with operation type 'Update', and therefore is invalid for 'Upsert'.`

```cs
Container container = await database.CreateContainerIfNotExistsAsync(
    id: "container",
    partitionKeyPath: "/partitionKey",
    throughput: 400
);

await container.Scripts.CreateTriggerAsync(new TriggerProperties
{
    Id = "triggerId",
    Body = "function trigger() { }",
    TriggerOperation = TriggerOperation.Update,
    TriggerType = TriggerType.Pre,
});

dynamic newItem = JObject.FromObject(new
{
    id = "example_id",
    partitionKey = "example_partion_key",
});

ItemRequestOptions itemRequestOptions = new()
{
    PreTriggers = new List<string> { "triggerId" },
};

ItemResponse<JObject> response = await container.UpsertItemAsync(newItem, requestOptions: itemRequestOptions);
```

**Expected behavior**
One of the enum members of `TriggerOperation` besides `All` to allow an upsert operation.

**Actual behavior**
Any enum member of `TriggerOperation` besides `All` will result in the error `Trigger 'triggerId' was defined with operation type 'Update', and therefore is invalid for 'Upsert'.`

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos (3.35.3)
OS Version: Microsoft Windows 11 Version 22H2 (OS Build 22621.2283)

**Additional context**
```
Microsoft.Azure.Cosmos.CosmosException
  HResult=0x80131500
  Message=Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 0b599894-8098-4f11-8bde-b68461e38988; Reason: (Message: {"Errors":["Trigger 'triggerId' was defined with operation type 'Update', and therefore is invalid for 'Upsert'."]}
ActivityId: 0b599894-8098-4f11-8bde-b68461e38988, Request URI: /apps/1f212380-47e4-430e-8fa6-8da55fef6637/services/82de4af5-381a-40de-973d-027736423202/partitions/a87d52de-30e4-4202-a54c-bcebea042723/replicas/133403181326061426p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22621 cosmos-netstandard-sdk/3.31.4);
  Source=Microsoft.Azure.Cosmos.Client
  StackTrace:
   at Microsoft.Azure.Documents.StoreResult.ToResponse(RequestChargeTracker requestChargeTracker)
   at Microsoft.Azure.Documents.ConsistencyWriter.WritePrivateAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean forceRefresh)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ConsistencyWriter.WriteAsync(DocumentServiceRequest entity, TimeoutHelper timeout, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass31_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
```

**Comment by ealsur** [comment]
@DavidAlexanderPerez Please see the Cosmos DB REST API: https://learn.microsoft.com/en-us/rest/api/cosmos-db/create-a-trigger

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/1633401/c6ff40e7-f773-47cb-860d-25758c9d9b1d)

SDK acts as a contract wrapper, there is no option for Upsert. There are no SDK changes here that we can do other than following the API contract.

**Comment by ealsur** [comment]
I'll see if I can loop in someone from the service to comment

**Comment by DavidAlexanderPerez** [comment]
I saw that list, but it is missing Update which already works.

**Comment by ealsur** [comment]
@DavidAlexanderPerez Apparently I found the REST API documentation is outdated, which leads to the outdated SDK values. Upsert was added internally in the service at some point but the REST API was never updated.

We'll work on adding this enum value, it should have value `TriggerOperation.Upsert = 5` on https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/TriggerOperation.cs#L10
