### ISSUE TITLE
Unable to query CosmosDB documents using Primary/Secondary key connection with VPN and Private endpoint configured

### ISSUE THREAD

**Issue by AnnaGolosova** [Azure/azure-cosmos-dotnet-v3#4174]
**Bug description**
I have encountered one error I'm getting when I try to query some Cosmos DB document. I have the next setup:

1) Azure Cosmos DB with disabled public access and Private endpoint configured. Connection from API's and Azure Functions through this private endpoint is working fine because they're places in the same VNet.

2) We have VPN configured to have an access to VNet that contains this Private endpoint and Cosmos DB Account. We use Private DNS Zone so for my local PC I've added DNS record to my local hosts file

And with this setup I'm unable to query any documents from Cosmos DB when VPN is turned on using the next code snippet:

```
string cosmosEndpoint = "https://<you-db-account>.documents.azure.com";
string cosmosKey = "<primary/secondary-key>";
var cosmosDbId = "<db-id>";
var cosmsoContainerId = "<container-id>";

CosmosClient client = new CosmosClient(cosmosEndpoint, cosmosKey);
var container = client.GetContainer(cosmosDbId, cosmsoContainerId);

ItemResponse<JObject> response = await container.ReadItemAsync<JObject>(
    id: "<document-id>",
    partitionKey: new PartitionKey("<partition-key>")
);
```
With this code on step when we call ReadItemAsync method I'm getting the next error: 
`[CosmosException] Response status code does not indicate success: Forbidden (403); Reason: (Request originated from IP <my-ip> through public internet. This is blocked by your Cosmos DB account firewall settings.`

But I'm able to query the same document using this ways:

- Query document using HTTP request from Postman
- Query document using HTTP request from Console App
- Query document using CosmosClient with DefaultAzureCredential

**To Reproduce**
Try to query some document from CosmosDb Account with disabled public access and Private endpoint configured via VPN. Bug can be reproduced at least with code I've provided above

**Expected behavior**
Documents can be successfully requested with VPN enabled

**Actual behavior**
I'm getting the next error: 
`[CosmosException] Response status code does not indicate success: Forbidden (403); Reason: (Request originated from IP <my-ip> through public internet. This is blocked by your Cosmos DB account firewall settings.`

**Environment summary**
SDK Version: 3.36.0
OS Version: Windows 11

**Additional context**
Stack trace for CosmosException:
```
   at Microsoft.Azure.Cosmos.GatewayStoreClient.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, DocumentServiceRequest request)
   at Microsoft.Azure.Cosmos.GatewayStoreClient.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, Uri physicalAddress, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Routing.ClientCollectionCache.ReadCollectionAsync(String collectionLink, IDocumentClientRetryPolicy retryPolicyInstance, ITrace trace, IClientSideRequestStatistics clientSideRequestStatistics, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Cosmos.Common.CollectionCache.<>c__DisplayClass10_0.<<ResolveByNameAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Cosmos.Common.AsyncCache`2.GetAsync(TKey key, TValue obsoleteValue, Func`1 singleValueInitFunc, CancellationToken cancellationToken, Boolean forceRefresh)
   at Microsoft.Azure.Cosmos.Common.CollectionCache.ResolveByNameAsync(String apiVersion, String resourceAddress, Boolean forceRefesh, ITrace trace, IClientSideRequestStatistics clientSideRequestStatistics, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Common.CollectionCache.ResolveCollectionAsync(DocumentServiceRequest request, CancellationToken cancellationToken, ITrace trace)
   at Microsoft.Azure.Cosmos.Routing.ClientCollectionCache.ResolveCollectionWithSessionContainerCleanupAsync(DocumentServiceRequest request, Func`1 resolveContainerProvider)
   at Microsoft.Azure.Cosmos.AddressResolver.ResolveAddressesAndIdentityAsync(DocumentServiceRequest request, Boolean forceRefreshPartitionAddresses, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.AddressResolver.ResolveAsync(DocumentServiceRequest request, Boolean forceRefreshPartitionAddresses, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Routing.GlobalAddressResolver.ResolveAsync(DocumentServiceRequest request, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.AddressSelector.ResolveAddressesAsync(DocumentServiceRequest request, Boolean forceAddressRefresh)
   at Microsoft.Azure.Documents.AddressSelector.ResolveAllTransportAddressUriAsync(DocumentServiceRequest request, Boolean includePrimary, Boolean forceRefresh)
   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicasInternalAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)
   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicaAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)
   at Microsoft.Azure.Documents.ConsistencyReader.ReadSessionAsync(DocumentServiceRequest entity, ReadMode readMode)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass31_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
```

Thanks in advance for any help!

**Comment by sourabh1007** [comment]
This error message clearly says "request is blocked by firewall settings". You need to check your network configuration for this, other examples worked because they might be calling different URLs which are not blocked by your network.

You can refer these troubleshooting guides:
https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#sdks
https://learn.microsoft.com/EN-US/azure/cosmos-db/nosql/troubleshoot-forbidden#firewall-blocking-requests

**Comment by AnnaGolosova** [comment]
Hi @sourabh1007 !
Thanks for your response.

Firewall is configured properly (because all other requests using HTTP is working fine with turned ON VPN). An issue is only with Microsoft.Azure.Cosmos nuget package.

By a lot of tests I figured out that when we use CosmosClient class from this package, request goes to one of Cosmos DB replicas. I have account endpoint xxx-westeurope.documents.azure.com and two replicas (West Europe and North Europe). And inside of SDK URL was changed to be xxx.documents.azure.com that causes problems for me, because I have only DNS record for xxx.documents.azure.com in my local hosts file. 

I think this URL replacement isn't obvious and results in days of investigation.

**Comment by sourabh1007** [comment]
I am assuming you are running SDK in `DIRECT` mode (which is default mode, ref https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/sdk-connection-modes) that's why it is going to different replicas. If you have limitations to serve such requests, you can consider switching to gateway mode but there will be trade off. 
In that case, it will make only HTTPs request to xxx.documents.azure.com. 
To set connection mode in SDK, ref. https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.connectionmode?view=azure-dotnet#microsoft-azure-cosmos-cosmosclientoptions-connectionmode

**Comment by AnnaGolosova** [comment]
Hi @sourabh1007! I tried both with `Gateway` and `Direct` modes, and in both cases I got the same 403 exception. In both cases (just re-checked) request's going to `xxx-westeurope.documents.azure.com` instead of `xxx.documents.azure.com`. And I assume that for this reason request was sent through public internet because only xxx.documents.azure.com was in local DNS hosts file.

This behavior isn't ok for us because replicas set can be changed and we don't want to handle it manually every time.

**Comment by sourabh1007** [comment]
This is expected behavior of SDK, SDK talks to regional endpoints for any account. you need to configure your firewall setting accordingly.
Here it is explained, how you should set up private endpoint for muti region set up.
https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-configure-private-endpoints?tabs=arm-bicep#update-a-private-endpoint-when-you-add-or-remove-a-region
