### ISSUE TITLE
Not support Linq feature

### ISSUE THREAD

**Issue by joelsteventurner** [Azure/azure-cosmos-dotnet-v3#4586]
**Describe the bug**
I am using `Microsoft.AspNetCore.OData` in conjunction with Cosmos and sometime the LINQ statements produced don't work against Cosmos LINQ provider. This is to do with a 1 -1 child on the document. (see below). Adding a simple Child object like this cause the generated LINQ statement to not be supported, which it seems an obvious use case which should be supported.

```csharp

public class MyDocument
{
    public Child Child { get; set; }
}

```

Stack trace if it helps.

Microsoft.Azure.Cosmos.Linq.DocumentQueryException: Expression with NodeType \u0027Default\u0027 is not supported., Windows/10.0.22621 cosmos-netstandard-sdk/3.34.4
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression expression, ReadOnlyCollection\u00601 parameters, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitScalarExpression(Expression expression, ReadOnlyCollection\u00601 parameters, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitScalarExpression(Expression expression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitBinary(BinaryExpression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression expression, ReadOnlyCollection\u00601 parameters, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitScalarExpression(Expression expression, ReadOnlyCollection\u00601 parameters, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitScalarExpression(Expression expression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitConditional(ConditionalExpression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression expression, ReadOnlyCollection\u00601 parameters, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitScalarExpression(Expression expression, ReadOnlyCollection\u00601 parameters, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitScalarExpression(Expression expression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitMemberAssignment(MemberAssignment inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitBinding(MemberBinding binding, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitBindingList(ReadOnlyCollection\u00601 inputExpressionList, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitMemberInit(MemberInitExpression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitNonSubqueryScalarExpression(Expression expression, ReadOnlyCollection\u00601 parameters, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitScalarExpression(Expression expression, ReadOnlyCollection\u00601 parameters, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitScalarExpression(LambdaExpression lambda, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitSelect(ReadOnlyCollection\u00601 arguments, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.VisitMethodCall(MethodCallExpression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.Translate(Expression inputExpression, TranslationContext context)
   at Microsoft.Azure.Cosmos.Linq.ExpressionToSql.TranslateQuery(Expression inputExpression, IDictionary\u00602 parameters, CosmosLinqSerializerOptionsInternal linqSerializerOptions, ScalarOperationKind\u0026 clientOperation)
   at Microsoft.Azure.Cosmos.Linq.SqlTranslator.TranslateQuery(Expression inputExpression, CosmosLinqSerializerOptionsInternal linqSerializerOptions, IDictionary\u00602 parameters)
   at Microsoft.Azure.Cosmos.Linq.DocumentQueryEvaluator.HandleMethodCallExpression(MethodCallExpression expression, IDictionary\u00602 parameters, CosmosLinqSerializerOptionsInternal linqSerializerOptions)
   at Microsoft.Azure.Cosmos.Linq.DocumentQueryEvaluator.Evaluate(Expression expression, CosmosLinqSerializerOptionsInternal linqSerializerOptions, IDictionary\u00602 parameters)
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery\u00601.CreateStreamIterator(Boolean isContinuationExcpected, ScalarOperationKind\u0026 scalarOperationKind)
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery\u00601.CreateFeedIterator(Boolean isContinuationExpected, ScalarOperationKind\u0026 scalarOperationKind)
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery\u00601.ToFeedIterator()
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqExtensions.ToFeedIterator[T](IQueryable\u00601 query)
   at CosmosRepoChanges.Infrastructure.Repositories.CosmosDBRepositoryBase\u00603.ProcessResults[TProjection](IQueryable\u00601 query, CancellationToken cancellationToken) in C:\\Workshop\\CosmosRepoChanges\\CosmosRepoChanges\\CosmosRepoChanges.Infrastructure\\Repositories\\CosmosDBRepositoryBase.cs:line 285
   at CosmosRepoChanges.Infrastructure.Repositories.CosmosDBRepositoryBase\u00603.FindAllProjectToAsync[TProjection](Expression\u00601 filterExpression, Func\u00602 filterProjection, CancellationToken cancellationToken) in C:\\Workshop\\CosmosRepoChanges\\CosmosRepoChanges\\CosmosRepoChanges.Infrastructure\\Repositories\\CosmosDBRepositoryBase.cs:line 258
   at CosmosRepoChanges.Application.Clients.GetClients.GetClientsQueryHandler.Handle(GetClientsQuery request, CancellationToken cancellationToken) in C:\\Workshop\\CosmosRepoChanges\\CosmosRepoChanges\\CosmosRepoChanges.Application\\Clients\\GetClients\\GetClientsQueryHandler.cs:line 28
   at CosmosRepoChanges.Application.Common.Behaviours.ValidationBehaviour\u00602.Handle(TRequest request, RequestHandlerDelegate\u00601 next, CancellationToken cancellationToken) in C:\\Workshop\\CosmosRepoChanges\\CosmosRepoChanges\\CosmosRepoChanges.Application\\Common\\Behaviours\\ValidationBehaviour.cs:line 36
   at CosmosRepoChanges.Application.Common.Behaviours.AuthorizationBehaviour\u00602.Handle(TRequest request, RequestHandlerDelegate\u00601 next, CancellationToken cancellationToken) in C:\\Workshop\\CosmosRepoChanges\\CosmosRepoChanges\\CosmosRepoChanges.Application\\Common\\Behaviours\\AuthorizationBehaviour.cs:line 83
   at CosmosRepoChanges.Application.Common.Behaviours.PerformanceBehaviour\u00602.Handle(TRequest request, RequestHandlerDelegate\u00601 next, CancellationToken cancellationToken) in C:\\Workshop\\CosmosRepoChanges\\CosmosRepoChanges\\CosmosRepoChanges.Application\\Common\\Behaviours\\PerformanceBehaviour.cs:line 35
   at CosmosRepoChanges.Application.Common.Behaviours.UnhandledExceptionBehaviour\u00602.Handle(TRequest request, RequestHandlerDelegate\u00601 next, CancellationToken cancellationToken) in C:\\Workshop\\CosmosRepoChanges\\CosmosRepoChanges\\CosmosRepoChanges.Application\\Common\\Behaviours\\UnhandledExceptionBehaviour.cs:line 27
   at CosmosRepoChanges.Api.Controllers.ClientsController.GetClients(ODataQueryOptions\u00601 oDataOptions, CancellationToken cancellationToken) in C:\\Workshop\\CosmosRepoChanges\\CosmosRepoChanges\\CosmosRepoChanges.Api\\Controllers\\ClientsController.cs:line 149
   at lambda_method707(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Awaited|12_0(ControllerActionInvoker invoker, ValueTask\u00601 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

**Actual behavior**
Crashes with a LINQ not support error : see above.

**Comment by bartelink** [comment]
Code and a minimal failing example would help people to track it down. Also why not include the details of `Child`
You're not paying per word to send a telegram ;)

**Comment by joelsteventurner** [comment]
Hahaha, Sure np let me try give you more context. Let me know if there are more specifics you need.

Odata is producing a Func<IQueryable, IQueryable> which I am forwarding to Cosmos.

This was working fine on Simple Documents with out Child objects, i.e. just primitive fields.
As soon as I added the Child object 'Preferences' the problem started.

Below is the "DebugView" of the LINQ Query the OData assembly is producing.

The issue I assume is around the line (and or the line below)
"Preferences = .If ($dtoIClientDocument.Preferences == .Default(System.Object))"

```text
.Call System.Linq.Queryable.Select(
    .Constant<Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery`1[CosmosRepoChanges.Domain.Repositories.Documents.IClientDocument]>(dbs/TestDb/colls/Container),
    '(.Lambda #Lambda1<System.Func`2[CosmosRepoChanges.Domain.Repositories.Documents.IClientDocument,CosmosRepoChanges.Application.Clients.ClientDto]>))

.Lambda #Lambda1<System.Func`2[CosmosRepoChanges.Domain.Repositories.Documents.IClientDocument,CosmosRepoChanges.Application.Clients.ClientDto]>(CosmosRepoChanges.Domain.Repositories.Documents.IClientDocument $dtoIClientDocument)
{
    .New CosmosRepoChanges.Application.Clients.ClientDto(){
        Id = $dtoIClientDocument.Id,
        Name = $dtoIClientDocument.Name,
        Surname = $dtoIClientDocument.Surname,
        Addresses = .Call System.Linq.Enumerable.ToList(.Call System.Linq.Enumerable.Select(
                $dtoIClientDocument.Addresses,
                .Lambda #Lambda2<System.Func`2[CosmosRepoChanges.Domain.Repositories.Documents.IAddressDocument,CosmosRepoChanges.Application.Clients.ClientAddressDto]>)
        ),
        Preferences = .If ($dtoIClientDocument.Preferences == .Default(System.Object)) {
            .Default(CosmosRepoChanges.Application.Clients.ClientPreferencesDto)
        } .Else {
            .New CosmosRepoChanges.Application.Clients.ClientPreferencesDto(){
                News = ($dtoIClientDocument.Preferences).News,
                Specials = ($dtoIClientDocument.Preferences).Specials
            }
        }
    }
}

.Lambda #Lambda2<System.Func`2[CosmosRepoChanges.Domain.Repositories.Documents.IAddressDocument,CosmosRepoChanges.Application.Clients.ClientAddressDto]>(CosmosRepoChanges.Domain.Repositories.Documents.IAddressDocument $dtoIAddressDocument)
{
    .New CosmosRepoChanges.Application.Clients.ClientAddressDto(){
        Line1 = $dtoIAddressDocument.Line1,
        Line2 = $dtoIAddressDocument.Line2,
        Id = $dtoIAddressDocument.Id
    }
}
```
Document Contract
```csharp

public interface IClientDocument
{
    string Id { get; }
    string Name { get; }
    string Surname { get; }
    IPreferencesDocument Preferences { get; }
    IReadOnlyList<IAddressDocument> Addresses { get; }
}

public interface IAddressDocument
{
    string Id { get; }
    string Line1 { get; }
    string Line2 { get; }
}

public interface IPreferencesDocument
{
    bool? News { get; }
    bool? Specials { get; }
}
```

DTO Contract
```csharp

public class ClientDto 
{
    public ClientDto()
    {
        Id = null!;
        Name = null!;
        Surname = null!;
        Addresses = null!;
        Preferences = null!;
    }

    public string Id { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public List<ClientAddressDto> Addresses { get; set; }
    public ClientPreferencesDto Preferences { get; set; }

    public static ClientDto Create(
        string id,
        string name,
        string surname,
        List<ClientAddressDto> addresses,
        ClientPreferencesDto preferences)
    {
        return new ClientDto
        {
            Id = id,
            Name = name,
            Surname = surname,
            Addresses = addresses,
            Preferences = preferences
        };
    }

    public void Mapping(Profile profile)
    {
        profile.CreateMap<Client, ClientDto>()
            .ForMember(d => d.Addresses, opt => opt.MapFrom(src => src.Addresses));

        profile.CreateMap<IClientDocument, ClientDto>()
            .ForMember(d => d.Addresses, opt => opt.MapFrom(src => src.Addresses));
    }
}

public class ClientPreferencesDto
{
    public ClientPreferencesDto()
    {
    }

    public bool? News { get; set; }
    public bool? Specials { get; set; }

    public static ClientPreferencesDto Create(bool? news, bool? specials)
    {
        return new ClientPreferencesDto
        {
            News = news,
            Specials = specials
        };
    }

    public void Mapping(Profile profile)
    {
        profile.CreateMap<Preferences, ClientPreferencesDto>();

        profile.CreateMap<IPreferencesDocument, ClientPreferencesDto>();
    }
}

    public class ClientAddressDto 
    {
        public ClientAddressDto()
        {
            Line1 = null!;
            Line2 = null!;
            Id = null!;
        }

        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Id { get; set; }

        public static ClientAddressDto Create(string line1, string line2, string id)
        {
            return new ClientAddressDto
            {
                Line1 = line1,
                Line2 = line2,
                Id = id
            };
        }

        public void Mapping(Profile profile)
        {
            profile.CreateMap<Address, ClientAddressDto>();

            profile.CreateMap<IAddressDocument, ClientAddressDto>();
        }
    }


```

**Comment by bartelink** [comment]
Basic scan (I am not on the team and don't use Cosmos LINQ in this way) says that your query is not possible to translate as it is - projections of the form `Func<Queryable<X>, Expression<Y>>` can work (not all forms are supported), but the Cosmos LINQ support can't magically map/remote a `Func<X,Y>`

The answer can be as simple as a `.ToEnumerable()` to mark the end of the expression tree bit, and the start of the client side in-memory mapping, or it might mean a big gap.

I'll let someone from the team answer, but tbh this is looking a lot like the sort of question that's best addressed on StackOverflow than here as the specifics of AutoMapper, OData etc may or may not be street lingo for watchers of this repo.
