### ISSUE TITLE
ArgumentNullException Parameter name: errorMessage

### ISSUE THREAD

**Issue by RobinHSanner** [Azure/azure-cosmos-dotnet-v3#518]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Exception from CosmosClient when testing under load.  The exception is an ArgumentNullException without any innerexception.

The exception occurs on a ItemLinqQueryable<T>.Where(predicate).ToFeedIterator<T>() iterator calling: await iterator.ReadNextAsync(cancellationToken);

**To Reproduce**
Create a task that executes 10000 the CosmosClient methods CreateItemStreamAsync, ReadItemStringAsync and ItemLinqQueryable.ToFeedIterator.ReadNextAsync.

The linq anonymous function that is being called is: i => i.StringProperty.Contains(string)

**Expected behavior**
- A CosmosException should be thrown not an ArgumentNullException
- Internally the code shouldn't be causing their own exception which masks some exception I caused but can't figure out because yours masked it.

**Actual behavior**
- ArgumentNullException is throw from an SDK code error
- I can't tell what exception caused the issue in the first place which probably has to do with the load

**Environment summary**
SDK Version: 3.0.0.19-preview
OS Version (e.g. Windows, Linux, MacOSX): Windows 1809 (OS Build 17763.557)
CosmosDB Emulator version: 2.4.5.0

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).
System.ArgumentNullException: Value cannot be null.
Parameter name: errorMessage
   at Microsoft.Azure.Cosmos.QueryResponse.CreateFailure(CosmosQueryResponseMessageHeaders responseHeaders, HttpStatusCode statusCode, RequestMessage requestMessage, String errorMessage, Error error)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.GetCosmosElementResponse(QueryRequestOptions requestOptions, ResourceType resourceType, String containerResourceId, ResponseMessage cosmosResponseMessage)
   at Microsoft.Azure.Cosmos.CosmosQueryClientCore.ExecuteItemQueryAsync(Uri resourceUri, ResourceType resourceType, OperationType operationType, String containerResourceId, QueryRequestOptions requestOptions, SqlQuerySpec sqlQuerySpec, Action`1 requestEnricher, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryContext.ExecuteQueryAsync(SqlQuerySpec querySpecForInit, CancellationToken cancellationToken, Action`1 requestEnricher)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.BufferMoreDocumentsAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.BufferMoreIfEmptyAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.MoveNextAsyncImplementationAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducer.MoveNextAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.TryMoveNextAsyncImplementationAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.ExecuteWithSplitProofingAsync(Func`2 function, Boolean functionNeedsBeReexecuted, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.ItemProducerTree.MoveNextAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.CosmosCrossPartitionQueryExecutionContext.MoveNextHelperAsync(ItemProducerTree itemProducerTree, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosParallelItemQueryExecutionContext.InternalDrainAsync(Int32 maxElements, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosCrossPartitionQueryExecutionContext.DrainAsync(Int32 maxElements, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.ExecuteNextAsync(CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.ExecuteNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ContainerCore.NextResultSetAsync[T](Nullable`1 maxItemCount, String continuationToken, RequestOptions options, Object state, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.ReadNextAsync(CancellationToken cancellationToken)

**Comment by j82w** [comment]
This is a bug that it is getting wrapped. This should just throw the original exception. 

By any chance do you know what status code was hit for this error? It seems weird that the status code was a failure, and the error message was null.

**Comment by RobinHSanner** [comment]
No the internal error masks the original exception.

**Comment by j82w** [comment]
Based on the call stack it's getting thrown from [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f69a7f272682c8fd78dbe91b32a0bd9eee68752e/Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryResponse.cs#L135) with the caller [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/0603747640efde2b40c4768d6e01bc7e0d4826a0/Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs#L217). Unfortunately the original argument null exception doesn't include any information about the response so even the original exception wouldn't have any additional information.

**Comment by RobinHSanner** [comment]
That’s correct.

**Comment by j82w** [comment]
Any chance you have a repo you can share?

**Comment by RobinHSanner** [comment]
It’s a customer repo sorry.  I could send you a summary of the operations though.

**Comment by j82w** [comment]
Thanks, do you also know how many RU's the container had?

**Comment by RobinHSanner** [comment]
No, how do I tell that?  I can reproduce the error easily.

**Comment by j82w** [comment]
When you create the container did you specify the RUs? It defaults to 400.

this.database.CreateContainerAsync("id", "/pk", 400)? 

The Cosmos DB Emulator explorer shows it. Right click on Cosmos DB emulator icon -> Data Explorer -> Explorer (left side) -> click database -> click container -> scale & settings.

**Comment by RobinHSanner** [comment]
Oh I thought you meant the current load.  Yes I specified 400.  I was trying to test for 429 errors to make sure I was handling them correctly.

**Comment by j82w** [comment]
I was able to get a repo. I'll have a PR and fix out tomorrow. Thanks for the help.

**Comment by RobinHSanner** [comment]
Thank you
