### ISSUE TITLE
System.ArgumentNullException: 'Value cannot be null. Parameter name: continuation can not be null or empty.'

### ISSUE THREAD

**Issue by mark-manticore** [Azure/azure-cosmos-dotnet-v3#621]
**Describe the bug**
Calling container.GetItemQueryStreamIterator() to get a feedIterator and then calling feedIterator.ReadNextAsync() throws an exception.

**To Reproduce**
Using Microsoft Azure Cosmos Emulator 2.4.5.0 (ddf424be)
Using Cosmos SDK v3.1
With or without custom serializer doesn't matter
Container exists but no documents are in it
Query shouldnt matter but this was mine: 
```
var requestOptions = new QueryRequestOptions();
requestOptions.EnableScanInQuery = true;
var feedIterator = container.GetItemQueryStreamIterator("SELECT VALUE root[\"id\"] FROM root ORDER BY root[\"Created\"] DESC", null, requestOptions);
feedIterator.ReadNextAsync(); // Exception here
```

**Expected behavior**
No exception and a stream with json something like {"_rid":"blah","Documents":[],"_count":0}

**Actual behavior**
Exception thrown

**Environment summary**
SDK Version: 3.1
OS Version: Windows

**Additional context**
```
System.ArgumentNullException: 'Value cannot be null.
Parameter name: continuation can not be null or empty.'

   at Microsoft.Azure.Cosmos.Query.CosmosOrderByItemQueryExecutionContext.ValidateAndExtractContinuationToken(String requestContinuation, SortOrder[] sortOrders, String[] orderByExpressions)
   at Microsoft.Azure.Cosmos.Query.CosmosOrderByItemQueryExecutionContext.InitializeAsync(SqlQuerySpec sqlQuerySpec, String requestContinuation, String collectionRid, List`1 partitionKeyRanges, Int32 initialPageSize, SortOrder[] sortOrders, String[] orderByExpressions, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosOrderByItemQueryExecutionContext.CreateAsync(CosmosQueryContext constructorParams, CrossPartitionInitParams initParams, CancellationToken token)
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.<>c__DisplayClass6_0.<<CreateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.CreateHelperAsync(QueryInfo queryInfo, Int32 initialPageSize, String requestContinuation, Func`2 createOrderByQueryExecutionContext, Func`2 createParallelQueryExecutionContext)
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.CreateAsync(CosmosQueryContext constructorParams, String collectionRid, PartitionedQueryExecutionInfo partitionedQueryExecutionInfo, List`1 partitionKeyRanges, Int32 initialPageSize, String requestContinuation, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.CreateSpecializedDocumentQueryExecutionContextAsync(CosmosQueryContext cosmosQueryContext, PartitionedQueryExecutionInfo partitionedQueryExecutionInfo, List`1 targetRanges, String collectionRid, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.CreateItemQueryExecutionContextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.ExecuteNextHelperAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.ReadNextAsync(CancellationToken cancellationToken)
   at <snip application call point>
```

**Comment by j82w** [comment]
I copied your exact code and it did not repo. Are you sure that the provided repo is the cause of the exception? The reason I ask is in the repo continuation token is null, but this error is only thrown if there is a [continuation token](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/f69a7f272682c8fd78dbe91b32a0bd9eee68752e/Microsoft.Azure.Cosmos/src/Query/CosmosOrderByItemQueryExecutionContext.cs#L272).

**Comment by mark-manticore** [comment]
My apologies it was an empty string passed in as the continuation token and I missed it.

**Comment by j82w** [comment]
Thanks for the update. I will create an issue to add a block for empty string so it's easier to debug in the future.

**Comment by j82w** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/628
