### ISSUE TITLE
"Compositions of aggregates and other expressions are not allowed." when using 'Any'

### ISSUE THREAD

**Issue by coffeymatt** [Azure/azure-cosmos-dotnet-v3#899]
**Describe the bug**

I've got a Cosmos db linq query, and if I call 'Any()' on that query, it gives me the following exception:

> Compositions of aggregates and other expressions are not allowed.

But if I use 'Count() > 0' it does what I need. I thought 'any' was supported now?

**To Reproduce**
Execute a linq expression with a where clause and 'Any()'.

**Expected behavior**
Same behaviour as I get with 'Count() > 0'.

**Actual behavior**
Throws 400: Compositions of aggregates and other expressions are not allowed.

**Environment summary**
SDK Version: 3.3.0
OS Version: Windows 10

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

> Response status code does not indicate success: 400 Substatus: 0 Reason: (Message: {"Errors":["Compositions of aggregates and other expressions are not allowed."]}).

>    at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.CreateQueryFeedResponseHelper[T](ResponseMessage cosmosResponseMessage, Boolean usePropertySerializer)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.<ReadNextAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery`1.<GetEnumerator>d__20.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Azure.Cosmos.Linq.CosmosLinqQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source)

**Comment by j82w** [comment]
@khdang can you please take a look?

**Comment by khdang** [comment]
Any() is supported when it is nested in another operator, such as Where in this expression: collection.Where(item => item.subItems.Any(subItem => subItem.property1 > 0))

This is a known issue only in the SDK for Any() on the top level expression. for example in this expression: collection.Any(). For such expression, the LINQ provider translates to the closest SQL query which is SELECT VALUE COUNT(1) > 0 .... However evaluation on the aggregate expression is not supported yet on the SDK.

As you mentioned, the workaround for this case would be to do Count() > 0 on the client which is equivalent to Any().
