### ISSUE TITLE
Group by queries not parsing on non-windows machines, or 32-bit processes - sends to gateway but errors

### ISSUE THREAD

**Issue by TheOnlyBryan** [Azure/azure-cosmos-dotnet-v3#974]
**Describe the bug**
When processing a group by query, the call to CustomTypeExtensions.ByPassQueryParsing() returns a true for all non-windows machines, which then sends the query off to the gateway.  The gateway then reports an error: System.ArgumentNullException: Value cannot be null. Parameter name: orderedAliases

**To Reproduce**
Run a CosmosDB query on a non-windows machine, or a process that is only 32-bit, that contains the group by clause. 

**Expected behavior**
Query returns data.

**Actual behavior**
The following error is reported: System.ArgumentNullException: Value cannot be null. Parameter name: orderedAliases

**Environment summary**
SDK Version: 3.4.0
OS Version: MacOS or Microsoft Windows NT 10.0.14393.0 with 32-bit process

**Additional context**
System.ArgumentNullException: Value cannot be null.
Parameter name: orderedAliases
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionComponent.GroupByDocumentQueryExecutionComponent..ctor(CosmosQueryClient cosmosQueryClient, IReadOnlyDictionary`2 groupByAliasToAggregateType, IReadOnlyList`1 orderedAliases, Boolean hasSelectValue, IDocumentQueryExecutionComponent source)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionComponent.GroupByDocumentQueryExecutionComponent.CreateAsync(CosmosQueryClient cosmosQueryClient, String requestContinuation, Func`2 createSourceCallback, IReadOnlyDictionary`2 groupByAliasToAggregateType, IReadOnlyList`1 orderedAliases, Boolean hasSelectValue)
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.<>c__DisplayClass7_3.<<CreateHelperAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.CreateHelperAsync(ExecutionEnvironment executionEnvironment, CosmosQueryClient queryClient, QueryInfo queryInfo, Int32 initialPageSize, String requestContinuation, Func`2 createOrderByQueryExecutionContext, Func`2 createParallelQueryExecutionContext)
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.CreateAsync(ExecutionEnvironment executionEnvironment, CosmosQueryContext queryContext, CrossPartitionInitParams initParams, String requestContinuationToken, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.CreateSpecializedDocumentQueryExecutionContextAsync(CosmosQueryContext cosmosQueryContext, InputParameters inputParameters, PartitionedQueryExecutionInfo partitionedQueryExecutionInfo, List`1 targetRanges, String collectionRid, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.CreateFromPartitionedQuerExecutionInfoAsync(PartitionedQueryExecutionInfo partitionedQueryExecutionInfo, ContainerQueryProperties containerQueryProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.CreateItemQueryExecutionContextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.ExecuteNextAsync(CancellationToken cancellationToken)

**Comment by j82w** [comment]
@bchong95 is this a known issue?

**Comment by bchong95** [comment]
I think it's just waiting for a gateway deployment.

**Comment by TheOnlyBryan** [comment]
Is there an ETA on gateway deployment?

**Comment by Splaxi** [comment]
I'm building a Azure App Function and trying to debug it from Visual Studio. It fails just like mentioned by @TheOnlyBryan 

I was however able to download the x64 version of the azure function core tools and use that while debugging and now things are running like expected.

https://stackoverflow.com/questions/50853396/debugging-x64-azure-functions-in-visual-studio

**Comment by eddadjei** [comment]
Any update on this? Spent 8 hours today chasing down this issue. I noticed in the Microsoft.Azure.Cosmos.Query.QueryInfo class, the following is coming out as null.

 [JsonProperty("groupByAliases")]
        public string[] GroupByAliases
        {
            get;
            set;
        }
<img width="947" alt="Screen Shot 2019-11-07 at 10 52 06 PM" src="https://user-images.githubusercontent.com/3740077/68450636-5aa7b180-01b1-11ea-912d-84522f1e6521.png">

**Comment by BharathPalanivelu** [comment]
Any resolution to this issue? Same code works in local machine but once pushed to Azure app service fails with this error message "cosmos System.ArgumentNullException: Value cannot be null. Parameter name: orderedAliases"

**Comment by j82w** [comment]
We are working on the fix. If you run it as 64bit app on Windows you will not hit this issue. Hopefully we can give a timeframe later today.

**Comment by j82w** [comment]
Can you please email at askcosmosdb@microsoft.com regarding this issue. This is a service issue, and we only work on the SDK.

**Comment by Splaxi** [comment]
I believe you need to share a bit more in regards on the comment on the "This is a service issue, and we only work on the SDK".

Should we translate that into that the SDK is getting a bad request back from the CosmosDB service, but the error handling inside the SD, is unable to provide us with that information?

**Comment by j82w** [comment]
Yes, that is how you should translate it. Here is a more detailed description.

In order to support group by queries several changes and information was added to the query plan. On Windows x64 machine there is a ServiceInterop.dll that can create the query plan locally, and has all the required changes. If you are on a platform that is not supported by the ServiceInterop.dll like Windows x32 application it goes to the gateway to get the query plan. The gateway is missing a change which adds the required fields for group by queries. The SDK can not process the bad query plan, and it causes the exception you are hitting. There was never any testing against this scenario as the service should have been deployed first, so there is no graceful exception.

**Comment by BharathPalanivelu** [comment]
App service is already running in 64-bit mode

**Following is the error log we receive.**

System.ArgumentNullException: Value cannot be null.
Parameter name: orderedAliases
   at Microsoft.Azure.Cosmos.Query.SingleGroupAggregator.SelectListAggregateValues..ctor(IReadOnlyDictionary`2 aliasToValue, IReadOnlyList`1 orderedAliases)
   at Microsoft.Azure.Cosmos.Query.SingleGroupAggregator.SelectListAggregateValues.Create(CosmosQueryClient cosmosQueryClient, IReadOnlyDictionary`2 aggregateAliasToAggregateType, IReadOnlyList`1 orderedAliases, String continuationToken)
   at Microsoft.Azure.Cosmos.Query.SingleGroupAggregator.Create(CosmosQueryClient queryClient, AggregateOperator[] aggregates, IReadOnlyDictionary`2 aggregateAliasToAggregateType, IReadOnlyList`1 orderedAliases, Boolean hasSelectValue, String continuationToken)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionComponent.AggregateDocumentQueryExecutionComponent.ClientAggregateDocumentQueryExecutionComponent.CreateAsync(CosmosQueryClient queryClient, AggregateOperator[] aggregates, IReadOnlyDictionary`2 aliasToAggregateType, IReadOnlyList`1 orderedAliases, Boolean hasSelectValue, String requestContinuation, Func`2 createSourceCallback)
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionComponent.AggregateDocumentQueryExecutionComponent.CreateAsync(ExecutionEnvironment executionEnvironment, CosmosQueryClient queryClient, AggregateOperator[] aggregates, IReadOnlyDictionary`2 aliasToAggregateType, IReadOnlyList`1 orderedAliases, Boolean hasSelectValue, String requestContinuation, Func`2 createSourceCallback)
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.<>c__DisplayClass7_1.<<CreateHelperAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Cosmos.Query.Core.ExecutionComponent.DistinctDocumentQueryExecutionComponent.CreateAsync(CosmosQueryClient queryClient, String requestContinuation, Func`2 createSourceCallback, DistinctQueryType distinctQueryType)
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.<>c__DisplayClass7_2.<<CreateHelperAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.CreateHelperAsync(ExecutionEnvironment executionEnvironment, CosmosQueryClient queryClient, QueryInfo queryInfo, Int32 initialPageSize, String requestContinuation, Func`2 createOrderByQueryExecutionContext, Func`2 createParallelQueryExecutionContext)
   at Microsoft.Azure.Cosmos.Query.PipelinedDocumentQueryExecutionContext.CreateAsync(ExecutionEnvironment executionEnvironment, CosmosQueryContext queryContext, CrossPartitionInitParams initParams, String requestContinuationToken, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.CreateSpecializedDocumentQueryExecutionContextAsync(CosmosQueryContext cosmosQueryContext, InputParameters inputParameters, PartitionedQueryExecutionInfo partitionedQueryExecutionInfo, List`1 targetRanges, String collectionRid, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.CreateFromPartitionedQuerExecutionInfoAsync(PartitionedQueryExecutionInfo partitionedQueryExecutionInfo, ContainerQueryProperties containerQueryProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.CreateItemQueryExecutionContextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.CosmosQueryExecutionContextFactory.ExecuteNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Query.QueryIterator.ReadNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.FeedIteratorCore`1.ReadNextAsync(CancellationToken cancellationToken)


   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by Splaxi** [comment]
@BharathPalanivelu 

Are you sure that your App Service is really running x64? 🤔 All my testing and everyone else that have reported this issue confirms that x64 works. 

Even Microsoft officials confirm that they are aware of the issue with x86 and that x64 is not affected.

Could you try and follow the guide that I posted earlier in this thread and see if you can make it work?

**Comment by BharathPalanivelu** [comment]
@Splaxi  let me try the guide and reply back... 

i see my app service is 64-Bit

How i checked... 
went to my App Service --> "Configuration" -> "General Settings" --> "Platform Settings"--> "Platform" --> "64-Bit"

Following is KUDU Environment details for my app service
System info
System up time: 3.00:44:58.6560000
OS version: Microsoft Windows NT 10.0.14393.0
64 bit system: True
64 bit process: True
Processor count: 1

**Comment by j82w** [comment]
@BharathPalanivelu the issue is the ServiceInterop.dll is not getting loaded in the App Service so it is falling back to the gateway to get the query plan. Please make sure the ServiceInterop.dll is in the same folder as the application. Please create a new issue if you want to further debug so we keep the discussion focused on the original issue.

**Comment by bchong95** [comment]
Gateway hotfix is deployed.
